(define burger (list
"32 32 9 1"
" 	s background	c None"
".	c tan"
"X	c white"
"o	c #ff0000000000"
"O	c #c000c000c000"
"+	c #000080000000"
"@	c #800000000000"
"#	c black"
"$	c #ff00ff000000"
"                                "
"                                "
"                                "
"                                "
"                                "
"                                "
"                                "
"                                "
"          ...........           "
"       .............X..         "
"     .................X...      "
"    .................X......    "
"   ..............o...........   "
"  ............................  "
" .............................. "
" .......................o....O. "
" ...............o.....o.ooo.... "
" ............o..o.oo.....o....  "
"   ...............ooo.......    "
"  +           ........          "
" + +++++++++++      +++++++++++ "
"   +++@@@ ++++++++++++++#@ @@@+ "
"       @@@@@@  +++++@@@@@@@@@   "
"   $@@@@@@@@@@@@@@+++++$@@@$$   "
" @@@@@@@@@@@@$@@@@@@@@@@@@@@@@@ "
" @@@@@@@@@@@@@@@@@@@@@@@@@@@@@@ "
" @@@@@@@@@@@@@@@@@@@@@@@@@@@@@  "
"  @@@@@@@@@@@@@@@@@@@@@@@@@@..  "
"  ....@@.@@@@@.@@@@@@@@.......  "
"   ................o.o........  "
"    .........................   "
"       ....................     "))

(define syringe (list
"32 32 5 1"
" 	s background	c None"
".	c black"
"X	c white"
"o	c slate grey"
"O	c grey"
"                                "
"                          .     "
"                         .X.    "
"                         .XX.   "
"                          .oo.  "
"                   ..    .o.OO. "
"                   .X.  .o.o..o "
"                    .X..o.O ooo "
"                    .XX..o      "
"                   .X.oo.O      "
"                  .XXo.oO.O     "
"                 .XXooO..O.O    "
"                .X.ooO.OO..O    "
"               .XXooO.Oooooo    "
"              .X.ooO.Oo         "
"             .XXooO.Oo          "
"            .X.ooO.Oo           "
"           .XXooO.Oo            "
"          .X.ooO.Oo             "
"         .XXooO.Oo              "
"        .X.ooO.Oo               "
"        ..X.O.Oo                "
"        .o.X.Oo                 "
"       .o...Oo                  "
"       ..OOOo                   "
"      .ooooo                    "
"     .o                         "
"    .o                          "
"   .o                           "
"  .o                            "
" .o                             "
"                                "))

(define media (list
"32 32 11 1"
"` c black"
"a c cyan"
"b c green"
"c c dodger blue"
"d c firebrick"
"e c red"
"f c navy blue"
"g c tomato"
"h c yellow"
"i c slate grey"
"j c blue"
"````````````````````````````````"
"`iii``iiiiiiiiiiiiiiiiiiiiiiigg`"
"`ii`iiii``iibiiiiiiiiiiiiiiiigg`"
"`i`iii``iiiibiiiiiiiiiiiiiiiggg`"
"``iii`iiiiiibiiiiiiiiiiiiiiiggg`"
"``ii`iii``iiibiiiiiiiigddiiggge`"
"`ii`iii`iiiiibiiiiiiigeeddegeee`"
"`ii`ii`iiiiiiiiiiiiiggeeeddeeei`"
"`i`ii`iii`iiccccciigggeeidddeii`"
"`i`ii`ii`icccccccggggeeiiiiiiii`"
"`iiiiiiiicccaaaccgggeeiiiiiiiii`"
"`iiiiiiiiccaaaacccgeeiiiiiiiiii`"
"`iiiiiiiccaaaaaccccjfiiiiiiiiii`"
"`iiiiiiiccaaaaccccjjfiiiiiiiiii`"
"`ihiiiiiccaaacccccjffiiiiiiiiii`"
"`ihiiiiicccccccccjjffibbiiiiiii`"
"`iiiiiiicccccccccjfffiiibbbbiii`"
"`iiiiiiiicceeccjjfffiiiiiiiibbi`"
"`iiihiiiijeeeejjffffiiiiiiiiiii`"
"`iiiiiiiiieeeefffffiiiiiiiiiiii`"
"`iiiiiiiiiieeffffiiihhiiiiiiiii`"
"`iiiiiiiiiiiiiiiiiihiihiiiiiiii`"
"`iiiiiiibbiieeiiiiiiiiihiiiiiii`"
"`iiiiiibbbieeeeihiiiiiihiiiiiii`"
"`iiiiibbbiieeeeiiiiiiiiihiiiiii`"
"`iiiibbbiiiieeihiiiiiiiihiiiiii`"
"`iiiibbiiiiiiiiiiiiiiiihiiiiiii`"
"`iiibbbiiiiiiiiiiiiiiihhiiiiiii`"
"`iibbbiiiiiiiiiihiiiihiihiiiiii`"
"`ibbbiiiiiiiiiiiiiiiihiihhhiiii`"
"`iibiiiiiiiiiiiiiiiiiihhiiihhii`"
"````````````````````````````````"
))

(define tut (list
"32 32 8 1"
" 	s background	c None"
".	c #ff00ff000000"
"X	c black"
"o	c #00000000ff00"
"O	c #ff0000000000"
"+	c #800080000000"
"@	c #000080008000"
"#	c #800000000000"
"                                "
"             .XX.XX.            "
"         .X.X.XX.XX...X.        "
"       .X.X.XX.X.X.XX.X.X.      "
"       .X.XX.X.X.X.X.XX.X.      "
"     .X.XX.X.Xoooo.X.X.XX.X.    "
"     XXX.X.X.ooOOoXX.X.X.XXX    "
"    ...X.X.X.oooooXX.X.X.X..    "
"    XXXX.XX.X.XoooX.X.XX.XXX    "
"   .....X.X.X.XoooX.X.X.X....   "
"   XXXXXXXXXXXXoooXXXXXXXXXXX   "
"   ......XX++++ooo+++XX......   "
"   XXXXXXX++++++++++++XXXXXXX   "
"   .....XX++++++++++++XX.....   "
"   XXXXX+XXXXXX++XXXXXX+XXXXX   "
"  .....X+XXX@@X++X@@XXX+X.....  "
"  XXXXXXXX+XXXXXXXXXX+XXXXXXXX  "
"  ......X++++++XX++++++X......  "
"  X###XXXXX++++XX++++XXXXXXXXX  "
" ######...X++++XXX+++X........  "
"###XX##XXXX++++XXX+++XXXXXX##X  "
"##....##..XX+++X+++++X.....##.  "
"##XXXX##XXXX+XXXXXX+XXXXXX####  "
"##.....##..X+++XX+++X....###### "
" ###XXXX##XXX++++++XXXXX###XX###"
"  ##....##..XXXXXXXX...###...X##"
"   ##XXXX##XXXX++XXXXX###XXXX ##"
"   ##....##...XXXX...###....    "
"     XXXXX##XXX++XXXX###XXXX    "
"     .....##..XXXX..###....     "
"      XXXXX##XX++XX###XXXXX     "
"      .....##.XXXX###.....      "))

(define fortune (list
"32 32 7 1"
" 	c None"
".	c black"
"X	c wheat"
"o	c tan"
"O	c peru"
"+	c lemon chiffon"
"@	c white"
"                                "
"                                "
"                                "
"                                "
"                                "
"                                "
"           ....                 "
"          .XXXX..               "
"         .ooXXXXX...            "
"       ..ooXXXXXXXXX....        "
"     ..oooXoXXXX.XXXXXXX....    "
"    .ooooXoXXXXXX.oXXXXXXXXX... "
"  ..ooooXoXXXXXXXX.OoXXXXXXXXXX."
" .oooooXoXXXXXXXXXX.OooXXXXXXX+."
".oooooXXXXXXXXXXXXXX.OoooXX++.. "
".ooXoXXXXXXXXXXXXXXXX..Oo+...   "
"..XXXXXXXXXXXXXXXXXXXXX....     "
" ..oXXXXXoXoXXXXXXXXXXXX.       "
"  ..ooXooooXXXXXXXXXXX+++.      "
"   .....oooooXXXXX+++......     "
"     ................OoOoOo.    "
"       ....O.@@.@@.Oooooooo.    "
"           .@.@.@..........     "
"           .@..@.               "
"          .@.@.@.               "
"         .@..@@.                "
"         .@@..@.                "
"          ..@@.                 "
"            ...                 "
"                                "
"                                "
"                                "))

(define bob1 (list
"32 32 10 1"
" 	s background	c None"
".	c #800080008000"
"X	c Red"
"o	c #000080000000"
"O	c Black"
"+	c Navy"
"@	c #800080000000"
"#	c White"
"$	c Cyan"
"%	c #c000c000c000"
"                                "
"                                "
"                                "
"           ... XX ...           "
"               XX               "
"              oOOo              "
"              oOO.              "
"              ooo.              "
"              ooo.              "
" ooooooooooo..oo.o..ooooooooooo "
"ooooo+o@@@@o..oo.o..@@@ooo+ooooo"
"oooo+#+o@@@o..oo.o..@@@oo+#+oooo"
" oo+#X#+o@ooo.o$%o.o@@@o+#X#+oo "
"  oo+#+o@@ooo.o$#o.ooo@@o+#+oo  "
"    o+o@@oooo.o$%o.oooo@oo+o    "
"         oooo.o$#o.ooooo        "
"              o@.@              "
"              oo.@              "
"              oo.o              "
"              +o.+              "
"              oo.o              "
"              oo.o              "
"               oo               "
"               oo               "
"            oo.OO.o@            "
"          o@@o.oo.o@@o          "
"         oo@@oOooOo@ooo         "
"          o@@oOooOoooo          "
"               oo               "
"               oo               "
"                                "
"                                "))

(define caesar (list
"32 32 7 1"
" 	s background	c None"
".	c red"
"X	c firebrick"
"o	c black"
"O	c grey"
"+	c slate grey"
"@	c white"
"                                "
"                                "
"             .X....X..          "
"          X.XXX.X.X.X.X..X      "
"         .X.XXXXXXXXXXXX..X.X   "
"       .X..XXXX.X..X.XXXXX....  "
"      .XXXXX.XX.XX.X..X..XXX.X. "
"     .XXX.XX.X.XX.XX..X.X..XX.X "
"     XXXXX.XXX.XX.XX.X.X..XXXX  "
"    XX....X.XXXXXXX.XX.XXXXXX   "
"    ..XXX..X.XXXXXXXXXXXXXX     "
"   ......XXXXoooooooooooX       "
"   XXXXXXXXooOOOOOOOOOOo        "
"  ..X....XoO++ooooo+++o         "
"  .X..XXXoO+oo+++++oo+o         "
" XXXXX.XXo+o++OOOOOO+o          "
" ..XXXXXo+o+OOOOOO@@O+o         "
" XX.X.XXoo+OO@@OOOO@OOOo        "
" .XXXXX  oOO@@@++OOOooooo       "
" ..XX   oOO@@O+++OOOo  oo       "
" XXX    oOO@OO+oooO+o  oo       "
"        oOOOO++o o+O+o  o       "
"        oOOOO++o  o@Oo          "
"        oOOOOO++o o+O+o         "
"         o++OO++o  oO++o        "
"         o++OOO+o  o+O+o        "
"         o+++OOOo   o++o        "
"        o+++++Oo     ooo        "
"       o@@OOOO+o                "
"      o++++++++o                "
"      ooooooooo                 "
"                                "))

(define xmas1 (list
"32 32 7 1"
" 	s background	c None"
".	c yellow"
"X	c #0000ff000000"
"o	c red"
"O	c #00000000ff00"
"+	c #800000000000"
"@	c #ff000000ff00"
"                                "
"              ..                "
"            ......              "
"            ......              "
"             X..X               "
"            X.X..X              "
"            .X.XX.              "
"           XXXXXXX              "
"           X......X             "
"          ooXXXooXX             "
"          ooXXXXXXXX            "
"          .XXXXXXXXX            "
"         XX.XXooXX.XX           "
"         OOX..oo..XXX           "
"        XOOXXX..XXXooX          "
"        XXXXXXXXXXXooX          "
"       XXXXXXXXXXXXXXXX         "
"       ...XXXXXXXOOX..X         "
"      XXXo....XXXO...XXX        "
"      XXXooXXXoo...XXXXX        "
"      XXXXXXXXooXXXXXXXXX       "
"     X....XXXXXXXXXooXX..       "
"     ooXO......XXXXo....oo      "
"    XooXOOXXXX.......XXXoo      "
"    XXXXXXXXXXOOXXXXXXXXXXX     "
"   XXXXXXXXXXXOOXXXXXXXXXXX     "
"   XOOXXXXooXXXXXXXXXooXXOOX    "
"  XXOOXXXXooXXXXXXXXXooXXOOX    "
"  XXXXXXXXXXXXXXXXXXXXXXXXXX    "
"              +++   . .         "
"      o o     +++  @@.@@@@ O O  "
"   OOOOoOOOO  +++  .......  O   "))

(define umbrela (list
"32 32 9 1"
" 	s background	c None"
".	c black"
"X	c blue"
"o	c #800000008000"
"O	c red"
"+	c yellow"
"@	c #000080000000"
"#	c #800000000000"
"$	c #800080000000"
"                                "
"               ..               "
"               ...              "
"            .........           "
"         ...XX.....oo...        "
"       ..XXX..O..++..ooo..      "
"     ..XXXX.OOO.@.+++.oooo.     "
"     .XXXX.OOOO.@.++++.oooo.    "
"    .XXXX.OOOO.@@@.++++.oooo.   "
"   .XXXXX.OOOO.@@@.++++.ooooo.  "
"   .XXXX.OOOOO.@@@.+++++.oooo.  "
"  .XXXXX.OOOO.@@@@@.++++.ooooo. "
"  .XXXX.OOOOO.@@@@@.+++++.oooo. "
"  .X..X.O...O.@..@@.+...+....o. "
"  ..  ...   ....#....   ...  .. "
"  .    .     . .$. .     .    . "
"               .#.              "
"               .$.              "
"               .#.              "
"               .$.              "
"               .#.              "
"               .$.              "
"               .#.              "
"               .$.              "
"               .#.              "
"        ..     .$.              "
"       .#$.    .#.              "
"       .$#.    .$.              "
"        .$#.  .$.               "
"        .#$#..$#.               "
"         ..$#$#.                "
"           ....                 "))

(define chess3 (list
"32 32 5 1"
" 	s background	c None"
".	c #808080"
"X	c black"
"o	c #c0c0c0"
"O	c white"
"                                "
"           .X.                  "
"           XXX.oo o             "
"           X.XX..oOo            "
"          XXX.XoX.X. o          "
"          XXXX.XOo.X..o         "
"         .XXXXX.X.O.XXOo        "
"         XXXXXXXXX.o.XX.o       "
"        .XXXXXXXXXX.O.XX.o      "
"        XXXXXXXXXoXX.o.X.o      "
"       .XXXXXXXXXXoXXO.XXOo     "
"       XXXXXXXXXXXoX.o.XX.o     "
"      .XXXXXXXXXX.oXX.o.XXo     "
"     .XXXXXXXXXXXoXXXXOoXXOo    "
"     XXXXXXXXXXX..XXX.o.XX.o    "
"     XXXXX.......XXXXXOo.X.o    "
"     .XXX  ..XXXXXXXX.o.XX.     "
"      .X   .XXXXXXXXXXOo.X.o    "
"          XXXXXXXXXXX.o.XX.o    "
"         XXXXXXXXXXX.O.XX.Oo    "
"        .XXXXXXXXXX.X.oX..o     "
"        XXXXXXXXXX.XO.XX.Oo     "
"        X.X.X.X...oO.XX..o      "
"        .X.X.........X.Oo       "
"         .XXXXXXXXXXXX.o        "
"         X.....o...oOo.         "
"         XXXXXXXXXXXXX          "
"       ........o...oOoo.        "
"        XXXXXXXXXXXXXXX         "
"       .X..X.X.o.X.XoOX.        "
"      .XXXXXXXXXXXXXXX.X.       "
"      XXXXXXXXXXXXXXXoXoX       "))

(define compress (list
"32 32 8 1"
" 	s background	c None"
".	c black"
"X	c #D4D4FF"
"o	c #8E8EFF"
"O	c white"
"+	c #6B6BFF"
"@	c #FFD48E"
"#	c #FF8F6B"
"                                "
"                                "
"                                "
"            ...                 "
"           .XXX.                "
"          .XXXXX.               "
"         .XXXXXXX.              "
"        .XXXXoXXXX........      "
"       .XXXXXoXXXoXXXXXXXX.     "
"       .OOOOOoOOOXOOOOOXOX.     "
"       ...XOX+XOXoXOXOoOOo.     "
"       .@@...+OXOoOXOXoOo.      "
"      .@@@@@@.XOXoXOXoOOo.      "
"      .#@@@@@#.XO+OXO+Oo.       "
"       .##@@@#.OXoXOoOOo.       "
"      .@..####.XO+OX+O.....     "
"      .@@@.....OX+X+O.@@@@#.    "
"      .#@@@@@@#.O+O+.@@@@@#.    "
"       .#@@@@@#.X+X+.@@@@@#.    "
"       ..######.O+O+.#####.     "
"      .@@.......X+X+X.....      "
"      .@@@@@@@@#.+O+OXOo.       "
"      .#@@@@@@@#.+XO+OXo.       "
"       .########.+OX+XOXo.      "
"       .........XoXOXoXOo.      "
"      .@@@@@#.OXO+OXO+OXOo.     "
"      .######.XOXoXOXOoOXo.     "
"       ......oOXOoOXOXoXOo.     "
"       .XOoOXoXOXoXOXOXoXo.     "
"      .XOoOXOXOXOXOXOXOXOo.     "
"      .OXOXO.........OXOXo.     "
"      ......         ......     "))

(define xdbx (list
"32 32 4 1"
" 	s None	c None"
".	m black	c black"
"X	m white	c white"
"o	m white	c red"
"........                      .."
" ........      .              .."
"  ........      .      .     .. "
"   ........     .      .    ..  "
"   ........     .      .   ..   "
"    ........   ........   ..    "
"     ..........XX.oooo.....   . "
"      .........XX.ooooooo..   . "
"      ........o..oo..ooo...   . "
"       ........ooo.XX.o..oo...  "
"      ..........oo.XX...ooo.    "
"      ...........oo....o..oo.   "
"     ............ooo..o.XX.o.   "
" .  ...X.o........oo..o.XX.o.   "
"  ....XX.oo.......o..ooo..ooo.  "
"    .....ooo.....o..ooooooooo.  "
"    ............o.............  "
"    .....oooo..o.....oooooooo.  "
"  ....XX.ooo..o.......oo..ooo.  "
" .  ...X.oo..oo.........XX.o.   "
"     ....o...oo.........XX.o.   "
"      ......oooo..........oo.   "
"      .....oo..oo........oo...  "
"       ...oo.XX.oo........o.  . "
"       ..ooo.XX.oo.........   . "
"      .. .ooo..oooo........   . "
"      ..  ..oooooooo........    "
"     ..    ....oooooo........   "
"    ..     .   ..............   "
"   ..      .      .   ........  "
"  ..      .       .    ........ "
" ..              .      ........"))

(define icl8 (list
"32 32 10 1"
" 	s None	c None"
".	c black"
"X	c #009ACD"
"o	c wheat"
"O	c #003298"
"+	c tan"
"@	c #FF3333"
"#	c #CC9966"
"$	c #980065"
"%	c #555555"
"            .                   "
"            .                   "
"           .X.                  "
"    ........X..........         "
"    .oooooo.X.oooooooo..        "
"    .ooooo.OXX.oooooo+.o.       "
"    .ooooo.OXX.oooooo+.oo.      "
"    .ooooo.OXX.oooooo+.ooo.     "
"    .oo.....X......oo+......    "
"    .oo.@@@.X.@@@@.oo+++++++.   "
"    .ooo.@@@.X.@@.oooooooooo.   "
"    .....@@@@..@@....ooooooo.   "
"  ...XXX.@@@@@.@@.OOO...oooo.   "
"..XXXXXX.@@@@@@@@.XXXXXX..oo.   "
"  ..OOOO.@@.@@@@@.XXX...oooo.   "
"    .....@@..@@@@....ooooooo.   "
"    .ooo.@@.O.@@@.oooooooooo.   "
"    .oo.@@@@.O.@@.o............."
"    .oo......O....o.ooooooooooo."
"    .ooooo.XXO.ooo+.ooo.....ooo."
"    .ooooo.XXO.ooo+.oo.#####.oo."
"    .ooooo.XXO.ooo+.o.#X###X#.o."
"    .oooooo.X.oooo+.o.###$###.o."
"    .oooooo.X.oooo+.o.#$###$#.o."
"    .oooooo.X.oooo+.o.##$$$##.o."
"    .ooooooo.ooooo+.oo.#####.oo."
"    .ooooooo.ooooo+.ooo.....ooo."
"    .ooooooooooooo+.ooooooooooo."
"    .ooooooooooooo+............."
"    .ooooooooooooo++++++++++%++ "
"    .ooooooooooooooooooooooo.   "
"    .........................   "))
