# make file for snd in mkLinux with Lesstif

CC = gcc
CFLAGS = -O2 -DLINUX -I/usr/local/include -I/usr/X11R6/include
LIBS = -L/usr/local/lib -lMrm -lXm -L/usr/X11R6/lib -lXpm -lXext -lFS -lSM -lICE -lXt -lX11 -lm `guile-config link`

include makesnd.files

snd: $(SNDLIB_HEADERS) $(SND_HEADERS) $(SND_X_HEADERS) $(SNDLIB_O_FILES) $(SNDLIB_SCM_FILES) $(O_FILES) $(X_O_FILES)
	$(CC) $(SNDLIB_O_FILES) $(SNDLIB_SCM_FILES) $(O_FILES) $(X_O_FILES) -o snd $(LIBS)

include makesnd.back
