# make file for snd in Linux with no user-interface

CC = cc
CFLAGS = -g -DLINUX -DUSE_SND -DUSE_NO_GUI -DHAVE_GUILE `guile-config compile`
LIBS = -lm `guile-config link`

include makesnd.files

snd: $(SNDLIB_HEADERS) $(SND_HEADERS) $(SNDLIB_O_FILES) $(O_FILES) snd-nogui.o
	$(CC) $(SNDLIB_O_FILES) $(O_FILES) snd-nogui.o -o snd $(LIBS)

include makesnd.back
