# make file for snd in Linux at ccrma with Motif 2.1

CC = gcc
CFLAGS = -g -O3 -DLINUX -DCCRMA -DUSR_LIB_OSS=1 -I/usr/ccrma/include
LIBS = -L/usr/ccrma/lib -lguile -L/usr/X11R6/lib -lMrm -lXm -lXp -lXpm -lXext -lXt -lSM -lICE -lFS -lX11 -lm -ldl

include makesnd.files

snd: $(SNDLIB_HEADERS) $(SND_HEADERS) $(SND_X_HEADERS) $(SNDLIB_O_FILES) $(SNDLIB_SCM_FILES) $(O_FILES) $(X_O_FILES)
	$(CC) $(SNDLIB_O_FILES) $(SNDLIB_SCM_FILES) $(O_FILES) $(X_O_FILES) -o snd $(LIBS)

include makesnd.back
