# make file for snd in Linux with Motif 2.1

CC = cc
CFLAGS = -O3 -DLINUX `guile-config compile`
LIBS = -L/usr/X11R6/lib -lXm -lXp -lXpm -lXt -lXext -lX11 -lm `guile-config link`

include makesnd.files

snd: $(SNDLIB_HEADERS) $(SND_HEADERS) $(SND_X_HEADERS) $(SNDLIB_O_FILES) $(O_FILES) $(X_O_FILES)
	$(CC) $(SNDLIB_O_FILES) $(O_FILES) $(X_O_FILES) -o snd $(LIBS)

include makesnd.back
