# make file for snd in Linux at ccrma with Motif 2.1

CC = gcc
CFLAGS = -g -O2 -DLINUX -DCCRMA -DHAVE_ALSA -I/usr/lib/snd/include
LIBS = -L/usr/lib/snd/lib -lguile -L/usr/X11R6/lib -lXm -lXp -lXpm -lXext -lXt -lSM -lICE -lX11 -lasound -lm -ldl

include makesnd.files

snd: $(SNDLIB_HEADERS) $(SND_HEADERS) $(SND_X_HEADERS) $(SNDLIB_O_FILES) $(SNDLIB_SCM_FILES) $(O_FILES) $(X_O_FILES)
	$(CC) $(SNDLIB_O_FILES) $(SNDLIB_SCM_FILES) $(O_FILES) $(X_O_FILES) -o snd $(LIBS)

include makesnd.back
