# Snd make file for Solaris

CC = gcc
CFLAGS = -O2 -DXPM -DSUN -DUSE_SND -DSOLARIS -I/usr/dt/include -I/usr/openwin/include `guile-config compile`
LIBS = -lMrm -lXm -lXpm -lXt -lXext -lX11 -lm `guile-config link`

include makesnd.files

snd: $(SNDLIB_HEADERS) $(SND_HEADERS) $(SND_X_HEADERS) $(SNDLIB_O_FILES) $(O_FILES) $(X_O_FILES)
	$(CC) $(SNDLIB_O_FILES) $(O_FILES) $(X_O_FILES) -o snd $(LIBS)

include makesnd.back

