# Snd make file for DEC Alpha

CC = gcc
CFLAGS = -O2 -DALPHA -DHAVE_EXTENSION_LANGUAGE=0
LIBS = -lMrm -lXm -lXt -lXext -lX11 -lm

include makesnd.files

snd: $(SNDLIB_HEADERS) $(SND_HEADERS) $(SND_X_HEADERS) $(SNDLIB_O_FILES) $(O_FILES) $(X_O_FILES)
	$(CC) $(SNDLIB_O_FILES) $(O_FILES) $(X_O_FILES) -o snd $(LIBS)

include makesnd.back

