;;; these are the old (pre-version 10 sndlib) names

(define next-sound-file mus-next)
(define nist-sound-file mus-nist)
(define aifc-sound-file mus-aifc)
(define ircam-sound-file mus-ircam)
(define raw-sound-file mus-raw)
(define riff-sound-file mus-riff)
(define aiff-sound-file mus-aiff)

(define snd-16-linear mus-bshort)
(define snd-16-linear-little-endian mus-lshort)
(define snd-24-linear mus-b24int)
(define snd-24-linear-little-endian mus-l24int)
(define snd-32-float mus-bfloat)
(define snd-32-float-little-endian mus-lfloat)
(define snd-32-linear mus-bint)
(define snd-32-linear-little-endian mus-lint)
(define snd-64-double mus-bdouble)
(define snd-64-double-little-endian mus-ldouble)
(define snd-8-alaw mus-alaw)
(define snd-8-linear mus-byte)
(define snd-8-mulaw mus-mulaw)
(define snd-8-unsigned mus-ubyte)
(define snd-16-unsigned mus-ubshort)
(define snd-16-unsigned-little-endian mus-ulshort)

(define sndlib-default-device mus-audio-default)
(define sndlib-read-write-device mus-audio-duplex-default)
(define sndlib-line-out-device mus-audio-line-out)
(define sndlib-line-in-device mus-audio-line-in)
(define sndlib-microphone-device mus-audio-microphone)
(define sndlib-speakers-device mus-audio-speakers)
(define sndlib-dac-out-device mus-audio-dac-out)
(define sndlib-adat-in-device mus-audio-adat-in)
(define sndlib-aes-in-device mus-audio-aes-in)
(define sndlib-digital-in-device mus-audio-digital-in)
(define sndlib-digital-out-device mus-audio-digital-out
(define sndlib-adat-out-device mus-audio-adat-out)
(define sndlib-aes-out-device mus-audio-aes-out)
(define sndlib-dac-filter-device mus-audio-dac-filter)
(define sndlib-mixer-device mus-audio-mixer)
(define sndlib-line1-device mus-audio-line1)
(define sndlib-line2-device mus-audio-line2)
(define sndlib-line3-device mus-audio-line3)
(define sndlib-aux-input-device mus-audio-aux-input)
(define sndlib-cd-in-device mus-audio-cd)
(define sndlib-aux-output-device mus-audio-aux-output)
(define sndlib-spdif-in-device mus-audio-spdif-in)
(define sndlib-spdif-out-device mus-audio-spdif-out)

(define sndlib-amp-field mus-audio-amp)
(define sndlib-srate-field mus-audio-srate)
(define sndlib-channel-field mus-audio-channel)
(define sndlib-format-field mus-audio-format)
(define sndlib-device-field mus-audio-port)
(define sndlib-imix-field mus-audio-imix)
(define sndlib-igain-field mus-audio-igain)
(define sndlib-reclev-field mus-audio-reclev)
(define sndlib-pcm-field mus-audio-pcm)
(define sndlib-pcm2-field mus-audio-pcm2)
(define sndlib-ogain-field mus-audio-ogain)
(define sndlib-line-field mus-audio-line)
(define sndlib-synth-field mus-audio-synth)
(define sndlib-bass-field mus-audio-bass)
(define sndlib-treble-field mus-audio-treble)

(define (audio-error . args) (apply mus-audio-error args))
(define (audio-error-name . args) (apply mus-audio-error-name args))
(define (audio-outputs . args) (apply mus-audio-sun-outputs args))
(define (sound-bytes-per-sample . args) (apply mus-data-format-bytes-per-sample args))
(define (report-audio-state . args) (apply mus-audio-report args))
(define (sound-chans . args) (apply mus-sound-chans args))
(define (sound-comment . args) (apply mus-sound-comment args))
(define (sound-data-format . args) (apply mus-sound-data-format args))
(define (sound-data-location . args) (apply mus-sound-data-location args))
(define (sound-datum-size . args) (apply mus-sound-datum-size args))
(define (sound-format-name . args) (apply mus-data-format-name args))
(define (sound-header-type . args) (apply mus-sound-header-type args))
(define (sound-length . args) (apply mus-sound-length args))
(define (sound-samples . args) (apply mus-sound-samples args))
(define (sound-frames . args) (apply mus-sound-frames args))
(define (sound-srate . args) (apply mus-sound-srate args))
(define (sound-type-name . args) (apply mus-header-type-name args))
(define (sound-type-specifier . args) (apply mus-sound-type-specifier args))
(define (sound-duration . args) (apply mus-sound-duration args))
(define (sound-max-amp . args) (apply mus-sound-max-amp args))
(define (sound-loop-info . args) (apply mus-sound-loop-info args))
(define (open-sound-input . args) (apply mus-sound-open-input args))
(define (open-sound-output . args) (apply mus-sound-open-output args))
(define (reopen-sound-output . args) (apply mus-sound-reopen-output args))
(define (close-sound-input . args) (apply mus-sound-close-input args))
(define (close-sound-output . args) (apply mus-sound-close-output args))
(define (read-sound . args) (apply mus-sound-read args))
(define (write-sound . args) (apply mus-sound-write args))
(define (seek-sound . args) (apply mus-sound-seek args))
(define (seek-sound-frame . args) (apply mus-sound-seek-frame args))
(define (open-audio-output . args) (apply mus-audio-open-output args))
(define (open-audio-input . args) (apply mus-audio-open-input args))
(define (write-audio . args) (apply mus-audio-write args))
(define (close-audio . args) (apply mus-audio-close args))
(define (read-audio . args) (apply mus-audio-read args))
(define (read-audio-state . args) (apply mus-audio-mixer-read args))
(define (write-audio-state . args) (apply mus-audio-mixer-write args))
(define (audio-systems . args) (apply mus-audio-systems args))
(define (save-audio-state . args) (apply mus-audio-save args))
(define (restore-audio-state . args) (apply mus-audio-restore args))
(define (mus-set-data-clipped . args) (apply mus-file-set-data-clipped args))
(define (mus-prescaler . args) (apply mus-file-prescaler args))
(define (mus-set-prescaler . args) (apply mus-file-set-prescaler args))
