    _OP_DEF(0,                                0,  0,       0,                               OP_TOP_LEVEL        )
    _OP_DEF(0,                                0,  0,       0,                               OP_T1LVL            )
    _OP_DEF(0,                                0,  0,       0,                               OP_READ_INTERNAL    )
    _OP_DEF(0,                                0,  0,       0,                               OP_VALUEPRINT       )
    _OP_DEF(0,                                0,  0,       0,                               OP_EVAL             )
    _OP_DEF(0,                                0,  0,       0,                               OP_REAL_EVAL        )
    _OP_DEF(0,                                0,  0,       0,                               OP_E0ARGS           )
    _OP_DEF(0,                                0,  0,       0,                               OP_E1ARGS           )
    _OP_DEF(0,                                0,  0,       0,                               OP_APPLY            )
    _OP_DEF(0,                                0,  0,       0,                               OP_REAL_APPLY       )
    _OP_DEF(0,                                0,  0,       0,                               OP_DOMACRO          )
    _OP_DEF(0,                                0,  0,       0,                               OP_LAMBDA           )
    _OP_DEF(0,                                0,  0,       0,                               OP_QUOTE            )
    _OP_DEF(0,                                0,  0,       0,                               OP_DEF0             )
    _OP_DEF(0,                                0,  0,       0,                               OP_DEF1             )
    _OP_DEF(0,                                0,  0,       0,                               OP_BEGIN            )
    _OP_DEF(0,                                0,  0,       0,                               OP_IF0              )
    _OP_DEF(0,                                0,  0,       0,                               OP_IF1              )
    _OP_DEF(0,                                0,  0,       0,                               OP_SET0             )
    _OP_DEF(0,                                0,  0,       0,                               OP_SET1             )
    _OP_DEF(0,                                0,  0,       0,                               OP_SET2             )
    _OP_DEF(0,                                0,  0,       0,                               OP_LET0             )
    _OP_DEF(0,                                0,  0,       0,                               OP_LET1             )
    _OP_DEF(0,                                0,  0,       0,                               OP_LET2             )
    _OP_DEF(0,                                0,  0,       0,                               OP_LET0AST          )
    _OP_DEF(0,                                0,  0,       0,                               OP_LET1AST          )
    _OP_DEF(0,                                0,  0,       0,                               OP_LET2AST          )
    _OP_DEF(0,                                0,  0,       0,                               OP_LET0REC          )
    _OP_DEF(0,                                0,  0,       0,                               OP_LET1REC          )
    _OP_DEF(0,                                0,  0,       0,                               OP_LET2REC          )
    _OP_DEF(0,                                0,  0,       0,                               OP_COND0            )
    _OP_DEF(0,                                0,  0,       0,                               OP_COND1            )
    _OP_DEF(0,                                0,  0,       0,                               OP_DELAY            )
    _OP_DEF(0,                                0,  0,       0,                               OP_AND0             )
    _OP_DEF(0,                                0,  0,       0,                               OP_AND1             )
    _OP_DEF(0,                                0,  0,       0,                               OP_OR0              )
    _OP_DEF(0,                                0,  0,       0,                               OP_OR1              )
    _OP_DEF(0,                                0,  0,       0,                               OP_C0STREAM         )
    _OP_DEF(0,                                0,  0,       0,                               OP_C1STREAM         )
    _OP_DEF(0,                                0,  0,       0,                               OP_DEFMACRO           )
    _OP_DEF(0,                                0,  0,       0,                               OP_MACRO0           )
    _OP_DEF(0,                                0,  0,       0,                               OP_MACRO1           )
    _OP_DEF(0,                                0,  0,       0,                               OP_CASE0            )
    _OP_DEF(0,                                0,  0,       0,                               OP_CASE1            )
    _OP_DEF(0,                                0,  0,       0,                               OP_CASE2            )
    _OP_DEF(0,                                0,  0,       0,                               OP_READ_EXPRESSION)
    _OP_DEF(0,                                0,  0,       0,                               OP_RDLIST           )
    _OP_DEF(0,                                0,  0,       0,                               OP_RDDOT            )
    _OP_DEF(0,                                0,  0,       0,                               OP_RDQUOTE          )
    _OP_DEF(0,                                0,  0,       0,                               OP_RDQQUOTE         )
    _OP_DEF(0,                                0,  0,       0,                               OP_RDQQUOTEVEC      )
    _OP_DEF(0,                                0,  0,       0,                               OP_RDUNQUOTE        )
    _OP_DEF(0,                                0,  0,       0,                               OP_RDUQTSP          )
    _OP_DEF(0,                                0,  0,       0,                               OP_RDVEC            )
    _OP_DEF(0,                                0,  0,       0,                               OP_P0LIST           )
    _OP_DEF(0,                                0,  0,       0,                               OP_P1LIST           )
    _OP_DEF(0,                                0,  0,       0,                               OP_PVECFROM         )
    _OP_DEF(0,                                0,  0,       0,                               OP_ERR1             )
    _OP_DEF(0,                                0,  0,       0,                               OP_ERROR             )
    _OP_DEF(0,                                0,  0,       0,                               OP_SAVE_FORCED      )
    _OP_DEF(0,                                0,  0,       0,                               OP_READ_RETURN_EXPRESSION )
    _OP_DEF(0,                                0,  0,       0,                               OP_READ_POP_AND_RETURN_EXPRESSION )
    _OP_DEF(0,                                0,  0,       0,                               OP_LOAD_RETURN_IF_EOF)
    _OP_DEF(0,                                0,  0,       0,                               OP_LOAD_CLOSE_AND_POP_IF_EOF)
    _OP_DEF(0,                                0,  0,       0,                               OP_EVAL_STRING)
    _OP_DEF(0,                                0,  0,       0,                               OP_EVAL_STRING_DONE)
    /* named args start here (this matters in eval) */
    _OP_DEF("defined?",                       1,  2,       TST_SYMBOL TST_PAIR,           OP_DEFP             )
    _OP_DEF("make-closure",                   1,  2,       TST_PAIR TST_PAIR,             OP_MKCLOSURE        )
    _OP_DEF("eval",                           1,  2,       TST_ANY TST_PAIR,              OP_PEVAL            )
    _OP_DEF("apply",                          1,  INF_ARG, TST_NONE,                        OP_PAPPLY           )
    _OP_DEF("call-with-current-continuation", 1,  1,       TST_NONE,                        OP_CONTINUATION     )
    _OP_DEF("call-with-exit",                 1,  1,       TST_NONE,                        OP_GOTO     )

    _OP_DEF("car",                            1,  1,       TST_PAIR,                        OP_CAR              )
    _OP_DEF("cdr",                            1,  1,       TST_PAIR,                        OP_CDR              )
    _OP_DEF("cons",                           2,  2,       TST_NONE,                        OP_CONS             )
    _OP_DEF("set-car!",                       2,  2,       TST_PAIR TST_ANY,                OP_SETCAR           )
    _OP_DEF("set-cdr!",                       2,  2,       TST_PAIR TST_ANY,                OP_SETCDR           )
    _OP_DEF("char->integer",                  1,  1,       TST_CHAR,                        OP_CHAR2INT         )
    _OP_DEF("integer->char",                  1,  1,       TST_NATURAL,                     OP_INT2CHAR         )
    _OP_DEF("char-upcase",                    1,  1,       TST_CHAR,                        OP_CHARUPCASE       )
    _OP_DEF("char-downcase",                  1,  1,       TST_CHAR,                        OP_CHARDNCASE       )
    _OP_DEF("make-string",                    1,  2,       TST_NATURAL TST_CHAR,            OP_MKSTRING         )
    _OP_DEF("string-length",                  1,  1,       TST_STRING,                      OP_STRLEN           )
    _OP_DEF("string-ref",                     2,  2,       TST_STRING TST_NATURAL,          OP_STRREF           )
    _OP_DEF("string-set!",                    3,  3,       TST_STRING TST_NATURAL TST_CHAR, OP_STRSET           )
    _OP_DEF("string-append",                  0,  INF_ARG, TST_STRING,                      OP_STRAPPEND        )
    _OP_DEF("substring",                      2,  3,       TST_STRING TST_NATURAL,          OP_SUBSTR           )
    _OP_DEF("vector",                         0,  INF_ARG, TST_NONE,                        OP_VECTOR           )
    _OP_DEF("make-vector",                    1,  2,       TST_NATURAL TST_ANY,             OP_MKVECTOR         )
    _OP_DEF("vector-length",                  1,  1,       TST_VECTOR,                      OP_VECLEN           )
    _OP_DEF("vector-ref",                     2,  2,       TST_VECTOR TST_NATURAL,          OP_VECREF           )
    _OP_DEF("vector-set!",                    3,  3,       TST_VECTOR TST_NATURAL TST_ANY,  OP_VECSET           )
    _OP_DEF("not",                            1,  1,       TST_NONE,                        OP_NOT              )
    _OP_DEF("boolean?",                       1,  1,       TST_NONE,                        OP_BOOLP            )
    _OP_DEF("null?",                          1,  1,       TST_NONE,                        OP_NULLP            )
    _OP_DEF("string?",                        1,  1,       TST_ANY,                         OP_STRINGP          )
    _OP_DEF("char?",                          1,  1,       TST_ANY,                         OP_CHARP            )
    _OP_DEF("char-alphabetic?",               1,  1,       TST_CHAR,                        OP_CHARAP           )
    _OP_DEF("char-numeric?",                  1,  1,       TST_CHAR,                        OP_CHARNP           )
    _OP_DEF("char-whitespace?",               1,  1,       TST_CHAR,                        OP_CHARWP           )
    _OP_DEF("char-upper-case?",               1,  1,       TST_CHAR,                        OP_CHARUP           )
    _OP_DEF("char-lower-case?",               1,  1,       TST_CHAR,                        OP_CHARLP           )
    _OP_DEF("procedure?",                     1,  1,       TST_ANY,                         OP_PROCP            )
    _OP_DEF("pair?",                          1,  1,       TST_ANY,                         OP_PAIRP            )
    _OP_DEF("list?",                          1,  1,       TST_ANY,                         OP_LISTP            )
    _OP_DEF("vector?",                        1,  1,       TST_ANY,                         OP_VECTORP          )
    _OP_DEF("eq?",                            2,  2,       TST_ANY,                         OP_EQ               )
    _OP_DEF("eqv?",                           2,  2,       TST_ANY,                         OP_EQV              )
    _OP_DEF("equal?",                         2,  2,       TST_ANY,                         OP_EQUAL            )
    _OP_DEF("force",                          1,  1,       TST_ANY,                         OP_FORCE            )
    _OP_DEF("list*",                          1,  INF_ARG, TST_NONE,                        OP_LIST_STAR        )
    _OP_DEF("append",                         0,  INF_ARG, TST_NONE,                        OP_APPEND           )
    _OP_DEF("quit",                           0,  1,       TST_NUMBER,                      OP_QUIT             )
    _OP_DEF("global-environment",        0,  0,       0,                               OP_GLOBAL_ENVIRONMENT          )
    _OP_DEF("current-environment",            0,  0,       0,                               OP_CURRENT_ENVIRONMENT         )
    _OP_DEF("length",                         1,  1,       TST_LIST,                        OP_LIST_LENGTH      )
    _OP_DEF("object->string",                 1,  1,       TST_NONE,                        OP_OBJECT_TO_STRING )
    _OP_DEF("assq",                           2,  2,       TST_NONE,                        OP_ASSQ             )
    _OP_DEF("closure?",                       1,  1,       TST_NONE,                        OP_CLOSUREP         )
    _OP_DEF("macro?",                         1,  1,       TST_NONE,                        OP_MACROP           )
#undef _OP_DEF
