#ifndef STRS_H_LOADED
#define STRS_H_LOADED

/* strings used in Snd */
#ifndef STR_OR
  #define STR_OR "or"
  /* British spelling enthusiasts can -DSTR_OR=\"our\" */
#endif

#define STRFTIME_FORMAT                  "%a %d-%b-%Y %H:%M %Z"

#define STR_decimal                      '.'
/* defines the decimal point character used where I'm making float representations by hand */

/* '_p' below means it's a prompt */

#define STR_Adat_In                      "Adat In"
#define STR_Adat_Out                     "Adat Out"
#define STR_Aes_In                       "Aes In"
#define STR_Aes_Out                      "Aes Out"
#define STR_Analog_In                    "Analog In"
#define STR_Apply		     	 "Apply"
#define STR_Autoload_Recording           "Autoload Recording"
#define STR_Back                         "Back"
#define STR_Big_Trouble                  "Yow!"
#define STR_Bogus_header_found_for	 "Bogus header found for %s"
#define STR_Cancel			 "Cancel"
#define STR_Channel_style                "Channel style"
#define STR_Clear                        "Clear"
#define STR_Click_for_help		 "Click for help"
#define STR_CLM                          "CLM"
#define STR_Close			 "Close"
#define STR_Color                        "Col" STR_OR
#define STR_Color_Editor                 "Col" STR_OR " Editor"
#define STR_Contrast			 "Contrast"
#define STR_Customization		 "Customization"
#define STR_Default		 	 "Default"
#define STR_Delete			 "Delete"
#define STR_Delete_Selection		 "Delete Selection"
#define STR_Digital_In                   "Digital In"
#define STR_Digital_Out                  "Digital Out"
#define STR_Disk_and_Memory_Usage        "Disk and Memory Usage"
#define STR_Dismiss		         "Dismiss"
#define STR_Done			 "Done"
#define STR_Edit			 "Edit"
#define STR_Edit_Envelope                "Edit Envelope"
#define STR_Edit_Header                  "Edit Header"
#define STR_Edit_header_of               "Edit header of %s"
#define STR_Envelope			 "Envelope"
#define STR_Error			 "Error"
#define STR_Error_History		 "Error History"
#define STR_Exit			 "Exit"
#define STR_Expand			 "Expand"
#define STR_FFT			         "FFT"
#define STR_File			 "File"
#define STR_File_Browser                 "File Browser"
#define STR_Files			 "Files"
#define STR_Find			 "Find"
#define STR_Focus_style                  "Zoom focus"
#define STR_Format			 "Format"
#define STR_Formats			 "Formats"
#define STR_Forward                      "Forward"
#define STR_Graph_style                  "Graph style"
#define STR_Help			 "Help"
#define STR_Hide_consoles                "Hide consoles"
#define STR_Hide_controls	 	 "Hide controls"
#define STR_Hide_listener	         "Hide listener"
#define STR_Hide_marks			 "Hide marks"
#define STR_Hide_Y0			 "Hide Y=0"
#define STR_Ignore_stats                 "Ignore stats"
#define STR_Info			 "Info"
#define STR_Input                        "Input"
#define STR_Insert_Selection		 "Insert Selection"
#define STR_Line_In                      "Line In"
#define STR_Line_Out                     "Line Out"
#define STR_Marks			 "Marks"
#define STR_Microphone                   "Microphone"
#define STR_Mix		                 "Mix"
#define STR_Mixing                       "Mixing"
#define STR_Mix_Selection		 "Mix Selection"
#define STR_New				 "New"
#define STR_News			 "News"
#define STR_Next			 "Next"
#define STR_No                           "No"
#define STR_No_Header_on_File		 "No Header on File"
#define STR_No_header_found_for		 "No header found for %s"
#define STR_Normalize			 "Normalize"
#define STR_Ok				 "Ok"
#define STR_Open			 "Open"
#define STR_Open_listener		 "Open listener"
#define STR_Options			 "Options"
#define STR_Orientation                  "Orientation"
#define STR_Output                       "Output"
#define STR_Overview			 "Overview"
#define STR_Play			 "Play"
#define STR_Play_selection		 "Play Selection"
#define STR_Print			 "Print"
#define STR_Previous			 "Previous"
#define STR_Raw_Data		 	 "Raw Data"
#define STR_Record			 "Record"
#define STR_Recording			 "Recording"
#define STR_Redo			 "Redo"
#define STR_Region_Browser		 "Region Browser"
#define STR_Regions			 "Regions"
#define STR_Remember			 "Remember"
#define STR_Reset                        "Reset"
#define STR_Restart		         "Restart"
#define STR_Restore		         "Restore"
#define STR_Reverb			 "Reverb"
#define STR_Revert			 "Revert"
#define STR_Save			 "Save"
#define STR_Save_as			 "Save as"
#define STR_Save_Audio_Settings		 "Save Audio Settings"
#define STR_Save_options		 "Save options"
#define STR_Save_selection     	         "Save Selection"
#define STR_Save_state     	         "Save state"
#define STR_Select			 "Select"
#define STR_Select_all			 "Select all"
#define STR_Show_consoles                "Show consoles"
#define STR_Show_controls		 "Show controls"
#define STR_Show_listener	         "Show listener"
#define STR_Show_marks			 "Show marks"
#define STR_Show_stats                   "Show stats"
#define STR_Show_Y0			 "Show Y=0"
#define STR_Silent_cursor		 "Silent cursor"
#define STR_Sound_Files_Only		 "sound files only"
#define STR_Speakers                     "Speakers"
#define STR_Spectrogram_Orientation	 "Spectrogram Orientation"
#define STR_Speed			 "Speed"
#define STR_Speed_style                  "Speed style"
#define STR_Stop                         "Stop"
#define STR_Sync			 "Sync"
#define STR_There_is_already_a_mark_at_sample "There is already a mark at sample %d"
#define STR_Transform_Options            "Transform Options"
#define STR_Triggered_Record		 "Triggered Record"
#define STR_Undo		         "Undo"
#define STR_Undo_and_Apply		 "Undo&Apply"
#define STR_Undo_and_redo		 "Undo and redo"
#define STR_Update                       "Update"
#define STR_Verbose_cursor		 "Verbose cursor"
#define STR_View			 "View"
#define STR_X_axis_units                 "X axis units"
#define STR_Yes                          "Yes"
#define STR_amp			         "amp"
#define STR_amp_p			 "amp:"
#define STR_amp_env_p			 "amp env:"
#define STR_amp_m		 	 "   amp:   "
#define STR_at                           "at"
/* 'at' used in the phrase 'y = %f at %d' -- reported results from the Find command */
#define STR_apply_flushed		 "apply flushed!"
#define STR_cant_access                  "can't access %s! temp dir is still %s."
#define STR_cant_create                  "can't create %s: %s"
#define STR_cant_find			 "can't find %s"
#define STR_cant_find_file		 "can't find file"
#define STR_cant_find_font               "can't find font %s"
#define STR_cant_open			 "can't open %s"
#define STR_cant_open_file		 "can't open file"
#define STR_cant_play			 "can't play"
#define STR_cant_read_header		 "can't read header"
#define STR_cant_read_his_header	 "can't read %s's header"
#define STR_cant_record_no_inputs        "can't record: no inputs enabled"
#define STR_cant_record_no_output_file   "can't record: no output file name supplied"
#define STR_cant_record_screwed_up_chans "can't record: you screwed up the output channel number!"
#define STR_cant_save_as                 "can't save as %s (%s is write-protected)"
#define STR_cant_translate               "can't translate %s"
#define STR_cant_write			 "can't write %s"
#define STR_cant_write_p		 "can't write %s: %s"
#define STR_cant_write_data		 "can't write data"
#define STR_cant_write_header		 "can't write header"
#define STR_cant_write_translator_file   "can't write translator temp file: %s or %s!"
#define STR_cant_write_type_with_format  "can't write %s %s file with %s data"
#define STR_changed_on_disk_p            "%s changed on disk! Save anyway?"
#define STR_channel_id                   "chn"
#define STR_chan_cursor_at_sample	 "chan %d, cursor at %s (sample %d) = %s"
#define STR_chans                        "chans: %d"
#define STR_chans_p			 "chans:"
#define STR_clip			 "clip"
#define STR_combined                     "combined"
#define STR_comment_p                    "comment:"
#define STR_contrast			 "contrast:"
#define STR_create_new_sound_p           "create new sound: %s"
#define STR_current_files                "current files"
#define STR_current_selection            "current selection"
#define STR_cursor_at_sample		 "cursor at %s (sample %d) = %s"
#define STR_cursor_at_sample_p		 "cursor at %s (sample %d): %s"
#define STR_cutoff                       "data cutoff"
#define STR_dark                         "dark"
#define STR_data                         "data"
#define STR_data_format_p		 "data format:"
#define STR_data_location_p		 "data location:"
#define STR_date                         "date"
#define STR_dB                           "dB"
#define STR_defining_kbd_macro		 "defining kbd macro..."
#define STR_defining_region		 "defining region..."
#define STR_direct_to_printer            "direct to printer"
#define STR_display                      "display"
#define STR_display_info                 "srate: %d\nchans: %d\nlength: %.3f (%d %s)\ntype: %s\nformat: %s\nwritten: %s\ncomment: %s\n"
#define STR_dots                         "dots"
#define STR_dots_and_lines               "dots and lines"
#define STR_duration_p                   "duration:"
#define STR_edit                         "edit"
#define STR_edit_env                     "edit env"
#define STR_entry			 "entry"
#define STR_env_p			 "env:"
#define STR_envelope_editor              "envelope editor"
#define STR_envs_p			 "envs:"
#define STR_eps_file_p			 "eps file:"
#define STR_error                        "error"
#define STR_eval_p			 "eval:"
#define STR_exists_overwrite             "%s exists. Overwrite?"
#define STR_exp			         "exp"
#define STR_exp_base		         "exp base:"
#define STR_expand			 "expand:"
#define STR_f			 	 "f"
/* this 'f' => fft */
#define STR_file_has_changed             "%s has changed since we last read it!"
#define STR_file_p			 "file:"
#define STR_filled			 "filled"
#define STR_filter			 "filter:"
#define STR_find		         "find"
#define STR_find_p			 "find:"
#define STR_find_s			 "find: %s"
#define STR_float                        "float"
#define STR_flt			         "flt"
#define STR_flt_env_p			 "flt env:"
#define STR_focus_active                 "cursor or selection"
#define STR_focus_left                   "window left edge"
#define STR_focus_middle                 "window midpoint"
#define STR_focus_right                  "window right edge"
#define STR_frequency			 "frequency"
#define STR_frequency_reversed           "ycneuqerf"
#define STR_global_search		 "global search"
#define STR_has_unsaved_edits            "%s has unsaved edits.\nClobber them and overwrite %s?"
#define STR_going_on                     "ok -- here we go..."
#define STR_header                       "header"
#define STR_hop                          "hop"
#define STR_insert_file_p		 "insert file:"
#define STR_invert                       "invert"
#define STR_is_a_directory               "%s is a directory"
#define STR_is_write_protected           "%s is write-protected"
#define STR_len				 "len:"
#define STR_length                       "length: %.3f"
#define STR_length_p                     "length:"
/* 'len' => reverb length in the controls panel */
#define STR_light                        "light"
#define STR_linear                       "linear"
#define STR_lines                        "lines"
#define STR_load_p			 "load:"
#define STR_location_p                   "location:"
#define STR_log_freq			 "log freq"
#define STR_lollipops                    "lollipops"
/* using lollipop rather than the suggested popsicle because 
 *   popsicle is a (capitalized) trade-name in the USA and I want lowercase,
 *   lollipop is about 200 years older as an English word (1724 vs 1923),
 *   and I think lollipop is more accurate -- in my experience lollipops have
 *     circular candies whereas popsicles have a sort of squared-off bottom.
 */
#define STR_macro_definition_already_in_progress "macro definition already in progress"
#define STR_macro_name_p		 "macro name:"
#define STR_mark_p			 "mark:"
#define STR_maxamp                       "maxamp: %.3f"
#define STR_maxamp_p                     "maxamp:"
#define STR_mix_file_p			 "mix file:"
#define STR_mix_in_p			 "mix in:"
#define STR_name                         "name"
#define STR_no_color_use_white           "can't get %s -- will use white\n"
#define STR_no_color_use_black           "can't get %s -- will use black\n"
#define STR_no_current_selection         "no current selection"
#define STR_no_data                      "(no data)"
#define STR_no_error			 "no error"
#define STR_no_longer_exists             "%s no longer exists!"
#define STR_no_room                      "only %d bytes left on disk, can't write %d"
#define STR_no_room_but_we_try           "only %d bytes left on disk, changing to 16-bit temp output"
#define STR_no_room_go_on_p              "only %d bytes left on disk; continue?"
#define STR_normal_fft		         "normal fft"
#define STR_normalize		         "normalize"
#define STR_not_found			 "not found"
#define STR_not_saved_no_name_given      "not saved (no name given)"
#define STR_open_p                       "open:"
#define STR_output_interrupted           "output interrupted"
#define STR_peaks			 "peaks"
#define STR_percent_of_spectrum          "% of spectrum"
#define STR_percentage                   "percentage"
#define STR_placed_at_sample		 "%s placed at sample %d"
#define STR_play			 "play"
#define STR_previous_files               "previous files"
#define STR_print                        "print"
#define STR_print_env                    "print env"
#define STR_print_f                      "print %s"
#define STR_printing                     "printing %s"
#define STR_ratio                        "ratio"
#define STR_raw_data                     "raw-data"
#define STR_read_only			 "read-only"
#define STR_redo                         "redo"
#define STR_regions                      "regions"
#define STR_reverb			 "reverb:"
#define STR_revert			 "revert"
#define STR_samples			 "samples"
#define STR_save			 "save"
#define STR_save_as_p			 "save as:"
#define STR_save_as_temp                 "save as temp: %s: %s (%s)"
#define STR_saved_as_p                   "%s saved as %s"
#define STR_saving			 "saving %s"
#define STR_search_in_progress           "search in progress"
#define STR_seconds			 "seconds"
#define STR_selection                    "selection"
#define STR_semitone                     "semitones"
#define STR_separate                     "separate"
#define STR_size			 "size"
#define STR_sonogram			 "sonogram"
#define STR_sort                         "sort"
#define STR_spectrogram			 "spectrogram"
#define STR_speed			 "speed:"
#define STR_speed_m		 	 "   speed:  "
#define STR_srate			 "srate: %d"
#define STR_srate_p			 "srate:"
#define STR_src                          "src"
#define STR_src_env_p                    "src env:"
#define STR_superimposed                 "superimposed"
#define STR_sync			 "sync"
#define STR_temp_dir_p			 "temp dir:"
#define STR_time			 "time"
#define STR_time_reversed		 "emit"
#define STR_trigger_p                    "trigger:"
#define STR_type			 "type"
#define STR_undo                         "undo"
#define STR_unite                        "unite"
#define STR_unknown		         "unknown"
#define STR_unlist                       "unlist"
#define STR_unsupported_data_format	 "unsupported data format"
#define STR_unsupported_header_type	 "unsupported header type"
#define STR_updated                      "updated %s"
#define STR_view_envs                    "view envs"
#define STR_w				 "w"
/* 'w' => wave (time domain) */
#define STR_wave		         "wave"
#define STR_wavelet                      "wavelet"
#define STR_were_getting_short_on_disk_space "disk nearly full: used %d Kbytes leaving %d"
#define STR_window		         "window"
#define STR_write_failed                 "write failed: %s"
#define STR_write_failed_temp_saved      "write failed: %s, edits saved in: %s"
#define STR_wrote                        "wrote %s"
#define STR_x_angle                      "x angle"
#define STR_x_scale                      "x scale"
#define STR_y_angle                      "y angle"
#define STR_y_scale                      "y scale"
#define STR_z_angle                      "z angle"
#define STR_z_scale                      "z scale"




#define S_abort                         "abort"
#define S_abortQ                        "abort?"
#define S_activate_listener             "activate-listener"
#define S_add_mark                      "add-mark"
#define S_add_sound_file_extension      "add-sound-file-extension"
#define S_add_to_main_menu              "add-to-main-menu"
#define S_add_to_menu                   "add-to-menu"
#define S_add_transform                 "add-transform"
#define S_after_graph_hook              "after-graph-hook"
#define S_after_open_hook               "after-open-hook"
#define S_amp                           "amp"
#define S_amplitude_env                 "amplitude-env"
#define S_append_to_minibuffer          "append-to-minibuffer"
#define S_as_one_edit                   "as-one-edit"
#define S_ask_before_overwrite          "ask-before-overwrite"
#define S_audio_output_device           "audio-output-device"
#define S_audio_state_file              "audio-state-file"
#define S_auto_resize                   "auto-resize"
#define S_auto_update                   "auto-update"
#define S_autocorrelate                 "autocorrelate"
#define S_autocorrelation               "autocorrelation"
#define S_axis_label_font               "axis-label-font"
#define S_axis_numbers_font             "axis-numbers-font"
#define S_backward_graph                "backward-graph"
#define S_backward_mark                 "backward-mark"
#define S_backward_mix                  "backward-mix"
#define S_backward_sample               "backward-sample"
#define S_basic_color                   "basic-col" STR_OR
#define S_bind_key                      "bind-key"  
#define S_bold_button_font              "bold-button-font"
#define S_bomb                          "bomb"
#define S_button_font                   "button-font"
#define S_call_apply                    "call-apply"
#define S_cepstrum                      "cepstrum"
#define S_change_menu_label             "change-menu-label"
#define S_change_samples_with_origin    "change-samples-with-origin"
#define S_channel_style                 "channel-style"
#define S_channels                      "channels"
#define S_channels_combined             "channels-combined"
#define S_channels_separate             "channels-separate"
#define S_channels_superimposed         "channels-superimposed"
#define S_chans                         "chans"
#define S_chebyshev_transform           "chebyshev-transform"
#define S_clear_audio_inputs            "clear-audio-inputs"
#define S_close_hook                    "close-hook"
#define S_close_sound                   "close-sound"
#define S_close_sound_file              "close-sound-file"
#define S_color_cutoff                  "col" STR_OR "-cutoff"
#define S_color_dialog                  "col" STR_OR "-dialog"
#define S_color_inverted                "col" STR_OR "-inverted"
#define S_color_scale                   "col" STR_OR "-scale"
#define S_color2list                    "col" STR_OR "->list"
#define S_colormap                      "col" STR_OR "map"
#define S_colorQ                        "col" STR_OR "?"
#define S_comment                       "comment"
#define S_contrast                      "contrast"
#define S_contrast_amp                  "contrast-amp"
#define S_contrast_func                 "contrast-func"
#define S_contrasting                   "contrasting"
#define S_convolve_arrays               "convolve-arrays"
#define S_convolve_selection_with       "convolve-selection-with"
#define S_convolve_with                 "convolve-with"
#define S_corruption_time               "corruption-time"
#define S_count_matches                 "count-matches"
#define S_cursor                        "cursor"
#define S_cursor_claim_selection        "cursor-claim-selection"
#define S_cursor_color                  "cursor-col" STR_OR
#define S_cursor_cross                  "cursor-cross"
#define S_cursor_follows_play           "cursor-follows-play"
#define S_cursor_in_middle              "cursor-in-middle"
#define S_cursor_in_view                "cursor-in-view"
#define S_cursor_line                   "cursor-line"
#define S_cursor_no_action              "cursor-no-action"
#define S_cursor_on_left                "cursor-on-left"
#define S_cursor_on_right               "cursor-on-right"
#define S_cursor_style                  "cursor-style"
#define S_cursor_update_display         "cursor-update-display"
#define S_cut                           "cut"
#define S_dac_folding                   "dac-folding"
#define S_dac_size                      "dac-size"
#define S_data_clipped                  "data-clipped"
#define S_data_color                    "data-col" STR_OR
#define S_data_format                   "data-format"
#define S_data_location                 "data-location"
#define S_default_output_chans          "default-output-chans"
#define S_default_output_format         "default-output-format"
#define S_default_output_srate          "default-output-srate"
#define S_default_output_type           "default-output-type"
#define S_define_envelope               "define-envelope"
#define S_delete_mark                   "delete-mark"
#define S_delete_marks                  "delete-marks"
#define S_delete_region                 "delete-region"
#define S_delete_sample                 "delete-sample"
#define S_delete_samples                "delete-samples"
#define S_delete_samples_with_origin    "delete-samples-with-origin"
#define S_describe_audio                "describe-audio"
#define S_dismiss_all_dialogs           "dismiss-all-dialogs"
#define S_dot_size                      "dot-size"
#define S_during_open_hook              "during-open-hook"
#define S_edit_header_dialog            "edit-header-dialog"
#define S_edit_fragment                 "edit-fragment"
#define S_edit_hook                     "edit-hook"
#define S_edit_position                 "edit-position"
#define S_edits                         "edits"
#define S_env_selection                 "env-selection"
#define S_env_sound                     "env-sound"
#define S_enved_base                    "enved-base"
#define S_enved_clipping                "enved-clipping"
#define S_enved_dBing                   "enved-dBing"
#define S_enved_dialog                  "enved-dialog"
#define S_enved_exping                  "enved-exping"
#define S_enved_power                   "enved-power"
#define S_enved_target                  "enved-target"
#define S_enved_waveform_color          "enved-waveform-col" STR_OR
#define S_enved_waving                  "enved-waving"
#define S_eps_file                      "eps-file"
#define S_erase_zeros                   "erase-zeros"
#define S_exit                          "exit"
#define S_exit_hook                     "exit-hook"
#define S_expand                        "expand"
#define S_expand_funcs                  "expand-funcs"
#define S_expand_hop                    "expand-hop"
#define S_expand_length                 "expand-length"
#define S_expand_ramp                   "expand-ramp"
#define S_expanding                     "expanding"
#define S_fft                           "fft"
#define S_fft_beta                      "fft-beta"
#define S_fft_hook                      "fft-hook"
#define S_fft_log_frequency             "fft-log-frequency"
#define S_fft_log_magnitude             "fft-log-magnitude"
#define S_fft_size                      "fft-size"
#define S_fft_style                     "fft-style"
#define S_fft_window                    "fft-window"
#define S_ffting                        "ffting"
#define S_file_dialog                   "file-dialog"
#define S_file_name                     "file-name"
#define S_file_names                    "file-names"
#define S_filter_sound                  "filter-sound"
#define S_filter_dBing                  "filter-dBing"
#define S_filter_env                    "filter-env"
#define S_filter_env_order              "filter-env-order"
#define S_filter_order                  "filter-order"
#define S_filter_selection              "filter-selection"
#define S_filter_waveform_color         "filter-waveform-col" STR_OR
#define S_filtering                     "filtering"
#define S_find                          "find"
#define S_find_mark                     "find-mark"
#define S_find_sound                    "find-sound"
#define S_finish_progress_report        "finish-progress-report"
#define S_fit_data_on_open              "fit-data-on-open"
#define S_focus_active                  "focus-active"
#define S_focus_left                    "focus-left"
#define S_focus_middle                  "focus-middle"
#define S_focus_right                   "focus-right"
#define S_forward_graph                 "forward-graph"
#define S_forward_mark                  "forward-mark"
#define S_forward_mix                   "forward-mix"
#define S_forward_sample                "forward-sample"
#define S_fourier_transform             "fourier-transform"
#define S_frames                        "frames"
#define S_free_mix_sample_reader        "free-mix-sample-reader"
#define S_free_sample_reader            "free-sample-reader"
#define S_free_track_sample_reader      "free-track-sample-reader"
#define S_graph                         "graph"
#define S_graph_color                   "graph-col" STR_OR
#define S_graph_cursor                  "graph-cursor"
#define S_graph_dots                    "graph-dots"
#define S_graph_dots_and_lines          "graph-dots-and-lines"
#define S_graph_filled                  "graph-filled"
#define S_graph_hook                    "graph-hook"
#define S_graph_lines                   "graph-lines"
#define S_graph_lollipops               "graph-lollipops"
#define S_graph_ps                      "graph->ps"
#define S_graph_style                   "graph-style"
#define S_graphing                      "graphing"
#define S_graphs_horizontal             "graphs-horizontal"
#define S_hadamard_transform            "hadamard-transform"
#define S_hankel_transform              "hankel-transform"
#define S_header_type                   "header-type"
#define S_help_dialog                   "help-dialog"
#define S_hide_listener                 "hide-listener"
#define S_help_text_font                "help-text-font"
#define S_highlight_color               "highlight-col" STR_OR
#define S_html_dir                      "html-dir"
#define S_id_region                     "id-region"
#define S_in                            "in"
#define S_initial_x0                    "initial-x0"
#define S_initial_x1                    "initial-x1"
#define S_initial_y0                    "initial-y0"
#define S_initial_y1                    "initial-y1"
#define S_insert_region                 "insert-region"
#define S_insert_sample                 "insert-sample"
#define S_insert_samples                "insert-samples"
#define S_insert_samples_with_origin    "insert-samples-with-origin"
#define S_insert_sound                  "insert-sound"
#define S_key                           "key"
#define S_key_press_hook                "key-press-hook"
#define S_keyboard_no_action            "keyboard-no-action"
#define S_left_sample                   "left-sample"
#define S_line_size                     "line-size"
#define S_listener_color                "listener-col" STR_OR
#define S_listener_font                 "listener-font"
#define S_listener_prompt               "listener-prompt"
#define S_load_colormap                 "load-colormap"
#define S_loop_samples                  "loop-samples"
#define S_make_color                    "make-col" STR_OR
#define S_make_mix_sample_reader        "make-mix-sample-reader"
#define S_make_region                   "make-region"
#define S_make_region_sample_reader     "make-region-sample-reader"
#define S_make_sample_reader            "make-sample-reader"
#define S_make_track_sample_reader      "make-track-sample-reader"
#define S_map_across_all_chans          "map-across-all-chans"
#define S_map_across_chans              "map-across-chans"
#define S_map_across_sound_chans        "map-across-sound-chans"
#define S_map_chan                      "map-chan"
#define S_map_chans                     "map-chans"
#define S_map_sound_chans               "map-sound-chans"
#define S_map_all_chans                 "map-all-chans"
#define S_mark_click_hook               "mark-click-hook"
#define S_mark_color                    "mark-col" STR_OR
#define S_mark_name                     "mark-name"
#define S_mark_sample                   "mark-sample"
#define S_mark_sync                     "mark-sync"
#define S_mark_sync_max                 "mark-sync-max"
#define S_mark_to_sound                 "mark->sound"
#define S_marks                         "marks"
#define S_markQ                         "mark?"
#define S_max_fft_peaks                 "max-fft-peaks"
#define S_max_regions                   "max-regions"
#define S_max_sounds                    "max-sounds"
#define S_maxamp                        "maxamp"
#define S_memo_sound                    "memo-sound"
#define S_min_dB                        "min-dB"
#define S_mix                           "mix"
#define S_mixes                         "mixes"
#define S_mix_amp                       "mix-amp"
#define S_mix_amp_changed_hook          "mix-amp-changed-hook"
#define S_mix_amp_env                   "mix-amp-env"
#define S_mix_anchor                    "mix-anchor"
#define S_mix_chans                     "mix-chans"
#define S_mix_color                     "mix-col" STR_OR
#define S_mix_console_amp_scaler        "mix-console-amp-scaler"
#define S_mix_console_speed_scaler      "mix-console-speed-scaler"
#define S_mix_console_state             "mix-console-state"
#define S_mix_console_state_changed_hook "mix-console-state-changed-hook"
#define S_mix_console_y                 "mix-console-y"
#define S_mix_focus_color               "mix-focus-col" STR_OR
#define S_mix_track                     "mix-track"
#define S_mix_length                    "mix-length"
#define S_mix_locked                    "mix-locked"
#define S_mix_name                      "mix-name"
#define S_mixQ                          "mix?"
#define S_mix_position                  "mix-position"
#define S_mix_position_changed_hook     "mix-position-changed-hook"
#define S_mix_region                    "mix-region"
#define S_mix_sample_readerQ            "mix-sample-reader?"
#define S_mix_sound                     "mix-sound"
#define S_mix_sound_channel             "mix-sound-channel"
#define S_mix_sound_index               "mix-sound-index"
#define S_mix_speed                     "mix-speed"
#define S_mix_speed_changed_hook        "mix-speed-changed-hook"
#define S_mix_vct                       "mix-vct"
#define S_mix_waveform_color            "mix-waveform-col" STR_OR
#define S_mix_waveform_height           "mix-waveform-height"
#define S_mouse_drag_hook               "mouse-drag-hook"
#define S_mouse_press_hook              "mouse-press-hook"
#define S_mouse_release_hook            "mouse-release-hook"
#define S_movies                        "movies"
#define S_multichannel_mix_hook         "multichannel-mix-hook"
#define S_mus_error_hook                "mus-error-hook"
#define S_name_click_hook               "name-click-hook"
#define S_new_sound                     "new-sound"
#define S_next_mix_sample               "next-mix-sample"
#define S_next_sample                   "next-sample"
#define S_next_track_sample             "next-track-sample"
#define S_normal_fft                    "normal-fft"
#define S_normalize_fft                 "normalize-fft"
#define S_normalize_on_open             "normalize-on-open"
#define S_normalize_view                "normalize-view"
#define S_open_alternate_sound          "open-alternate-sound"
#define S_open_hook                     "open-hook"
#define S_open_multifile_sound_hook     "open-multifile-sound-hook"
#define S_open_raw_sound                "open-raw-sound"
#define S_open_sound                    "open-sound"
#define S_open_sound_file               "open-sound-file"
#define S_orientation_dialog            "orientation-dialog"
#define S_output_comment_hook           "output-comment-hook"
#define S_output_name_hook              "output-name-hook"
#define S_override_data_format          "override-data-format"
#define S_override_data_location        "override-data-location"
#define S_override_data_size            "override-data-size"
#define S_peaks                         "peaks"
#define S_play                          "play"
#define S_play_and_wait                 "play-and-wait"
#define S_play_mix                      "play-mix"
#define S_play_region                   "play-region"
#define S_play_selection                "play-selection"
#define S_play_track                    "play-track"
#define S_position_color                "position-col" STR_OR
#define S_prefix_arg                    "prefix-arg"
#define S_preload_directory             "preload-directory"
#define S_preload_file                  "preload-file"
#define S_previous_files_sort           "previous-files-sort"
#define S_previous_sample               "previous-sample"
#define S_print_length                  "print-length"
#define S_progress_report               "progress-report"
#define S_prompt_in_minibuffer          "prompt-in-minibuffer"
#define S_protect_region                "protect-region"
#define S_pushed_button_color           "pushed-button-col" STR_OR
#define S_raw_chans                     "raw-chans"
#define S_raw_format                    "raw-format"
#define S_raw_srate                     "raw-srate"
#define S_read_only                     "read-only"
#define S_recorder_autoload             "recorder-autoload"
#define S_recorder_buffer_size          "recorder-buffer-size"
#define S_recorder_dialog               "recorder-dialog"
#define S_recorder_file                 "recorder-file"
#define S_recorder_gain                 "recorder-gain"
#define S_recorder_in_amp               "recorder-in-amp"
#define S_recorder_in_format            "recorder-in-format"
#define S_recorder_max_duration         "recorder-max-duration"
#define S_recorder_out_amp              "recorder-out-amp"
#define S_recorder_out_chans            "recorder-out-chans"
#define S_recorder_out_format           "recorder-out-format"
#define S_recorder_srate                "recorder-srate"
#define S_recorder_trigger              "recorder-trigger"
#define S_redo                          "redo"
#define S_region_chans                  "region-chans"
#define S_region_dialog                 "region-dialog"
#define S_region_id                     "region-id"
#define S_region_length                 "region-length"
#define S_region_maxamp                 "region-maxamp"
#define S_region_sample                 "region-sample"
#define S_region_samples                "region-samples"
#define S_region_samples_vct            "region-samples->vct"
#define S_region_srate                  "region-srate"
#define S_regions                       "regions"
#define S_regionQ                       "region?"
#define S_remove_from_menu              "remove-from-menu"
#define S_report_in_minibuffer          "report-in-minibuffer"
#define S_restore_control_panel         "restore-control-panel"
#define S_restore_marks                 "restore-marks"
#define S_restore_region                "restore-region"
#define S_reverb_decay                  "reverb-decay"
#define S_reverb_feedback               "reverb-feedback"
#define S_reverb_funcs                  "reverb-funcs"
#define S_reverb_length                 "reverb-length"
#define S_reverb_lowpass                "reverb-lowpass"
#define S_reverb_scale                  "reverb-scale"
#define S_reverbing                     "reverbing"
#define S_reverse_sound                 "reverse-sound"
#define S_reverse_selection             "reverse-selection"
#define S_revert_sound                  "revert-sound"
#define S_right_sample                  "right-sample"
#define S_sample                        "sample"
#define S_sample_reader_at_endQ         "sample-reader-at-end?"
#define S_sample_readerQ                "sample-reader?"
#define S_samples                       "samples"
#define S_samples_vct                   "samples->vct"
#define S_samples2sound_data            "samples->sound-data"
#define S_save_control_panel            "save-control-panel"
#define S_save_dir                      "save-dir"
#define S_save_edit_history             "save-edit-history"
#define S_save_envelopes                "save-envelopes"
#define S_save_hook                     "save-hook"
#define S_save_macros                   "save-macros"
#define S_save_marks                    "save-marks"
#define S_save_options                  "save-options"
#define S_save_region                   "save-region"
#define S_save_selection                "save-selection"
#define S_save_sound                    "save-sound"
#define S_save_sound_as                 "save-sound-as"
#define S_save_multifile_sound_hook     "save-multifile-sound-hook"
#define S_save_state                    "save-state"
#define S_save_state_file               "save-state-file"
#define S_save_state_on_exit            "save-state-on-exit"
#define S_scale_by                      "scale-by"
#define S_scale_selection_by            "scale-selection-by"
#define S_scale_selection_to            "scale-selection-to"
#define S_scale_to                      "scale-to" 
#define S_scan_across_all_chans         "scan-across-all-chans"
#define S_scan_across_chans             "scan-across-chans"
#define S_scan_across_sound_chans       "scan-across-sound-chans"
#define S_scan_chan                     "scan-chan"
#define S_scan_chans                    "scan-chans"
#define S_scan_sound_chans              "scan-sound-chans"
#define S_scan_all_chans                "scan-all-chans"
#define S_select_all                    "select-all"
#define S_select_channel                "select-channel"
#define S_select_mix                    "select-mix"
#define S_select_region                 "select-region"
#define S_select_sound                  "select-sound"
#define S_selected_channel              "selected-channel"
#define S_selected_data_color           "selected-data-col" STR_OR
#define S_selected_graph_color          "selected-graph-col" STR_OR
#define S_selected_mix                  "selected-mix"
#define S_selected_sound                "selected-sound"
#define S_selection_beg                 "selection-beg"
#define S_selection_color               "selection-col" STR_OR
#define S_selection_length              "selection-length"
#define S_selection_member              "selection-member"
#define S_selection_to_temp             "selection-to-temp"
#define S_selection_to_temps            "selection-to-temps"
#define S_selectionQ                    "selection?"
#define S_set_amp                       "set-amp"
#define S_set_ask_before_overwrite      "set-ask-before-overwrite"
#define S_set_audio_output_device       "set-audio-output-device"
#define S_set_audio_state_file          "set-audio-state-file"
#define S_set_auto_resize               "set-auto-resize"
#define S_set_auto_update               "set-auto-update"
#define S_set_axis_label_font           "set-axis-label-font"
#define S_set_axis_numbers_font         "set-axis-numbers-font"
#define S_set_basic_color               "set-basic-col" STR_OR
#define S_set_bold_button_font          "set-bold-button-font"
#define S_set_button_font               "set-button-font"
#define S_set_channel_style             "set-channel-style"
#define S_set_color_cutoff              "set-col" STR_OR "-cutoff"
#define S_set_color_inverted            "set-col" STR_OR "-inverted"
#define S_set_color_scale               "set-col" STR_OR "-scale"
#define S_set_colormap                  "set-colormap"
#define S_set_contrast                  "set-contrast"
#define S_set_contrast_amp              "set-contrast-amp"
#define S_set_contrast_func             "set-contrast-func"
#define S_set_contrasting               "set-contrasting"
#define S_set_corruption_time           "set-corruption-time"
#define S_set_cursor                    "set-cursor"
#define S_set_cursor_color              "set-cursor-col" STR_OR
#define S_set_cursor_follows_play       "set-cursor-follows-play"
#define S_set_cursor_style              "set-cursor-style"
#define S_set_dac_folding               "set-dac-folding"
#define S_set_dac_size                  "set-dac-size"
#define S_set_data_clipped              "set-data-clipped"
#define S_set_data_color                "set-data-col" STR_OR
#define S_set_default_output_chans      "set-default-output-chans"
#define S_set_default_output_format     "set-default-output-format"
#define S_set_default_output_srate      "set-default-output-srate"
#define S_set_default_output_type       "set-default-output-type"
#define S_set_dot_size                  "set-dot-size"
#define S_set_env_base                  "set-env-base"
#define S_set_enved_base                "set-enved-base"
#define S_set_enved_clipping            "set-enved-clipping"
#define S_set_enved_dBing               "set-enved-dBing"
#define S_set_enved_exping              "set-enved-exping"
#define S_set_enved_power               "set-enved-power"
#define S_set_enved_target              "set-enved-target"
#define S_set_enved_waveform_color      "set-enved-waveform-col" STR_OR
#define S_set_enved_waving              "set-enved-waving"
#define S_set_eps_file                  "set-eps-file"
#define S_set_erase_zeros               "set-erase-zeros"
#define S_set_expand                    "set-expand"
#define S_set_expand_funcs              "set-expand-funcs"
#define S_set_expand_hop                "set-expand-hop"
#define S_set_expand_length             "set-expand-length"
#define S_set_expand_ramp               "set-expand-ramp"
#define S_set_expanding                 "set-expanding"
#define S_set_fft_beta                  "set-fft-beta"
#define S_set_fft_log_frequency         "set-fft-log-frequency"
#define S_set_fft_log_magnitude         "set-fft-log-magnitude"
#define S_set_fft_size                  "set-fft-size"
#define S_set_fft_style                 "set-fft-style"
#define S_set_fft_window                "set-fft-window"
#define S_set_ffting                    "set-ffting"
#define S_set_filter_dBing              "set-filter-dBing"
#define S_set_filter_env                "set-filter-env"
#define S_set_filter_env_order          "set-filter-env-order"
#define S_set_filter_order              "set-filter-order"
#define S_set_filter_waveform_color     "set-filter-waveform-col" STR_OR
#define S_set_filtering                 "set-filtering"
#define S_set_fit_data_on_open          "set-fit-data-on-open"
#define S_set_graph_color               "set-graph-col" STR_OR
#define S_set_graph_cursor              "set-graph-cursor"
#define S_set_graph_style               "set-graph-style"
#define S_set_graphing                  "set-graphing"
#define S_set_graphs_horizontal         "set-graphs-horizontal"
#define S_set_help_text_font            "set-help-text-font"
#define S_set_highlight_color           "set-highlight-col" STR_OR
#define S_set_html_dir                  "set-html-dir"
#define S_set_initial_x0                "set-initial-x0"
#define S_set_initial_x1                "set-initial-x1"
#define S_set_initial_y0                "set-initial-y0"
#define S_set_initial_y1                "set-initial-y1"
#define S_set_just_sounds               "set-just-sounds"
#define S_set_left_sample               "set-left-sample"
#define S_set_line_size                 "set-line-size"
#define S_set_listener_color            "set-listener-col" STR_OR
#define S_set_listener_font             "set-listener-font"
#define S_set_listener_prompt           "set-listener-prompt"
#define S_set_mark_color                "set-mark-col" STR_OR
#define S_set_mark_name                 "set-mark-name"
#define S_set_mark_sample               "set-mark-sample"
#define S_set_mark_sync                 "set-mark-sync"
#define S_set_max_fft_peaks             "set-max-fft-peaks"
#define S_set_max_regions               "set-max-regions"
#define S_set_menu_sensitive            "set-menu-sensitive"
#define S_set_min_dB                    "set-min-dB"
#define S_set_mix_amp                   "set-mix-amp"
#define S_set_mix_amp_env               "set-mix-amp-env"
#define S_set_mix_anchor                "set-mix-anchor"
#define S_set_mix_color                 "set-mix-col" STR_OR
#define S_set_mix_console_amp_scaler    "set-mix-console-amp-scaler"
#define S_set_mix_console_speed_scaler  "set-mix-console-speed-scaler"
#define S_set_mix_console_state         "set-mix-console-state"
#define S_set_mix_console_y             "set-mix-console-y"
#define S_set_mix_focus_color           "set-mix-focus-col" STR_OR
#define S_set_mix_track                 "set-mix-track"
#define S_set_mix_length                "set-mix-length"
#define S_set_mix_locked                "set-mix-locked"
#define S_set_mix_name                  "set-mix-name"
#define S_set_mix_position              "set-mix-position"
#define S_set_mix_speed                 "set-mix-speed"
#define S_set_mix_waveform_color        "set-mix-waveform-col" STR_OR
#define S_set_mix_waveform_height       "set-mix-waveform-height"
#define S_set_movies                    "set-movies"
#define S_set_normalize_fft             "set-normalize-fft"
#define S_set_normalize_on_open         "set-normalize-on-open"
#define S_set_oss_buffers               "set-oss-buffers"
#define S_set_position_color            "set-position-col" STR_OR
#define S_set_prefix_arg                "set-prefix-arg"
#define S_set_previous_files_sort       "set-previous-files-sort"
#define S_set_print_length              "set-print-length"
#define S_set_pushed_button_color       "set-pushed-button-col" STR_OR
#define S_set_raw_chans                 "set-raw-chans"
#define S_set_raw_format                "set-raw-format"
#define S_set_raw_srate                 "set-raw-srate"
#define S_set_read_only                 "set-read-only"
#define S_set_recorder_autoload         "set-recorder-autoload"
#define S_set_recorder_buffer_size      "set-recorder-buffer-size"
#define S_set_recorder_file             "set-recorder-file"
#define S_set_recorder_gain             "set-recorder-gain"
#define S_set_recorder_in_amp           "set-recorder-in-amp"
#define S_set_recorder_in_format        "set-recorder-in-format"
#define S_set_recorder_max_duration     "set-recorder-max-duration"
#define S_set_recorder_out_amp          "set-recorder-out-amp"
#define S_set_recorder_out_chans        "set-recorder-out-chans"
#define S_set_recorder_out_format       "set-recorder-out-format"
#define S_set_recorder_srate            "set-recorder-srate"
#define S_set_recorder_trigger          "set-recorder-trigger"
#define S_set_reverb_decay              "set-reverb-decay"
#define S_set_reverb_feedback           "set-reverb-feedback"
#define S_set_reverb_funcs              "set-reverb-funcs"
#define S_set_reverb_length             "set-reverb-length"
#define S_set_reverb_lowpass            "set-reverb-lowpass"
#define S_set_reverb_scale              "set-reverb-scale"
#define S_set_reverbing                 "set-reverbing"
#define S_set_right_sample              "set-right-sample"
#define S_set_sample                    "set-sample"
#define S_set_samples                   "set-samples"
#define S_set_save_dir                  "set-save-dir"
#define S_set_save_state_file           "set-save-state-file"
#define S_set_save_state_on_exit        "set-save-state-on-exit"
#define S_set_selected_data_color       "set-selected-data-col" STR_OR
#define S_set_selected_graph_color      "set-selected-graph-col" STR_OR
#define S_set_selection_color           "set-selection-col" STR_OR
#define S_set_show_axes                 "set-show-axes"
#define S_set_show_fft_peaks            "set-show-fft-peaks"
#define S_set_show_indices              "set-show-indices"
#define S_set_show_marks                "set-show-marks"
#define S_set_show_mix_consoles         "set-show-mix-consoles"
#define S_set_show_mix_waveforms        "set-show-mix-waveforms"
#define S_set_show_selection_transform  "set-show-selection-transform"
#define S_set_show_usage_stats          "set-show-usage-stats"
#define S_set_show_y_zero               "set-show-y-zero"
#define S_set_showing_controls          "set-showing-controls"
#define S_set_sinc_width                "set-sinc-width"
#define S_set_sound_loop_info           "set-sound-loop-info"
#define S_set_spectro_cutoff            "set-spectro-cutoff"
#define S_set_spectro_hop               "set-spectro-hop"
#define S_set_spectro_start             "set-spectro-start"
#define S_set_spectro_x_angle           "set-spectro-x-angle"
#define S_set_spectro_x_scale           "set-spectro-x-scale"
#define S_set_spectro_y_angle           "set-spectro-y-angle"
#define S_set_spectro_y_scale           "set-spectro-y-scale"
#define S_set_spectro_z_angle           "set-spectro-z-angle"
#define S_set_spectro_z_scale           "set-spectro-z-scale"
#define S_set_speed                     "set-speed"
#define S_set_speed_style               "set-speed-style"
#define S_set_speed_tones               "set-speed-tones"
#define S_set_squelch_update            "set-squelch-update"
#define S_set_syncing                   "set-syncing"
#define S_set_temp_dir                  "set-temp-dir"
#define S_set_text_focus_color          "set-text-focus-col" STR_OR
#define S_set_tiny_font                 "set-tiny-font"
#define S_set_transform_type            "set-transform-type"
#define S_set_trap_segfault             "set-trap-segfault"
#define S_set_uniting                   "set-uniting"
#define S_set_use_raw_defaults          "set-use-raw-defaults"
#define S_set_use_sinc_interp           "set-use-sinc-interp"
#define S_set_verbose_cursor            "set-verbose-cursor"
#define S_set_vu_font                   "set-vu-font"
#define S_set_vu_font_size              "set-vu-font-size"
#define S_set_vu_size                   "set-vu-size"
#define S_set_wavelet_type              "set-wavelet-type"
#define S_set_waving                    "set-waving"
#define S_set_wavo                      "set-wavo"
#define S_set_wavo_hop                  "set-wavo-hop"
#define S_set_wavo_trace                "set-wavo-trace"
#define S_set_window_height             "set-window-height"
#define S_set_window_width              "set-window-width"
#define S_set_window_x                  "set-window-x"
#define S_set_window_y                  "set-window-y"
#define S_set_with_mix_consoles         "set-with-mix-consoles"
#define S_set_x_axis_style              "set-x-axis-style"
#define S_set_x_bounds                  "set-x-bounds"
#define S_set_xmax                      "set-xmax"
#define S_set_xmin                      "set-xmin"
#define S_set_y_bounds                  "set-y-bounds"
#define S_set_ymax                      "set-ymax"
#define S_set_ymin                      "set-ymin"
#define S_set_zero_pad                  "set-zero-pad"
#define S_set_zoom_color                "set-zoom-col" STR_OR
#define S_set_zoom_focus_style          "set-zoom-focus-style"
#define S_short_file_name               "short-file-name"
#define S_short_file_names              "short-file-names"
#define S_show_all_axes                 "show-all-axes"
#define S_show_axes                     "show-axes"
#define S_show_fft_peaks                "show-fft-peaks"
#define S_show_indices                  "show-indices"
#define S_show_listener                 "show-listener"
#define S_show_marks                    "show-marks"
#define S_show_mix_consoles             "show-mix-consoles"
#define S_show_mix_waveforms            "show-mix-waveforms"
#define S_show_no_axes                  "show-no-axes"
#define S_show_selection_transform      "show-selection-transform"
#define S_show_usage_stats              "show-usage-stats"
#define S_show_x_axis                   "show-x-axis"
#define S_show_y_zero                   "show-y-zero"
#define S_showing_controls              "showing-controls"
#define S_sinc_width                    "sinc-width"
#define S_smooth                        "smooth"
#define S_smooth_selection              "smooth-selection"
#define S_snd_apropos                   "snd-apropos"
#define S_snd_error                     "snd-error"
#define S_snd_error_hook                "snd-error-hook"
#define S_snd_help                      "snd-help"
#define S_snd_print                     "snd-print"
#define S_snd_spectrum                  "snd-spectrum"
#define S_snd_tempnam                   "snd-tempnam"
#define S_snd_version                   "snd-version"
#define S_snd_warning                   "snd-warning"
#define S_snd_warning_hook              "snd-warning-hook"
#define S_sonogram                      "sonogram"
#define S_sound_files_in_directory      "sound-files-in-directory"
#define S_sound_to_temp                 "sound-to-temp"
#define S_sound_to_temps                "sound-to-temps"
#define S_soundfont_info                "soundfont-info"
#define S_soundQ                        "sound?"
#define S_sounds                        "sounds"
#define S_spectro_cutoff                "spectro-cutoff"
#define S_spectro_hop                   "spectro-hop"
#define S_spectro_start                 "spectro-start"
#define S_spectro_x_angle               "spectro-x-angle"
#define S_spectro_x_scale               "spectro-x-scale"
#define S_spectro_y_angle               "spectro-y-angle"
#define S_spectro_y_scale               "spectro-y-scale"
#define S_spectro_z_angle               "spectro-z-angle"
#define S_spectro_z_scale               "spectro-z-scale"
#define S_spectrogram                   "spectrogram"
#define S_spectrum_env                  "spectrum-env"
#define S_speed                         "speed"
#define S_speed_as_float                "speed-as-float"
#define S_speed_as_ratio                "speed-as-ratio"
#define S_speed_as_semitone             "speed-as-semitone"
#define S_speed_style                   "speed-style"
#define S_speed_tones                   "speed-tones"
#define S_squelch_update                "squelch-update"
#define S_srate                         "srate"
#define S_srate_env                     "srate-env"
#define S_src_sound                     "src-sound"
#define S_src_selection                 "src-selection"
#define S_start_hook                    "start-hook"
#define S_start_playing_hook            "start-playing-hook"
#define S_start_progress_report         "start-progress-report"
#define S_stop_playing                  "stop-playing"
#define S_stop_playing_hook             "stop-playing-hook"
#define S_stop_playing_region_hook      "stop-playing-region-hook"
#define S_string_length                 "string-length"
#define S_swap_channels                 "swap-channels"
#define S_syncd_marks                   "syncd-marks"
#define S_syncing                       "syncing"
#define S_temp_dir                      "temp-dir"
#define S_temp_filenames                "temp-filenames"
#define S_temp_to_selection             "temp-to-selection"
#define S_temp_to_sound                 "temp-to-sound"
#define S_temps_to_selection            "temps-to-selection"
#define S_temps_to_sound                "temps-to-sound"
#define S_text_focus_color              "text-focus-col" STR_OR
#define S_tiny_font                     "tiny-font"
#define S_track_sample_readerQ          "track-sample-reader?"
#define S_transform_dialog              "transform-dialog"
#define S_transform_sample              "transform-sample"
#define S_transform_samples             "transform-samples"
#define S_transform_samples_vct         "transform-samples->vct"
#define S_transform_size                "transform-size"
#define S_transform_type                "transform-type"
#define S_trap_segfault                 "trap-segfault"
#define S_unbind_key                    "unbind-key"  
#define S_undo                          "undo"
#define S_undo_hook                     "undo-hook"
#define S_uniting                       "uniting"
#define S_update_fft                    "update-fft"
#define S_update_graph                  "update-graph"
#define S_update_sound                  "update-sound"
#define S_update_usage_stats            "update-usage-stats"
#define S_use_raw_defaults              "use-raw-defaults"
#define S_use_sinc_interp               "use-sinc-interp"
#define S_vct_samples                   "vct->samples"
#define S_vct_sound_file                "vct->sound-file"
#define S_verbose_cursor                "verbose-cursor"
#define S_view_sound                    "view-sound"
#define S_vu_font                       "vu-font"
#define S_vu_font_size                  "vu-font-size"
#define S_vu_size                       "vu-size"
#define S_walsh_transform               "walsh-transform"
#define S_wavelet_transform             "wavelet-transform"
#define S_wavelet_type                  "wavelet-type"
#define S_waving                        "waving"
#define S_wavo                          "wavo"
#define S_wavo_hop                      "wavo-hop"
#define S_wavo_trace                    "wavo-trace"
#define S_window_height                 "window-height"
#define S_window_width                  "window-width"
#define S_window_x                      "window-x"
#define S_window_y                      "window-y"
#define S_with_mix_consoles             "with-mix-consoles"
#define S_x_axis_style                  "x-axis-style"
#define S_x_bounds                      "x-bounds"
#define S_x_in_samples                  "x-in-samples"
#define S_x_in_seconds                  "x-in-seconds"
#define S_x_position_slider             "x-position-slider"
#define S_x_to_one                      "x-to-one"
#define S_x_zoom_slider                 "x-zoom-slider"
#define S_xmax                          "xmax"
#define S_xmin                          "xmin"
#define S_y_bounds                      "y-bounds"
#define S_y_position_slider             "y-position-slider"
#define S_y_zoom_slider                 "y-zoom-slider"
#define S_yes_or_no_p                   "yes-or-no-p"
#define S_ymax                          "ymax"
#define S_ymin                          "ymin"
#define S_zero_pad                      "zero-pad"
#define S_zoom_color                    "zoom-col" STR_OR
#define S_zoom_focus_style              "zoom-focus-style"

#endif
