#ifndef XG_X11_H
#define XG_X11_H

/* functions shared by xg.c and xm.c if WITH_GTK_AND_X11 */
/* created automatically by makexg.scm */
XEN gxg_visual(XEN ptr);
XEN gxg_type(XEN ptr);
XEN gxg_window(XEN ptr);
XEN gxg_send_event(XEN ptr);
XEN gxg_count(XEN ptr);
XEN gxg_state(XEN ptr);
XEN gxg_time(XEN ptr);
XEN gxg_x(XEN ptr);
XEN gxg_y(XEN ptr);
XEN gxg_is_hint(XEN ptr);
XEN gxg_x_root(XEN ptr);
XEN gxg_y_root(XEN ptr);
XEN gxg_button(XEN ptr);
XEN gxg_subwindow(XEN ptr);
XEN gxg_mode(XEN ptr);
XEN gxg_detail(XEN ptr);
XEN gxg_focus(XEN ptr);
XEN gxg_width(XEN ptr);
XEN gxg_height(XEN ptr);
XEN gxg_atom(XEN ptr);
XEN gxg_selection(XEN ptr);
XEN gxg_target(XEN ptr);
XEN gxg_property(XEN ptr);
XEN gxg_requestor(XEN ptr);
XEN gxg_name(XEN ptr);
XEN gxg_function(XEN ptr);
XEN gxg_tile(XEN ptr);
XEN gxg_stipple(XEN ptr);
XEN gxg_clip_mask(XEN ptr);
XEN gxg_subwindow_mode(XEN ptr);
XEN gxg_ts_x_origin(XEN ptr);
XEN gxg_ts_y_origin(XEN ptr);
XEN gxg_clip_x_origin(XEN ptr);
XEN gxg_clip_y_origin(XEN ptr);
XEN gxg_graphics_exposures(XEN ptr);
XEN gxg_line_width(XEN ptr);
XEN gxg_line_style(XEN ptr);
XEN gxg_cap_style(XEN ptr);
XEN gxg_join_style(XEN ptr);
XEN gxg_colormap(XEN ptr);
XEN gxg_byte_order(XEN ptr);
XEN gxg_depth(XEN ptr);
XEN gxg_bits_per_pixel(XEN ptr);
XEN gxg_keycode(XEN ptr);
XEN gxg_x1(XEN ptr);
XEN gxg_y1(XEN ptr);
XEN gxg_x2(XEN ptr);
XEN gxg_y2(XEN ptr);
XEN gxg_colormap_size(XEN ptr);
XEN gxg_bits_per_rgb(XEN ptr);
XEN gxg_red_mask(XEN ptr);
XEN gxg_green_mask(XEN ptr);
XEN gxg_blue_mask(XEN ptr);
XEN gxg_event_mask(XEN ptr);
XEN gxg_cursor(XEN ptr);
XEN gxg_override_redirect(XEN ptr);
XEN gxg_min_width(XEN ptr);
XEN gxg_min_height(XEN ptr);
XEN gxg_max_width(XEN ptr);
XEN gxg_max_height(XEN ptr);
XEN gxg_width_inc(XEN ptr);
XEN gxg_height_inc(XEN ptr);
XEN gxg_win_gravity(XEN ptr);
XEN gxg_parent(XEN ptr);
XEN gxg_font(XEN ptr);
XEN gxg_border_width(XEN ptr);
XEN gxg_ascent(XEN ptr);
XEN gxg_descent(XEN ptr);
XEN gxg_root(XEN ptr);
XEN gxg_flags(XEN ptr);
XEN gxg_backing_store(XEN ptr);
XEN gxg_format(XEN ptr);
XEN gxg_data(XEN ptr);
XEN gxg_pixel(XEN ptr);
XEN gxg_red(XEN ptr);
XEN gxg_green(XEN ptr);
XEN gxg_blue(XEN ptr);
XEN gxg_set_pixel(XEN ptr, XEN val);
XEN gxg_set_red(XEN ptr, XEN val);
XEN gxg_set_green(XEN ptr, XEN val);
XEN gxg_set_blue(XEN ptr, XEN val);
#endif
