(provide 'snd-new-icons.scm)

(define icon-save-as (list
"32 25 5 1"
"       c white"
".      c lightslategrey"
"X      c black"
"o      c blue"
"O      c red"
"                                "
" ..............................X"
" ..............................X"
" ..............................X"
" ..............................X"
" ..............................X"
" .......oooOOOOOOOOOOoo........X"
" .......oooOOOOOOOOOOoo........X"
" .......ooo          oo........X"
" .......ooo          oo........X"
" .......ooo          oo........X"
" .......ooooooooooooooo........X"
" .......ooooooooooooooo........X"
" .......ooooooooooooooo........X"
" .......ooo         ooo........X"
" .......ooo         ooo........X"
" .......ooo ooo     ooo........X"
" .......ooo ooo     ooo........X"
" ........oo ooo     ooo........X"
" ..............................X"
" ..............................X"
" ..............................X"
" ..............................X"
" ..............................X"
" XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX"))

(define icon-env-edit (list
"32 25 4 1"
"       c white"
".      c yellow"
"X      c black"
"o      c darkgrey"
"                                "
" ..............................X"
" ......XXXX....................X"
" ......X.......................X"
" ......X.......................X"
" ......X.......................X"
" ......XXXX..X.XX..X.....X.....X"
" ......X.....X...X..X...X......X"
" ......X.....X...X..X...X......X"
" ......X.....X...X...X.X.......X"
" ......XXXX..X...X....X........X"
" ..............................X"
" ..............................X"
" ......XXXX......X..X..X.......X"
" ......X.........X.....X.......X"
" ......X......XX.X..X.XXX......X"
" ......X.....X..XX..X..X.......X"
" ......XXXX..X...X..X..X.......X"
" ......X.....X...X..X..X.......X"
" ......X.....X...X..X..X.......X"
" ......X.....X..XX..X..X.......X"
" ......XXXX...XX.X..X..XX......X"
" ..............................X"
" ..............................X"
" XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX"))

(define icon-no-fear (list
"32 25 3 1"
"       c white"
".      c red"
"X      c black"
"                                "
" ..............................X"
" ..............................X"
" ..XXXX........................X"
" ..X...X.......................X"
" ..X....X......................X"
" ..X.....X..............XX..X..X"
" ..X.....X..XXXX..X.XXX..X.XXX.X"
" ..X.....X.X....X.XX...X....X..X"
" ..X....X..X....X.X....X....X..X"
" ..X...X...X....X.X....X....X..X"
" ..XXXX.....XXXX..X....X....X..X"
" ..............................X"
" ..............................X"
" ..XXXX........................X"
" ..X...X.......................X"
" ..X...X.......................X"
" ..XXXX................X.......X"
" ..X......XXXX..X.XXX..X..XXX..X"
" ..X.....X....X.XX...X.X.X.....X"
" ..X.....X....X.X....X.X.X.....X"
" ..X.....X...XX.X....X.X.X.....X"
" ..X......XXX.X.X....X.X..XXX..X"
" ..............................X"
" XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX"))


(define icon-regions-browser (list
"32 25 4 1"
"       c white"
".      c yellow"
"X      c black"
"o      c darkgrey"
"                                "
" ..............................X"
" ......XXXX....................X"
" ......X...X...................X"
" ......X....X..................X"
" ......X...X...................X"
" ......XXXX.....XXXX...XXXX....X"
" ......X...X...X....X.X....X...X"
" ......X....X..XXXXX..X....X...X"
" ......X.....X..X.....X....X...X"
" ......X......X..XXXX..XXXXX...X"
" ..........................X...X"
" .......................XXX....X"
" ......XXXX......X..X..X.......X"
" ......X.........X.....X.......X"
" ......X......XX.X..X.XXX......X"
" ......X.....X..XX..X..X.......X"
" ......XXXX..X...X..X..X.......X"
" ......X.....X...X..X..X.......X"
" ......X.....X...X..X..X.......X"
" ......X.....X..XX..X..X.......X"
" ......XXXX...XX.X..X..XX......X"
" ..............................X"
" ..............................X"
" XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX"))

(define icon-mix-pane (list
"32 25 4 1"
"       c white"
".      c yellow"
"X      c black"
"o      c darkgrey"
"                                "
" ..............................X"
" ..............................X"
" ......XX.....XX..X............X"
" ......X.X...X.X...............X"
" ......X..X.X..X..X..X....X....X"
" ......X...X...X..X...X..X.....X"
" ......X.......X..X....XX......X"
" ......X.......X..X....XX......X"
" ......X.......X..X...X..X.....X"
" ......X.......X..X..X....X....X"
" ..............................X"
" ..............................X"
" ......XXXX......X..X..X.......X"
" ......X.........X.....X.......X"
" ......X......XX.X..X.XXX......X"
" ......X.....X..XX..X..X.......X"
" ......XXXX..X...X..X..X.......X"
" ......X.....X...X..X..X.......X"
" ......X.....X...X..X..X.......X"
" ......X.....X..XX..X..X.......X"
" ......XXXX...XX.X..X..XX......X"
" ..............................X"
" ..............................X"
" XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX"))


(define icon-rec-pane (list
"32 25 4 1"
"       c white"
".      c blue"
"X      c black"
"o      c red"
"                                "
" ..............................X"
" ..............................X"
" ..............................X"
" ..............................X"
" ..............................X"
" ..ooooo....oooooo....oooo.....X"
" ..oooooo...oooooo...oo..oo....X"
" ..oo...oo..oo......oo....oo...X"
" ..oo...oo..oo......oo....oo...X"
" ..oo...oo..oo......oo.........X"
" ..oo...oo..oooooo..oo.........X"
" ..oooooo...oooooo..oo.........X"
" ..oo..oo...oo......oo.........X"
" ..oo...oo..oo......oo.........X"
" ..oo...oo..oo......oo....oo...X"
" ..oo...oo..oooooo...oo..oo....X"
" ..oo...oo..oooooo....oooo.....X"
" ..............................X"
" ..............................X"
" ..............................X"
" ..............................X"
" ..............................X"
" ..............................X"
" XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX"))

(define icon-undo-it (list
"32 25 3 1"
"       c white"
".      c antiquewhite"
"X      c black"
"                                "
" ..............................X"
" ..............................X"
" ..............................X"
" ..............................X"
" ..............................X"
" ..............................X"
" ..............................X"
" .X....X.X....X.XXXX.....XXX...X"
" .X....X.XX...X.X...X...X...X..X"
" .X....X.X.X..X.X....X.X.....X.X"
" .X....X.X..X.X.X....X.X.....X.X"
" .X....X.X...XX.X....X.X.....X.X"
" .X....X.X....X.X....X.X.....X.X"
" .X....X.X....X.X....X.X.....X.X"
" ..X..X..X....X.X...X...X...X..X"
" ...XX...X....X.XXXX.....XXX...X"
" ..............................X"
" ..............................X"
" ..............................X"
" ..............................X"
" ..............................X"
" ..............................X"
" ..............................X"
" XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX"))

(define icon-redo-it (list
"32 25 3 1"
"       c white"
"X      c antiquewhite"
".      c black"
"                                "
" ..............................X"
" ..............................X"
" ..............................X"
" ..............................X"
" ..............................X"
" ..............................X"
" ..............................X"
" .XXXXX..XXXXXX.XXXX.....XXX...X"
" .X....X.X......X...X...X...X..X"
" .X....X.X......X....X.X.....X.X"
" .X....X.X......X....X.X.....X.X"
" .XXXXX..XXXXX..X....X.X.....X.X"
" .X.X....X......X....X.X.....X.X"
" .X..X...X......X....X.X.....X.X"
" .X...X..X......X...X...X...X..X"
" .X....X.XXXXXX.XXXX.....XXX...X"
" ..............................X"
" ..............................X"
" ..............................X"
" ..............................X"
" ..............................X"
" ..............................X"
" ..............................X"
" XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX"))


(define icon-exit-it (list
"32 25 4 1"
"       c white"
".      c black"
"X      c grey"
"O      c red"
"                                "
" ..............................X"
" ..............................X"
" ..............................X"
" ..............................X"
" ..............................X"
" ..............................X"
" ..............................X"
" .OOOOOO.OO.....OO.OOOO.OOOOOO.X"
" .OOOOOO..OO...OO...OO....OO...X"
" .O........OO.OO....OO....OO...X"
" .O.........OOO.....OO....OO...X"
" .OOOOO......O......OO....OO...X"
" .O.........OOO.....OO....OO...X"
" .O........OO.OO....OO....OO...X"
" .OOOOOO..OO...OO...OO....OO...X"
" .OOOOOO.OO.....OO.OOOO...OO...X"
" ..............................X"
" ..............................X"
" ..............................X"
" ..............................X"
" ..............................X"
" ..............................X"
" ..............................X"
" XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX"))

(define icon-full-go (list
"32 25 4 1"
"X      c white"
"       c grey"
".      c black"
"o      c darkgreen"
"XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX"
"                                "
"                                "
"                                "
"                                "
"    .......................     "
"   .ooooooooooooooooooooooo.    "
"  .ooooooooooooooooooooooooo.   "
" .ooooooXXXXooooooXXXoooooooo.  "
".ooooooXooooXooooXoooXoooooooo. "
".oooooXoooooooooXoooooXooooooo. "
".oooooXoooooooooXoooooXooooooo. "
".oooooXoooXXXXooXoooooXooooooo. "
".oooooXooooooXooXoooooXooooooo. "
".oooooXooooooXooXoooooXooooooo. "
".ooooooXooooXooooXoooXoooooooo. "
" .ooooooXXXXooooooXXXoooooooo.  "
"  .ooooooooooooooooooooooooo.   "
"   .ooooooooooooooooooooooo.    "
"    .......................     "
"                                "
"                                "
"                                "
"                                "
"................................"))


(define icon-play-direction-forward (list
"32 25 4 1"
"       c grey"
".      c black"
"x      c white"
"X      c lightgrey"
"xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"
"                                "
"                                "
"                                "
"                                "
"        X              .        "
"       XX              ..       "
"      XXX              ...      "
"     XXXX              ....     "
"    XXXXX              .....    "
"   XXXXXX              ......   "
"  XXXXXXXXXXXXX  .............  "
"   XXXXXX              ......   "
"    XXXXX              .....    "
"     XXXX              ....     "
"      XXX              ...      "
"       XX              ..       "
"        X              .        "
"                                "
"                                "
"                                "
"                                "
"                                "
"                                "
"................................"))


(define icon-play-direction-backward (list
"32 25 4 1"
"       c grey"
".      c black"
"x      c white"
"X      c lightgrey"
"xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"
"                                "
"                                "
"                                "
"                                "
"        .              X        "
"       ..              XX       "
"      ...              XXX      "
"     ....              XXXX     "
"    .....              XXXXX    "
"   ......              XXXXXX   "
"  .............  XXXXXXXXXXXXX  "
"   ......              XXXXXX   "
"    .....              XXXXX    "
"     ....              XXXX     "
"      ...              XXX      "
"       ..              XX       "
"        .              X        "
"                                "
"                                "
"                                "
"                                "
"                                "
"                                "
"................................"))

(define icon-loop-play (list
"32 25 11 1"

". c black"
"# c #00007f"
"a c #0000ff"
"b c #505850"
"c c #7f7f7f"
"d c orange"
"e c #dfdfdf"
"f c #ffff00"
"g c #ffffff"
"X c white"
"x c black"

"XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX"
"dddddddddddddddddddddddddddddddd"
"dddddddddddddddddddddddddddddddd"
"dddddddddddggggggggggddddddddddd"
"ddddddddddg..........cdddddddddd"
"dddddddddg.cccccccccc.cddddddddd"
"ddddddddg.cddddddddddg.cdddddddd"
"ddddddddg.cddddddddddg.cdddddddd"
"ddddddddg.c.dddddddddg.cdddddddd"
"ddddddg.c.c.ddddddddg...dddddddd"
"ddddddg.....ddddddddg...cddddddd"
"ddddddg.....dddddddg.....ddddddd"
"dddddddg...ddddddddg.....ddddddd"
"dddddddg...ddddddddg.c.c.ddddddd"
"ddddddddg.cddddddddddc.cdddddddd"
"ddddddddg.cddddddddddg.cdddddddd"
"ddddddddg.cddddddddddg.cdddddddd"
"ddddddddg.cddddddddddg.cdddddddd"
"dddddddddc.ddddddddgg.cddddddddd"
"ddddddddddc..........cdddddddddd"
"ddddddddddddcccccccccddddddddddd"
"dddddddddddddddddddddddddddddddd"
"dddddddddddddddddddddddddddddddd"
"dddddddddddddddddddddddddddddddd"
"xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"))


(define icon-loop-stop (list
"32 25 11 1"

". c black"
"# c #00007f"
"a c #0000ff"
"b c #505850"
"c c #7f7f7f"
"d c red"
"e c #dfdfdf"
"f c #ffff00"
"g c #ffffff"
"X c white"
"x c black"

"XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX"
"dddddddddddddddddddddddddddddddd"
"dddXXddddddddddddddddddddXXddddd"
"ddddXXddddddddddddddddddXXdddddd"
"dddddXXddddggggggggggddXXddddddd"
"ddddddXXddg..........cXXdddddddd"
"dddddddXXg.ccccccccccXXddddddddd"
"ddddddddXXcdddddddddXX.cdddddddd"
"ddddddddgXXddddddddXXg.cdddddddd"
"ddddddddg.XXddddddXXdg.cdddddddd"
"ddddddg.c.cXXddddXXdg...dddddddd"
"ddddddg.....XXddXXddg...cddddddd"
"ddddddg.....dXXXXddg.....ddddddd"
"dddddddg...dddXXdddg.....ddddddd"
"dddddddg...ddXXXXddg.c.c.ddddddd"
"ddddddddg.cdXXddXXdddc.cdddddddd"
"ddddddddg.cXXddddXXddg.cdddddddd"
"ddddddddg.XXddddddXXdg.cdddddddd"
"ddddddddgXXddddddddXXg.cdddddddd"
"ddddddddXX.ddddddddgXXcddddddddd"
"dddddddXXdc..........XXddddddddd"
"ddddddXXddddcccccccccdXXdddddddd"
"dddddXXddddddddddddddddXXddddddd"
"ddddXXddddddddddddddddddXXdddddd"
"xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"))






(define icon-full-stop (list
"32 25 4 1"
"X      c white"
"       c grey"
".      c black"
"o      c red"
"XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX"
"                                "
"                                "
"                                "
"                                "
"    .......................     "
"   .ooooooooooooooooooooooo.    "
"  .ooooooooooooooooooooooooo.   "
" .ooXXXooXXXXXooXXXoooXXXXXoo.  "
".ooXoooXoooXoooXoooXooXooooXoo. "
".oXooooooooXooXoooooXoXoooooXo. "
".ooXoooooooXooXoooooXoXooooXoo. "
".oooXXXooooXooXoooooXoXXXXXooo. "
".ooooooXoooXooXoooooXoXooooooo. "
".oooooooXooXooXoooooXoXooooooo. "
".ooXoooXoooXoooXoooXooXooooooo. "
" .ooXXXooooXooooXXXoooXoooooo.  "
"  .ooooooooooooooooooooooooo.   "
"   .ooooooooooooooooooooooo.    "
"    .......................     "
"                                "
"                                "
"                                "
"                                "
"................................"))


(define icon-open-file (list
"32 25 4 1"
"x      c white"
"       c lightslategrey"
".      c black"
"o      c yellow"
"xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"
"                                "
"                                "
"                                "
"                                "
"                                "
"                                "
"         ...........            "
"        .ooooooooooo.           "
"        .oooooooooooo.....      "
"        .oooooooooooooooo.      "
"      ....................      "
"      .oooooooooooooooo...      "
"       .oooooooooooooooo..      "
"       .oooooooooooooooo..      "
"        .oooooooooooooooo.      "
"         .ooooooooooooooo.      "
"          ................      "
"                                "
"                                "
"                                "
"                                "
"                                "
"                                "
"................................"))


(define icon-close-file (list
"32 25 4 1"
"       c white"
".      c lightslategrey"
"X      c black"
"o      c yellow"
"                                "
" ..............................X"
" ..............................X"
" ..............................X"
" ..............................X"
" ..............................X"
" ..............................X"
" .........XXXXXX...............X"
" ........XooooooX..............X"
" .......XXXXXXXXXXXXXXXX.......X"
" .......XooooooooooooooX.......X"
" .......XooooooooooooooX.......X"
" .......XooooooooooooooX.......X"
" .......XooooooooooooooX.......X"
" .......XooooooooooooooX.......X"
" .......XooooooooooooooX.......X"
" .......XooooooooooooooX.......X"
" .......XooooooooooooooX.......X"
" .......XXXXXXXXXXXXXXXX.......X"
" ..............................X"
" ..............................X"
" ..............................X"
" ..............................X"
" ..............................X"
" XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX"))

(define icon-start-of-window (list
"32 25 3 1"
"       c lightblue"
".      c black"
"x      c white"
"xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"
"                                "
"                                "
"                                "
"                                "
"               .        .       "
"              ..       ..       "
"             ...      ...       "
"            ....     ....       "
"           .....    .....       "
"         .......  .......       "
"       ..................       "
"         .......  .......       "
"           .....    .....       "
"            ....     ....       "
"             ...      ...       "
"              ..       ..       "
"               .        .       "
"                                "
"                                "
"                                "
"                                "
"                                "
"                                "
"................................"))

(define icon-mid-window (list
"32 25 3 1"
"       c lightblue"
".      c black"
"x      c white"
"xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"
"                                "
"                                "
"                                "
"                                "
"       .                .       "
"       ..              ..       "
"       ...            ...       "
"       ....          ....       "
"       .....        .....       "
"       .......    .......       "
"       ..................       "
"       .......    .......       "
"       .....        .....       "
"       ....          ....       "
"       ...            ...       "
"       ..              ..       "
"       .                .       "
"                                "
"                                "
"                                "
"                                "
"                                "
"                                "
"................................"))


(define icon-end-of-window (list
"32 25 3 1"
"       c lightblue"
".      c black"
"x      c white"
"xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"
"                                "
"                                "
"                                "
"                                "
"       .        .               "
"       ..       ..              "
"       ...      ...             "
"       ....     ....            "
"       .....    .....           "
"       .......  .......         "
"       ..................       "
"       .......  .......         "
"       .....    .....           "
"       ....     ....            "
"       ...      ...             "
"       ..       ..              "
"       .        .               "
"                                "
"                                "
"                                "
"                                "
"                                "
"                                "
"................................"))

(define icon-start-of-file (list
"32 25 3 1"
"       c lightblue"
".      c black"
"x      c white"
"xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"
"                                "
"                                "
"                                "
"                                "
"     ..        .        .       "
"     ..       ..       ..       "
"     ..      ...      ...       "
"     ..     ....     ....       "
"     ..    .....    .....       "
"     ..  .......  .......       "
"     ....................       "
"     ..  .......  .......       "
"     ..    .....    .....       "
"     ..     ....     ....       "
"     ..      ...      ...       "
"     ..       ..       ..       "
"     ..        .        .       "
"                                "
"                                "
"                                "
"                                "
"                                "
"                                "
"................................"))


(define icon-end-of-file (list
"32 25 3 1"
"       c lightblue"
".      c black"
"x      c white"
"xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"
"                                "
"                                "
"                                "
"                                "
"       .        .        ..     "
"       ..       ..       ..     "
"       ...      ...      ..     "
"       ....     ....     ..     "
"       .....    .....    ..     "
"       .......  .......  ..     "
"       ....................     "
"       .......  .......  ..     "
"       .....    .....    ..     "
"       ....     ....     ..     "
"       ...      ...      ..     "
"       ..       ..       ..     "
"       .        .        ..     "
"                                "
"                                "
"                                "
"                                "
"                                "
"                                "
"................................"))

(define icon-forward-one-sample (list
"32 25 3 1"
"       c lightblue"
".      c black"
"x      c white"
"xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"
"                                "
"                                "
"                                "
"                                "
"       .           ..           "
"       ..         ...           "
"       ...       ....           "
"       ....        ..           "
"       .....       ..           "
"       .......     ..           "
"       .........   ..           "
"       .......     ..           "
"       .....       ..           "
"       ....        ..           "
"       ...         ..           "
"       ..        ......         "
"       .         ......         "
"                                "
"                                "
"                                "
"                                "
"                                "
"                                "
"................................"))

(define icon-back-one-sample (list
"32 25 3 1"
"       c lightblue"
".      c black"
"x      c white"
"xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"
"                                "
"                                "
"                                "
"                                "
"            ..           .      "
"           ...          ..      "
"          ....         ...      "
"            ..        ....      "
"            ..       .....      "
"            ..     .......      "
"            ..   .........      "
"            ..     .......      "
"            ..       .....      "
"            ..        ....      "
"            ..         ...      "
"          ......        ..      "
"          ......         .      "
"                                "
"                                "
"                                "
"                                "
"                                "
"                                "
"................................"))

(define icon-forward-one-window (list
"32 25 3 1"
"       c lightblue"
".      c black"
"x      c white"
"xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"
"                                "
"                                "
"                                "
"                                "
"       .                        "
"       ..                       "
"       ...         ............ "
"       ....        ..         . "
"       .....       ..         . "
"       .......     ..         . "
"       .........   ..         . "
"       .......     ..         . "
"       .....       ..         . "
"       ....        ..         . "
"       ...         ............ "
"       ..                       "
"       .                        "
"                                "
"                                "
"                                "
"                                "
"                                "
"                                "
"................................"))


(define icon-back-one-window (list
"32 25 3 1"
"       c lightblue"
".      c black"
"x      c white"
"xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"
"                                "
"                                "
"                                "
"                                "
"                         .      "
"                        ..      "
" .............         ...      "
" .          ..        ....      "
" .          ..       .....      "
" .          ..     .......      "
" .          ..   .........      "
" .          ..     .......      "
" .          ..       .....      "
" .          ..        ....      "
" .............         ...      "
"                        ..      "
"                         .      "
"                                "
"                                "
"                                "
"                                "
"                                "
"                                "
"................................"))


(define icon-next-mix-point (list
"32 25 4 1"
"       c lightblue"
"x      c white"
".      c black"
"X      c black"
"xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"
"                                "
"                   XX     XX    "
"                   X X   X X    "
"                   X  X X  X    "
"       .           X   X   X    "
"       ..          X       X    "
"       ...         X       X    "
"       ....        X       X    "
"       .....          XXX       "
"       .......         X        "
"       .........       X        "
"       .......         X        "
"       .....           X        "
"       ....            X        "
"       ...            XXX       "
"       ..          XX     XX    "
"       .             X   X      "
"                      X X       "
"                       X        "
"                      X X       "
"                     X   X      "
"                   XX     XX    "
"                                "
"................................"))


(define icon-last-mix-point (list
"32 25 4 1"
"       c lightblue"
"x      c white"
".      c black"
"X      c black"
"xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"
"                                "
"     XX     XX                  "
"     X X   X X                  "
"     X  X X  X                  "
"     X   X   X           .      "
"     X       X          ..      "
"     X       X         ...      "
"     X       X        ....      "
"        XXX          .....      "
"         X         .......      "
"         X       .........      "
"         X         .......      "
"         X           .....      "
"         X            ....      "
"        XXX            ...      "
"     XX     XX          ..      "
"       X   X             .      "
"        X X                     "
"         X                      "
"        X X                     "
"       X   X                    "
"     XX     XX                  "
"                                "
"................................"))


(define icon-mixer (list
"32 25 5 1"
"       c white"
".      c grey"
"X      c black"
"o      c darkgrey"
"O      c yellow"
"                                "
" ..............................X"
" ..............................X"
" ..............................X"
" ...ooo...ooo...ooo......ooo...X"
" ...ooo...ooo...ooo......ooo...X"
" ...ooo...ooo...ooo......ooo...X"
" ...oXo...oXo.XXXXXXX....ooo...X"
" ...oXo...oXo.XOOOOOX..XXXXXXX.X"
" ...oXo...oXo.XXXXXXX..XOOOOOX.X"
" .XXXXXXX.oXo...oXo....XXXXXXX.X"
" .XOOOOOX.oXo...oXo......oXo...X"
" .XXXXXXX.oXo...oXo......oXo...X"
" ...oXo...oXo...oXo......oXo...X"
" ...oXo.XXXXXXX.oXo......oXo...X"
" ...oXo.XOOOOOX.oXo......oXo...X"
" ...oXo.XXXXXXX.oXo......oXo...X"
" ...oXo...oXo...oXo......oXo...X"
" ...ooo...ooo...ooo......oXo...X"
" ...ooo...ooo...ooo......ooo...X"
" ...ooo...ooo...ooo......ooo...X"
" ..............................X"
" ..............................X"
" ..............................X"
" XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX"))

(define icon-zooming-in (list
"32 25 4 1"
"       c lightblue"
".      c black"
"x      c white"
"X	c black"
"xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"
"                                "
"                                "
"        XXXXXXXXXXX             "
"       X           X            "
"      X      X      X           "
"     X       X       X          "
"     X       X       X          "
"     X   XXXXXXXXX   X          "
"     X       X       X          "
"     X       X       X          "
"      X      X      X           "
"       X           X            "
"        XXXXXXXXXXX             "
"                 XX             "
"                  XX            "
"                   XX           "
"                    XX          "
"                     XX         "
"                      XX        "
"                       XX       "
"                        XX      "
"                         XX     "
"                                "
"................................"))

(define icon-zooming-out (list
"32 25 4 1"
"       c lightblue"
".      c black"
"x      c white"
"X	c black"
"xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"
"                                "
"                                "
"        XXXXXXXXXXX             "
"       X           X            "
"      X             X           "
"     X               X          "
"     X               X          "
"     X   XXXXXXXXX   X          "
"     X               X          "
"     X               X          "
"      X             X           "
"       X           X            "
"        XXXXXXXXXXX             "
"                 XX             "
"                  XX            "
"                   XX           "
"                    XX          "
"                     XX         "
"                      XX        "
"                       XX       "
"                        XX      "
"                         XX     "
"                                "
"................................"))


(define icon-open-mix-file (list
"32 25 5 1"
"x      c white"
"       c lightslategrey"
".      c black"
"o      c yellow"
"X      c darkblue"
"xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"
"           XX     XX            "
"           X X   X X            "
"           X  X X  X            "
"           X   X   X            "
"           X       X            "
"           X       X            "
"         ..X.......X            "
"        .ooooooooooo.           "
"        .oooooXXXoooo.....      "
"        .ooooooXooooooooo.      "
"      .........X..........      "
"      .ooooooooXooooooo...      "
"       .oooooooXoooooooo..      "
"       .oooooooXoooooooo..      "
"        .oooooXXXoooooooo.      "
"         .ooooooooooooooo.      "
"          .XX.....XX......      "
"             X   X              "
"              X X               "
"               X                "
"              X X               "
"             X   X              "
"           XX     XX            "
"................................"))

