(if (not (defined? 'red)) (load-from-path "rgb.scm"))

(catch 'no-such-track
       (lambda ()
	 (set! (track-color (track 0)) red)
	 (set! (track-color (track 1)) orange)
	 (set! (track-color (track 2)) blue)
	 (set! (track-color (track 3)) white)
	 (set! (track-color (track 4)) gold)
	 (set! (track-color (track 5)) yellow4)
	 (set! (track-color (track 6)) antique-white)
	 (set! (track-color (track 7)) pink)
	 (set! (track-color (track 8)) orange-red)
	 (set! (track-color (track 9)) dark-salmon)
	 (set! (track-color (track 10)) coral)
	 (set! (track-color (track 11)) slateblue1)
	 (set! (track-color (track 12)) lightskyblue1)
	 (set! (track-color (track 13)) orchid)
	 (set! (track-color (track 14)) slategray1)
	 (set! (track-color (track 15)) rosy-brown)
	 (set! (track-color (track 16)) dark-sea-green)
	 (set! (track-color (track 17)) sandy-brown)
	 (set! (track-color (track 18)) tomato)
	 (set! (track-color (track 19)) plum)
	 (set! (track-color (track 20)) dark-orange)
	 (set! (track-color (track 21)) black)
	 (set! (track-color (track 22)) black)
	 (set! (track-color (track 23)) black)
	 (set! (track-color (track 24)) black)
	 (set! (track-color (track 25)) black)
	 (set! (track-color (track 26)) black)
	 (set! (track-color (track 27)) black)
	 (set! (track-color (track 28)) black)
	 (set! (track-color (track 29)) black)
	 (set! (track-color (track 30)) black)
	 (set! (track-color (track 31)) black)
	 (set! (track-color (track 32)) black)
	 (set! (track-color (track 33)) black)
	 (set! (track-color (track 34)) black)
	 (set! (track-color (track 35)) black)
	 (set! (track-color (track 36)) black)
	 (set! (track-color (track 37)) black)
	 (set! (track-color (track 38)) black)
	 (set! (track-color (track 39)) black)
	 (set! (track-color (track 40)) black)
	 (set! (track-color (track 41)) black)
	 (set! (track-color (track 42)) black)
	 (set! (track-color (track 43)) black)
	 (set! (track-color (track 44)) black)
	 (set! (track-color (track 45)) black))
       (lambda args #t))

	 
