(define save-as (list
"32 25 5 1"
"       c white"
".      c grey"
"X      c black"
"o      c blue"
"O      c red"
"                                "
" ..............................X"
" ..............................X"
" ..............................X"
" ..............................X"
" ..............................X"
" .......oooOOOOOOOOOOoo........X"
" .......oooOOOOOOOOOOoo........X"
" .......ooo          oo........X"
" .......ooo          oo........X"
" .......ooo          oo........X"
" .......ooooooooooooooo........X"
" .......ooooooooooooooo........X"
" .......ooooooooooooooo........X"
" .......ooo         ooo........X"
" .......ooo         ooo........X"
" .......ooo ooo     ooo........X"
" .......ooo ooo     ooo........X"
" ........oo ooo     ooo........X"
" ..............................X"
" ..............................X"
" ..............................X"
" ..............................X"
" ..............................X"
" XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX"))

(define env-edit (list
"32 25 4 1"
"       c white"
".      c grey"
"X      c black"
"o      c darkgrey"
"                                "
" ..............................X"
" ......XXXX....................X"
" ......X.......................X"
" ......X.......................X"
" ......X.......................X"
" ......XXXX..X.XX..X.....X.....X"
" ......X.....X...X..X...X......X"
" ......X.....X...X..X...X......X"
" ......X.....X...X...X.X.......X"
" ......XXXX..X...X....X........X"
" ..............................X"
" ..............................X"
" ......XXXX......X..X..X.......X"
" ......X.........X.....X.......X"
" ......X......XX.X..X.XXX......X"
" ......X.....X..XX..X..X.......X"
" ......XXXX..X...X..X..X.......X"
" ......X.....X...X..X..X.......X"
" ......X.....X...X..X..X.......X"
" ......X.....X..XX..X..X.......X"
" ......XXXX...XX.X..X..XX......X"
" ..............................X"
" ..............................X"
" XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX"))

(define regions-browser (list
"32 25 4 1"
"       c white"
".      c grey"
"X      c black"
"o      c darkgrey"
"                                "
" ..............................X"
" ......XXXX....................X"
" ......X...X...................X"
" ......X....X..................X"
" ......X...X...................X"
" ......XXXX.....XXXX...XXXX....X"
" ......X...X...X....X.X....X...X"
" ......X....X..XXXXX..X....X...X"
" ......X.....X..X.....X....X...X"
" ......X......X..XXXX..XXXXX...X"
" ..........................X...X"
" .......................XXX....X"
" ......XXXX......X..X..X.......X"
" ......X.........X.....X.......X"
" ......X......XX.X..X.XXX......X"
" ......X.....X..XX..X..X.......X"
" ......XXXX..X...X..X..X.......X"
" ......X.....X...X..X..X.......X"
" ......X.....X...X..X..X.......X"
" ......X.....X..XX..X..X.......X"
" ......XXXX...XX.X..X..XX......X"
" ..............................X"
" ..............................X"
" XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX"))

(define mix-pane (list
"32 25 4 1"
"       c white"
".      c grey"
"X      c black"
"o      c darkgrey"
"                                "
" ..............................X"
" ..............................X"
" ......XX.....XX..X............X"
" ......X.X...X.X...............X"
" ......X..X.X..X..X..X....X....X"
" ......X...X...X..X...X..X.....X"
" ......X.......X..X....XX......X"
" ......X.......X..X....XX......X"
" ......X.......X..X...X..X.....X"
" ......X.......X..X..X....X....X"
" ..............................X"
" ..............................X"
" ......XXXX......X..X..X.......X"
" ......X.........X.....X.......X"
" ......X......XX.X..X.XXX......X"
" ......X.....X..XX..X..X.......X"
" ......XXXX..X...X..X..X.......X"
" ......X.....X...X..X..X.......X"
" ......X.....X...X..X..X.......X"
" ......X.....X..XX..X..X.......X"
" ......XXXX...XX.X..X..XX......X"
" ..............................X"
" ..............................X"
" XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX"))


(define rec-pane (list
"32 25 4 1"
"       c white"
".      c grey"
"X      c black"
"o      c red"
"                                "
" ..............................X"
" ..............................X"
" ..............................X"
" ..............................X"
" ..............................X"
" ..............................X"
" ..............................X"
" ...ooooo...oooooo....oooo.....X"
" ...o....o..o........o....o....X"
" ...o....o..o.......o..........X"
" ...o....o..o.......o..........X"
" ...ooooo...oooooo..o..........X"
" ...o...o...o.......o..........X"
" ...o....o..o.......o..........X"
" ...o....o..o........o....o....X"
" ...o....o..oooooo....oooo.....X"
" ..............................X"
" ..............................X"
" ..............................X"
" ..............................X"
" ..............................X"
" ..............................X"
" ..............................X"
" XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX"))

(define undo-it (list
"32 25 3 1"
"       c white"
".      c grey"
"X      c black"
"                                "
" ..............................X"
" ..............................X"
" ..............................X"
" ..............................X"
" ..............................X"
" ..............................X"
" ..............................X"
" .X....X.X....X.XXXX.....XXX...X"
" .X....X.XX...X.X...X...X...X..X"
" .X....X.X.X..X.X....X.X.....X.X"
" .X....X.X..X.X.X....X.X.....X.X"
" .X....X.X...XX.X....X.X.....X.X"
" .X....X.X....X.X....X.X.....X.X"
" .X....X.X....X.X....X.X.....X.X"
" ..X..X..X....X.X...X...X...X..X"
" ...XX...X....X.XXXX.....XXX...X"
" ..............................X"
" ..............................X"
" ..............................X"
" ..............................X"
" ..............................X"
" ..............................X"
" ..............................X"
" XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX"))

(define exit-it (list
"32 25 4 1"
"       c white"
".      c grey"
"X      c black"
"O      c red"
"                                "
" ..............................X"
" ..............................X"
" ..............................X"
" ..............................X"
" ..............................X"
" ..............................X"
" ..............................X"
" ..OOOOOO.O.......O.OOO.OOOOO..X"
" ..O.......O.....O...O....O....X"
" ..O........O...O....O....O....X"
" ..O.........O.O.....O....O....X"
" ..OOOOO......O......O....O....X"
" ..O.........O.O.....O....O....X"
" ..O........O...O....O....O....X"
" ..O.......O.....O...O....O....X"
" ..OOOOOO.O.......O.OOO...O....X"
" ..............................X"
" ..............................X"
" ..............................X"
" ..............................X"
" ..............................X"
" ..............................X"
" ..............................X"
" XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX"))

(define full-go (list
"32 25 4 1"
"X      c white"
"       c grey"
".      c black"
"o      c darkgreen"
"XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX"
"                                "
"                                "
"                                "
"                                "
"    .......................     "
"   .ooooooooooooooooooooooo.    "
"  .ooooooooooooooooooooooooo.   "
" .ooooooXXXXoooooXXXoooXooooo.  "
".ooooooXooooXoooXoooXooXoooooo. "
".oooooXooooooooXoooooXoXoooooo. "
".oooooXooooooooXoooooXoXoooooo. "
".oooooXoooXXXXoXoooooXoXoooooo. "
".oooooXooooooXoXoooooXoXoooooo. "
".oooooXooooooXoXoooooXoXoooooo. "
".ooooooXooooXoooXoooXooooooooo. "
" .ooooooXXXXoooooXXXoooXooooo.  "
"  .ooooooooooooooooooooooooo.   "
"   .ooooooooooooooooooooooo.    "
"    .......................     "
"                                "
"                                "
"                                "
"                                "
"................................"))





(define full-stop (list
"32 25 4 1"
"X      c white"
"       c grey"
".      c black"
"o      c red"
"XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX"
"                                "
"                                "
"                                "
"                                "
"    .......................     "
"   .ooooooooooooooooooooooo.    "
"  .ooooooooooooooooooooooooo.   "
" .ooXXXooXXXXXooXXXoooXXXXXoo.  "
".ooXoooXoooXoooXoooXooXooooXoo. "
".oXooooooooXooXoooooXoXoooooXo. "
".ooXoooooooXooXoooooXoXooooXoo. "
".oooXXXooooXooXoooooXoXXXXXooo. "
".ooooooXoooXooXoooooXoXooooooo. "
".oooooooXooXooXoooooXoXooooooo. "
".ooXoooXoooXoooXoooXooXooooooo. "
" .ooXXXooooXooooXXXoooXoooooo.  "
"  .ooooooooooooooooooooooooo.   "
"   .ooooooooooooooooooooooo.    "
"    .......................     "
"                                "
"                                "
"                                "
"                                "
"................................"))


(define open-file (list
"32 25 4 1"
"x      c white"
"       c grey"
".      c black"
"o      c yellow"
"xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"
"                                "
"                                "
"                                "
"                                "
"                                "
"                                "
"         ...........            "
"        .ooooooooooo.           "
"        .oooooooooooo.....      "
"        .oooooooooooooooo.      "
"      ....................      "
"      .oooooooooooooooo...      "
"       .oooooooooooooooo..      "
"       .oooooooooooooooo..      "
"        .oooooooooooooooo.      "
"         .ooooooooooooooo.      "
"          ................      "
"                                "
"                                "
"                                "
"                                "
"                                "
"                                "
"................................"))


(define close-file (list
"32 25 4 1"
"       c white"
".      c grey"
"X      c black"
"o      c yellow"
"                                "
" ..............................X"
" ..............................X"
" ..............................X"
" ..............................X"
" ..............................X"
" ..............................X"
" .........XXXXXX...............X"
" ........XooooooX..............X"
" .......XXXXXXXXXXXXXXXX.......X"
" .......XooooooooooooooX.......X"
" .......XooooooooooooooX.......X"
" .......XooooooooooooooX.......X"
" .......XooooooooooooooX.......X"
" .......XooooooooooooooX.......X"
" .......XooooooooooooooX.......X"
" .......XooooooooooooooX.......X"
" .......XooooooooooooooX.......X"
" .......XXXXXXXXXXXXXXXX.......X"
" ..............................X"
" ..............................X"
" ..............................X"
" ..............................X"
" ..............................X"
" XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX"))

(define start-of-window (list
"32 25 3 1"
"       c grey"
".      c black"
"x      c white"
"xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"
"                                "
"                                "
"                                "
"                                "
"               .        .       "
"              ..       ..       "
"             ...      ...       "
"            ....     ....       "
"           .....    .....       "
"         .......  .......       "
"       ..................       "
"         .......  .......       "
"           .....    .....       "
"            ....     ....       "
"             ...      ...       "
"              ..       ..       "
"               .        .       "
"                                "
"                                "
"                                "
"                                "
"                                "
"                                "
"................................"))

(define mid-window (list
"32 25 3 1"
"       c grey"
".      c black"
"x      c white"
"xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"
"                                "
"                                "
"                                "
"                                "
"       .                .       "
"       ..              ..       "
"       ...            ...       "
"       ....          ....       "
"       .....        .....       "
"       .......    .......       "
"       ..................       "
"       .......    .......       "
"       .....        .....       "
"       ....          ....       "
"       ...            ...       "
"       ..              ..       "
"       .                .       "
"                                "
"                                "
"                                "
"                                "
"                                "
"                                "
"................................"))


(define end-of-window (list
"32 25 3 1"
"       c grey"
".      c black"
"x      c white"
"xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"
"                                "
"                                "
"                                "
"                                "
"       .        .               "
"       ..       ..              "
"       ...      ...             "
"       ....     ....            "
"       .....    .....           "
"       .......  .......         "
"       ..................       "
"       .......  .......         "
"       .....    .....           "
"       ....     ....            "
"       ...      ...             "
"       ..       ..              "
"       .        .               "
"                                "
"                                "
"                                "
"                                "
"                                "
"                                "
"................................"))

(define start-of-file (list
"32 25 3 1"
"       c grey"
".      c black"
"x      c white"
"xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"
"                                "
"                                "
"                                "
"                                "
"     ..        .        .       "
"     ..       ..       ..       "
"     ..      ...      ...       "
"     ..     ....     ....       "
"     ..    .....    .....       "
"     ..  .......  .......       "
"     ....................       "
"     ..  .......  .......       "
"     ..    .....    .....       "
"     ..     ....     ....       "
"     ..      ...      ...       "
"     ..       ..       ..       "
"     ..        .        .       "
"                                "
"                                "
"                                "
"                                "
"                                "
"                                "
"................................"))


(define end-of-file (list
"32 25 3 1"
"       c grey"
".      c black"
"x      c white"
"xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"
"                                "
"                                "
"                                "
"                                "
"       .        .        ..     "
"       ..       ..       ..     "
"       ...      ...      ..     "
"       ....     ....     ..     "
"       .....    .....    ..     "
"       .......  .......  ..     "
"       ....................     "
"       .......  .......  ..     "
"       .....    .....    ..     "
"       ....     ....     ..     "
"       ...      ...      ..     "
"       ..       ..       ..     "
"       .        .        ..     "
"                                "
"                                "
"                                "
"                                "
"                                "
"                                "
"................................"))

(define forward-one-sample (list
"32 25 3 1"
"       c grey"
".      c black"
"x      c white"
"xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"
"                                "
"                                "
"                                "
"                                "
"       .           ..           "
"       ..         ...           "
"       ...       ....           "
"       ....        ..           "
"       .....       ..           "
"       .......     ..           "
"       .........   ..           "
"       .......     ..           "
"       .....       ..           "
"       ....        ..           "
"       ...         ..           "
"       ..        ......         "
"       .         ......         "
"                                "
"                                "
"                                "
"                                "
"                                "
"                                "
"................................"))

(define back-one-sample (list
"32 25 3 1"
"       c grey"
".      c black"
"x      c white"
"xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"
"                                "
"                                "
"                                "
"                                "
"            ..           .      "
"           ...          ..      "
"          ....         ...      "
"            ..        ....      "
"            ..       .....      "
"            ..     .......      "
"            ..   .........      "
"            ..     .......      "
"            ..       .....      "
"            ..        ....      "
"            ..         ...      "
"          ......        ..      "
"          ......         .      "
"                                "
"                                "
"                                "
"                                "
"                                "
"                                "
"................................"))

(define forward-one-window (list
"32 25 3 1"
"       c grey"
".      c black"
"x      c white"
"xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"
"                                "
"                                "
"                                "
"                                "
"       .                        "
"       ..                       "
"       ...         ............ "
"       ....        ..         . "
"       .....       ..         . "
"       .......     ..         . "
"       .........   ..         . "
"       .......     ..         . "
"       .....       ..         . "
"       ....        ..         . "
"       ...         ............ "
"       ..                       "
"       .                        "
"                                "
"                                "
"                                "
"                                "
"                                "
"                                "
"................................"))


(define back-one-window (list
"32 25 3 1"
"       c grey"
".      c black"
"x      c white"
"xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"
"                                "
"                                "
"                                "
"                                "
"                         .      "
"                        ..      "
" .............         ...      "
" .          ..        ....      "
" .          ..       .....      "
" .          ..     .......      "
" .          ..   .........      "
" .          ..     .......      "
" .          ..       .....      "
" .          ..        ....      "
" .............         ...      "
"                        ..      "
"                         .      "
"                                "
"                                "
"                                "
"                                "
"                                "
"                                "
"................................"))


(define mixer (list
"32 25 5 1"
"       c white"
".      c grey"
"X      c black"
"o      c darkgrey"
"O      c yellow"
"                                "
" ..............................X"
" ..............................X"
" ..............................X"
" ...ooo...ooo...ooo......ooo...X"
" ...ooo...ooo...ooo......ooo...X"
" ...ooo...ooo...ooo......ooo...X"
" ...oXo...oXo.XXXXXXX....ooo...X"
" ...oXo...oXo.XOOOOOX..XXXXXXX.X"
" ...oXo...oXo.XXXXXXX..XOOOOOX.X"
" .XXXXXXX.oXo...oXo....XXXXXXX.X"
" .XOOOOOX.oXo...oXo......oXo...X"
" .XXXXXXX.oXo...oXo......oXo...X"
" ...oXo...oXo...oXo......oXo...X"
" ...oXo.XXXXXXX.oXo......oXo...X"
" ...oXo.XOOOOOX.oXo......oXo...X"
" ...oXo.XXXXXXX.oXo......oXo...X"
" ...oXo...oXo...oXo......oXo...X"
" ...ooo...ooo...ooo......oXo...X"
" ...ooo...ooo...ooo......ooo...X"
" ...ooo...ooo...ooo......ooo...X"
" ..............................X"
" ..............................X"
" ..............................X"
" XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX"))


