#!/bin/csh -f

# cp ~/dist/snd/snd.tar .
# tar xf snd.tar

# words I constantly missppelll
fgrep decrip *.html
fgrep accomoda *.html
fgrep pysical *.html
fgrep decrip *.c
fgrep accomoda *.c
fgrep decrip *.scm
fgrep accomoda *.scm
fgrep -e " #(" *.scm
fgrep -e "the the " *.c
fgrep -e "the the " *.html
fgrep udpate *.c
fgrep "if DEBUGGING" *.c
fgrep "(DEBUGGING)" *.c
fgrep udpate *.html
fgrep udpate *.scm
fgrep ";;" *.[ch]
va.scm
tools/check-gtk.scm

rm -f snd
rm -f config.cache

echo ' -------------------------------------------------------------------------------- '
echo ' ----                 basic configure test                                  ----- '
echo ' -------------------------------------------------------------------------------- '
./configure --quiet CFLAGS="-Wall -I/usr/X11R6/include" LDFLAGS="-L/usr/X11R6/lib" 
make allclean
make
echo ' '
echo ' '
make xm
echo ' '
echo ' '
./snd --version
./snd -noinit --features "'clm 'snd-guile 'snd-motif 'sndlib"
echo '(let ((hxm (dlopen (string-append (getcwd) "/xm.so")))) (dlinit hxm "Init_libxm") (display XmARROWS_END) (exit))' > tmp.scm
./snd tmp.scm
rm tmp.scm

echo ' -------------------------------- no strftime -------------------------------- '

sed mus-config.h -e 's/#define HAVE_STRFTIME 1/#define HAVE_STRFTIME 0/' > tmp
mv tmp mus-config.h
make

echo ' -------------------------------- no readlink -------------------------------- '

sed mus-config.h -e 's/#define HAVE_READLINK 1/#define HAVE_READLINK 0/' > tmp
mv tmp mus-config.h
make

echo ' -------------------------------- no getcwd -------------------------------- '

sed mus-config.h -e 's/#define HAVE_GETCWD 1/#define HAVE_GETCWD 0/' > tmp
mv tmp mus-config.h
make

echo ' -------------------------------- no lstat -------------------------------- '

sed mus-config.h -e 's/#define HAVE_LSTAT 1/#define HAVE_LSTAT 0/' > tmp
mv tmp mus-config.h
make

echo ' -------------------------------- no access -------------------------------- '

sed mus-config.h -e 's/#define HAVE_ACCESS 1/#define HAVE_ACCESS 0/' > tmp
mv tmp mus-config.h
make

echo ' -------------------------------- no strcasecmp -------------------------------- '

sed mus-config.h -e 's/#define HAVE_STRCASECMP 1/#define HAVE_STRCASECMP 0/' > tmp
mv tmp mus-config.h
make

echo ' -------------------------------- no snprintf -------------------------------- '

sed mus-config.h -e 's/#define HAVE_SNPRINTF 1/#define HAVE_SNPRINTF 0/' > tmp
mv tmp mus-config.h
make

make clmclean
make sndinfo
make audinfo
make sndplay
make sndrecord
make allclean

echo ' '
echo ' '
echo ' -------------------------------------------------------------------------------- '
echo ' -----                   GUILE_CONFIG_path=/home/bil/test/bin -Wdeclaration-after-statement -Wmissing-field-initializer ---- '
echo ' -------------------------------------------------------------------------------- '
./configure --quiet CFLAGS="-Wall -I/usr/X11R6/include -D_FORTIFY_SOURCE" LDFLAGS="-L/usr/X11R6/lib" GUILE_CONFIG_path=/home/bil/test/bin
make
make xm
./snd --version
./snd -noinit --features "'clm 'sndlib 'snd 'snd-guile 'snd-motif"
echo '(let ((hxm (dlopen (string-append (getcwd) "/xm.so")))) (dlinit hxm "Init_libxm") (display XmARROWS_END) (exit))' > tmp.scm
./snd tmp.scm
rm tmp.scm
make allclean

echo ' '
echo ' '
echo ' -------------------------------------------------------------------------------- '
echo ' ----                 --enable-snd-debug g++                                ----  '
echo ' -------------------------------------------------------------------------------- '
./configure --quiet --enable-snd-debug CC=g++ CFLAGS="-Wall -I/usr/X11R6/include" LDFLAGS="-L/usr/X11R6/lib" 
make
make xm
./snd --version
./snd -noinit --features "'clm 'snd-debug"

make allclean
rm -f snd
rm -f config.cache

echo ' '
echo ' '
echo ' -------------------------------------------------------------------------------- '
echo ' -----                --with-no-gui                                         ----  '
echo ' -------------------------------------------------------------------------------- '
./configure --quiet LDFLAGS="-L/usr/X11R6/lib" CFLAGS="-Wall -I/usr/X11R6/include" --with-no-gui
make
echo ' '
echo ' '
./snd --version
./snd -noinit --features "'clm 'snd-nogui"

make allclean
rm -f snd
rm -f config.cache

echo ' '
echo ' '
echo ' -------------------------------------------------------------------------------- '
echo ' ----                 -with-no-gui --without-ladspa                         ----  '
echo ' -------------------------------------------------------------------------------- '
./configure --quiet LDFLAGS="-L/usr/X11R6/lib" CFLAGS="-Wall -I/usr/X11R6/include" --with-no-gui --without-ladspa
make
echo ' '
echo ' '
./snd --version
./snd -noinit --features "'clm 'snd-nogui"

make allclean
rm -f snd
rm -f config.cache

echo ' '
echo ' '
echo ' -------------------------------------------------------------------------------- '
echo ' ----                --with-gtk                                             ----  '
echo ' -------------------------------------------------------------------------------- '
./configure --quiet LDFLAGS="-L/usr/X11R6/lib" CFLAGS="-Wall -I/usr/X11R6/include" --with-gtk
make
echo ' '
echo ' '
./snd --version
./snd -noinit --features "'clm 'snd-gtk"

echo ' -------------------------------------------------------------------------------- '
echo ' ----                 --with-gtk --with-cairo                               ----  '
echo ' -------------------------------------------------------------------------------- '
./configure --quiet LDFLAGS="-L/usr/X11R6/lib" CFLAGS="-Wall -I/usr/X11R6/include" --with-gtk --with-cairo
make
echo ' '
echo ' '
./snd --version
./snd -noinit --features "'clm 'snd-gtk"
make xg
echo '(let ((hxm (dlopen (string-append (getcwd) "/xg.so")))) (dlinit hxm "Init_libxg") (display GTK_ARROW_UP) (exit))' > tmp.scm
./snd tmp.scm
rm tmp.scm
rm xg.o

echo ' '
echo ' '
echo ' -------------------------------------------------------------------------------- '
echo ' ----                 g++ --with-gtk --disable-deprecated                   ----  '
echo ' -------------------------------------------------------------------------------- '
./configure --quiet CC=g++ CFLAGS="-Wall -I/usr/X11R6/include" --with-gtk --disable-deprecated
make xg
make allclean
make
./snd --version
./snd -noinit --features "'clm 'snd-gtk"
make allclean

echo ' '
echo ' '
echo ' -------------------------------------------------------------------------------- '
echo ' -----                g++ --with-gtk                                         ---  '
echo ' -------------------------------------------------------------------------------- '
./configure --quiet CC=g++ --with-gtk CFLAGS="-Wall -I/usr/X11R6/include"
make
./snd --version
./snd -noinit --features "'clm 'snd-gtk"
make allclean

echo ' '
echo ' '
echo ' -------------------------------------------------------------------------------- '
echo ' ----                 g++ --with-gtk --without-builtin-gtkrc                 ---  '
echo ' -------------------------------------------------------------------------------- '
./configure --quiet --with-gtk --without-builtin-gtkrc CFLAGS="-Wall -I/usr/X11R6/include"
make
./snd --version
./snd -noinit --features "'clm 'snd-gtk"

make allclean
rm -f snd
rm -f config.cache

echo ' '
echo ' '
echo ' -------------------------------------------------------------------------------- '
echo ' ----                 --without-guile --without-ruby                        ----  '
echo ' -------------------------------------------------------------------------------- '
./configure LDFLAGS="-L/usr/X11R6/lib" CFLAGS="-I/usr/X11R6/include" --quiet --without-guile --without-ruby
make
echo ' '
echo ' '
./snd --version
make allclean

echo ' -------------------------------------------------------------------------------- '
echo ' -----                --without-guile --without-ruby --with-gtk             ----  '
echo ' -------------------------------------------------------------------------------- '
./configure --quiet --without-guile --without-ruby --with-gtk
make
echo ' '
echo ' '
./snd --version
rm -f sndinfo
make sndinfo
./sndinfo test.snd
make allclean

echo ' -------------------------------------------------------------------------------- '
echo ' ----                 --without-guile --without-ruby --with-gtk --with-cairo ---- '
echo ' -------------------------------------------------------------------------------- '
./configure --quiet --without-guile --without-ruby --with-gtk --with-cairo
make
echo ' '
echo ' '
./snd --version
make allclean

echo ' -------------------------------------------------------------------------------- '
echo ' ----                 --without-guile --without-ruby --with-gtk --with-gl ------  '
echo ' -------------------------------------------------------------------------------- '
./configure --quiet --without-guile --without-ruby --with-gtk --with-gl
make
echo ' '
echo ' '
./snd --version
make allclean

echo ' -------------------------------------------------------------------------------- '
echo ' ----                 --without-guile --without-ruby --with-just-gl       ------  '
echo ' -------------------------------------------------------------------------------- '
./configure LDFLAGS="-L/usr/X11R6/lib" CFLAGS="-I/usr/X11R6/include" --quiet --without-guile --without-ruby --with-just-gl
make
echo ' '
echo ' '
./snd --version

echo ' -------------------------------------------------------------------------------- '
echo ' -----                --without-guile --without-ruby g++                    ----  '
echo ' -------------------------------------------------------------------------------- '
./configure --quiet --without-guile --without-ruby CC=g++ LDFLAGS="-L/usr/X11R6/lib" CFLAGS="-I/usr/X11R6/include"
make
echo ' '
echo ' '
./snd --version
make allclean

echo ' '
echo ' '
echo ' -------------------------------------------------------------------------------- '
echo ' -----                --with-forth                                           ---- '
echo ' -------------------------------------------------------------------------------- '
./configure LDFLAGS="-L/usr/X11R6/lib" CFLAGS="-I/usr/X11R6/include" --quiet --with-forth
make
./snd --version
./snd -noinit --features "'clm 'snd-forth 'snd-motif"
make allclean

echo ' '
echo ' '
echo ' -------------------------------------------------------------------------------- '
echo ' -----                --with-forth --enable-snd-debug --with-static-xm --with-editres --with-gl ---- '
echo ' -------------------------------------------------------------------------------- '
./configure --quiet --with-forth --enable-snd-debug --with-static-xm --with-editres --with-gl LDFLAGS="-L/usr/X11R6/lib" CFLAGS="-Wall -I/usr/X11R6/include" --with-midi
make
./snd --version
./snd -noinit --features "'clm 'snd-forth 'xm 'gl"
make allclean

echo ' '
echo ' '
echo ' -------------------------------------------------------------------------------- '
echo ' -----                --with-forth --with-gtk --with-static-xg --with-gl      --- '
echo ' -------------------------------------------------------------------------------- '
./configure --quiet --with-forth --with-gtk --with-static-xg --with-gl LDFLAGS="-L/usr/X11R6/lib" CFLAGS="-Wall -I/usr/X11R6/include"
make
./snd --version
./snd -noinit --features "'clm 'snd-gtk 'xg 'gl"
make allclean

echo ' '
echo ' '
echo ' -------------------------------------------------------------------------------- '
echo ' -----                --with-gtk --with-cairo --with-static-xg                --- '
echo ' -------------------------------------------------------------------------------- '
./configure --quiet --with-gtk --with-static-xg --with-cairo LDFLAGS="-L/usr/X11R6/lib" CFLAGS="-Wall -I/usr/X11R6/include"
make
./snd --version
./snd -noinit --features "'clm 'snd-gtk 'xg 'gl"
make allclean

echo ' '
echo ' '
echo ' -------------------------------------------------------------------------------- '
echo ' -----                --with-forth --with-no-gui                              --- '
echo ' -------------------------------------------------------------------------------- '
./configure --quiet --with-forth --with-no-gui LDFLAGS="-L/usr/X11R6/lib" CFLAGS="-Wall -I/usr/X11R6/include"
make
./snd --version
./snd -noinit --features "'clm 'snd-forth 'snd-nogui"
make allclean

echo ' '
echo ' '
echo ' -------------------------------------------------------------------------------- '
echo ' ----                 --with-gauche                                          ---- '
echo ' -------------------------------------------------------------------------------- '
./configure LDFLAGS="-L/usr/X11R6/lib" CFLAGS="-I/usr/X11R6/include" --quiet --with-gauche
make
./snd --version
./snd -noinit --features "'clm 'snd-gauche 'snd-motif"
make allclean

echo ' '
echo ' '
echo ' -------------------------------------------------------------------------------- '
echo ' ----                 --with-gauche  API 0_8*                                ---- '
echo ' -------------------------------------------------------------------------------- '
./configure LDFLAGS="-L/usr/X11R6/lib" CFLAGS="-I/usr/X11R6/include -DGAUCHE_API_0_8_8 -DGAUCHE_API_0_8_10" --quiet --with-gauche
make
./snd --version
./snd -noinit --features "'clm 'snd-gauche 'snd-motif"
make allclean

echo ' '
echo ' '
echo ' -------------------------------------------------------------------------------- '
echo ' ----                 --with-gauche  API 0_9                                 ---- '
echo ' -------------------------------------------------------------------------------- '
./configure LDFLAGS="-L/usr/X11R6/lib" CFLAGS="-I/usr/X11R6/include -DGAUCHE_API_0_9" --quiet --with-gauche
make
./snd --version
./snd -noinit --features "'clm 'snd-gauche 'snd-motif"
make allclean

echo ' '
echo ' '
echo ' -------------------------------------------------------------------------------- '
echo ' ----                --with-gauche --enable-snd-debug --with-static-xm --with-editres --with-gl '
echo ' -------------------------------------------------------------------------------- '
./configure --quiet --with-gauche --enable-snd-debug --with-static-xm --with-editres --with-gl LDFLAGS="-L/usr/X11R6/lib" CFLAGS="-Wall -I/usr/X11R6/include" --with-midi
make
./snd --version
./snd -noinit --features "'clm 'snd-gauche 'xm 'gl"
make allclean

echo ' '
echo ' '
echo ' -------------------------------------------------------------------------------- '
echo ' ----                --with-gauche --with-gtk --with-static-xg --with-gl      --- '
echo ' -------------------------------------------------------------------------------- '
./configure --quiet --with-gauche --with-gtk --with-static-xg --with-gl LDFLAGS="-L/usr/X11R6/lib" CFLAGS="-Wall -I/usr/X11R6/include"
make
./snd --version
./snd -noinit --features "'clm 'snd-gtk 'xg 'gl"
make allclean

echo ' '
echo ' '
echo ' -------------------------------------------------------------------------------- '
echo ' -----                --with-gauche --with-no-gui                             --- '
echo ' -------------------------------------------------------------------------------- '
./configure --quiet --with-gauche --with-no-gui LDFLAGS="-L/usr/X11R6/lib" CFLAGS="-Wall -I/usr/X11R6/include"
make
./snd --version
./snd -noinit --features "'clm 'snd-gauche 'snd-nogui"
make allclean

echo ' '
echo ' '
echo ' -------------------------------------------------------------------------------- '
echo ' -----                --with-gauche g++ --disable-deprecated                  --- '
echo ' -------------------------------------------------------------------------------- '
./configure --quiet --with-gauche CC=g++ --disable-deprecated LDFLAGS="-L/usr/X11R6/lib" CFLAGS="-Wall -I/usr/X11R6/include"
make
./snd --version
./snd -noinit --features "'clm 'snd-gauche"
make allclean

echo ' '
make allclean
rm -f snd
rm -f config.cache

echo ' -------------------------------------------------------------------------------- '
echo ' ----                 --with-static-gsl --with-alsa --with-midi                -  '
echo ' -------------------------------------------------------------------------------- '
./configure --quiet LDFLAGS="-L/usr/X11R6/lib" CFLAGS="-Wall -I/usr/X11R6/include" --with-static-gsl --with-alsa --with-midi
make
echo ' '
echo ' '
./snd --version
./snd -noinit --features "'clm 'gsl 'alsa"

echo ' '
make allclean
rm -f snd
rm -f config.cache
rm -f makefile
rm -f mus-config.h
rm -f sndinfo

echo ' -------------------------------------------------------------------------------- '
echo ' -----                 --with-doubles                                       ----  '
echo ' -------------------------------------------------------------------------------- '
./configure --quiet LDFLAGS="-L/usr/X11R6/lib" CFLAGS="-Wall -I/usr/X11R6/include"  --with-doubles
make
echo ' '
echo ' '
./snd --version
./snd -noinit --features "'clm 'snd-guile"

echo ' '
make allclean
rm -f snd
rm -f config.cache
rm -f makefile
rm -f mus-config.h
rm -f sndinfo

echo ' -------------------------------------------------------------------------------- '
echo ' ----                  --with-doubles  but int samples                      ----  '
echo ' -------------------------------------------------------------------------------- '
./configure --quiet LDFLAGS="-L/usr/X11R6/lib" CFLAGS="-Wall -I/usr/X11R6/include"  --with-doubles --without-float-samples
make
echo ' '
echo ' '
./snd --version
./snd -noinit --features "'clm 'snd-guile"

echo ' '
echo ' '
make allclean
rm -f snd
rm -f config.cache
rm -f makefile
rm -f mus-config.h
rm -f sndinfo

echo ' -------------------------------------------------------------------------------- '
echo ' ----                  --without-float-samples --without-ladspa --with-gl --with-gl2ps --with-modules --without-gsl --without-xpm '
echo ' -------------------------------------------------------------------------------- '
./configure --quiet LDFLAGS="-L/usr/X11R6/lib" CFLAGS="-Wall -I/usr/X11R6/include"  --without-float-samples --without-ladspa --with-gl --with-gl2ps --with-modules --without-gsl --without-xpm
make
echo ' '
echo ' '
./snd --version
./snd -noinit --features "'clm 'gl 'gl2ps"
make clmclean

echo ' '
echo ' '
make allclean
rm -f snd
rm -f config.cache
rm -f makefile
rm -f mus-config.h
rm -f sndinfo

echo ' -------------------------------------------------------------------------------- '
echo ' -----                 --without-float-samples --with-sample-width=32 --with-just-gl --with-static-motif --without-fftw --with-midi '
echo ' -------------------------------------------------------------------------------- '
./configure --quiet LDFLAGS="-L/usr/X11R6/lib" CFLAGS="-Wall -I/usr/X11R6/include"  --without-float-samples --with-sample-width=32 --with-just-gl --with-static-motif --without-fftw --with-midi
make
echo ' '
echo ' '
./snd --version
./snd -noinit --features "'clm 'snd-motif"

echo ' '
echo ' '
make allclean
rm -f snd
rm -f config.cache
rm -f makefile
rm -f mus-config.h
rm -f sndinfo

echo ' -------------------------------------------------------------------------------- '
echo ' -----                 --without-float-samples --with-sample-width=28       ----  '
echo ' -------------------------------------------------------------------------------- '
./configure --quiet LDFLAGS="-L/usr/X11R6/lib" CFLAGS="-Wall -I/usr/X11R6/include"  --without-float-samples --with-sample-width=28
make
echo ' '
echo ' '
./snd --version
./snd -noinit --features "'clm"

echo ' '
echo ' '
make allclean
rm -f snd
rm -f config.cache
rm -f makefile
rm -f mus-config.h
rm -f sndinfo
echo ' -------------------------------------------------------------------------------- '
echo ' -----                 --without-float-samples --with-sample-width=16        ---- '
echo ' -------------------------------------------------------------------------------- '
./configure --quiet LDFLAGS="-L/usr/X11R6/lib" CFLAGS="-Wall -I/usr/X11R6/include"  --without-float-samples --with-sample-width=16
make
echo ' '
echo ' '
./snd --version
./snd -noinit --features "'clm"

make allclean
rm -f snd
rm -f config.cache

echo ' -------------------------------------------------------------------------------- '
echo ' ----                  --with-gtk                                            ---- '
echo ' -------------------------------------------------------------------------------- '
./configure --quiet LDFLAGS="-L/usr/X11R6/lib" CFLAGS="-Wall -I/usr/X11R6/include"  --with-gtk
make
echo ' '
echo ' '
./snd --version
./snd -noinit --features "'clm 'snd-gtk"
make allclean
rm -f snd
rm -f config.cache

echo ' -------------------------------------------------------------------------------- '
echo ' -----                 --with-gtk --with-static-xm                           ---- '
echo ' -------------------------------------------------------------------------------- '
./configure --quiet LDFLAGS="-L/usr/X11R6/lib" CFLAGS="-Wall -I/usr/X11R6/include"  --with-gtk --with-static-xm
make
echo ' '
echo ' '
./snd --version
./snd -noinit --features "'clm 'snd-gtk 'xg"
make allclean

echo ' -------------------------------------------------------------------------------- '
echo ' -----                GTK_DISABLE_DEPRECATED G_DISABLE_DEPRECATED GDK_DISABLE_DEPRECATED --with-gtk --with-static-xm --with-x11 '
echo ' -------------------------------------------------------------------------------- '
./configure --quiet --disable-deprecated CFLAGS="-Wall -I/usr/X11R6/include -D_FORTIFY_SOURCE" --with-gtk --with-static-xm --with-x11
make
echo ' '
echo ' '
./snd --version
./snd -noinit --features "'clm 'snd-gtk 'xg"

make allclean
rm -f snd
rm -f sndinfo
rm -f audinfo
rm -f config.cache

echo ' -------------------------------------------------------------------------------- '
echo ' ----                --enable-snd-debug --with-gsl                           ---- '
echo ' -------------------------------------------------------------------------------- '
./configure --quiet LDFLAGS="-L/usr/X11R6/lib" CFLAGS="-Wall -I/usr/X11R6/include -DXEN_DEBUGGING" --enable-snd-debug --with-gsl
make
echo ' '
echo ' '
./snd --version
./snd -noinit --features "'clm 'gsl 'snd-debug 'snd-motif"
make allclean

echo ' -------------------------------------------------------------------------------- '
echo ' -----                --with-static-xm  editres                              ---- '
echo ' -------------------------------------------------------------------------------- '
./configure --quiet LDFLAGS="-L/usr/X11R6/lib" CFLAGS="-Wall -I/usr/X11R6/include" --with-static-xm --with-editres --disable-deprecated
make
rm xm.o
echo ' '
echo ' '
echo ' -------------------------------------------------------------------------------- '
echo ' -----                g++ --with-static-xm                                   ---- '
echo ' -------------------------------------------------------------------------------- '
./configure LDFLAGS="-L/usr/X11R6/lib" --quiet CC=g++ --with-static-xm
make xm

make allclean
echo ' '
echo ' '
echo ' -------------------------------------------------------------------------------- '
echo ' -----                --with-static-xm --without-xpm --without-xp            ---- '
echo ' -------------------------------------------------------------------------------- '
./configure --quiet LDFLAGS="-L/usr/X11R6/lib" CFLAGS="-Wall -I/usr/X11R6/include" --with-static-xm --without-xpm --without-xp
make
./snd --version
./snd -noinit --features "'clm 'snd-motif 'xm"

echo ' '
echo ' '
make allclean
rm -f snd
rm -f config.cache

echo ' -------------------------------------------------------------------------------- '
echo ' ----                 --with-snd-as-widget                                   ---- '
echo ' -------------------------------------------------------------------------------- '
./configure --quiet LDFLAGS="-L/usr/X11R6/lib" CFLAGS="-Wall -I/usr/X11R6/include" --with-snd-as-widget
make
echo ' '
echo ' '
./snd --version
./snd -noinit --features "'clm"

make allclean
rm -f snd
rm -f config.cache

echo ' -------------------------------------------------------------------------------- '
echo ' ----                 --enable-snd-debug --with-gtk --with-gsl --with-gl --with-gl2ps '
echo ' -------------------------------------------------------------------------------- '
./configure --quiet LDFLAGS="-L/usr/X11R6/lib" CFLAGS="-Wall -I/usr/X11R6/include -DXEN_DEBUGGING" --enable-snd-debug --with-gtk --with-gsl --with-gl --with-gl2ps
make
echo ' '
echo ' '
./snd --version
./snd -noinit --features "'clm 'snd-gtk 'gsl 'gl 'snd-debug 'snd-guile 'gl2ps"

echo ' '
echo ' '
make allclean
rm -f snd
rm -f config.cache

echo ' -------------------------------------------------------------------------------- '
echo ' -----                --with-ruby                                            ---- '
echo ' -------------------------------------------------------------------------------- '
./configure --quiet LDFLAGS="-L/usr/X11R6/lib" CFLAGS="-Wall -I/usr/X11R6/include" --with-ruby
make
echo ' '
echo ' '
make xm
echo ' '
echo ' '
./snd --version
./snd -noinit --features ":clm, :snd_ruby, :snd_motif"
make allclean

echo ' -------------------------------------------------------------------------------- '
echo ' ----                 g++ --with-ruby                                        ---- '
echo ' -------------------------------------------------------------------------------- '
./configure --quiet CC=g++ LDFLAGS="-L/usr/X11R6/lib" CFLAGS="-Wall -I/usr/X11R6/include" --with-ruby --with-midi
make
./snd --version
./snd -noinit --features ":clm, :snd_ruby"
make allclean

echo ' -------------------------------------------------------------------------------- '
echo ' -----                --with-ruby --with-static-xm --with-gl --enable-snd-debug --with-alsa '
echo ' -------------------------------------------------------------------------------- '
./configure --quiet LDFLAGS="-L/usr/X11R6/lib" CFLAGS="-Wall -I/usr/X11R6/include -DXEN_DEBUGGING" --with-ruby --with-static-xm --with-gl --enable-snd-debug --with-alsa
make
echo ' '
echo ' '
./snd --version
./snd -noinit --features ":clm, :alsa, :snd_ruby, :xm, :gl, :snd_debug"

make allclean
rm -f snd
rm -f config.cache

echo ' -------------------------------------------------------------------------------- '
echo ' ----                 --with-ruby --with-gtk                                 ---- '
echo ' -------------------------------------------------------------------------------- '
./configure --quiet LDFLAGS="-L/usr/X11R6/lib" CFLAGS="-Wall -I/usr/X11R6/include" --with-ruby --with-gtk
make
echo ' '
echo ' '
./snd --version
./snd -noinit --features ":clm, :snd_gtk, :snd_ruby"
make allclean

echo ' -------------------------------------------------------------------------------- '
echo ' -----                g++ --with-ruby --with-gtk --with-alsa                 ---- '
echo ' -------------------------------------------------------------------------------- '
./configure --quiet CC=g++ --with-ruby --with-gtk --with-alsa
make
echo ' '
echo ' '
./snd --version
./snd -noinit --features ":clm, :alsa, :snd_gtk, :snd_ruby"
make allclean

echo ' -------------------------------------------------------------------------------- '
echo ' ----                 --with-ruby --with-static-xm --with-gtk --enable-snd-debug --without-gsl --without-xpm --without-xp '
echo ' -------------------------------------------------------------------------------- '
./configure --quiet LDFLAGS="-L/usr/X11R6/lib" CFLAGS="-Wall -I/usr/X11R6/include -DXEN_DEBUGGING" --with-ruby --with-static-xm --with-gtk --enable-snd-debug --without-gsl --without-xpm --without-xp
make
echo ' '
echo ' '
./snd --version
./snd -noinit --features ":clm, :snd_ruby, :xg, :snd_gtk, :snd_debug"
make allclean

echo ' -------------------------------------------------------------------------------- '
echo ' ----                GTK_DISABLE_DEPRECATED G_DISABLE_DEPRECATED GDK_DISABLE_DEPRECATED --with-ruby --with-static-xm --with-gtk --with-x11 --with-gl '
echo ' -------------------------------------------------------------------------------- '
./configure --quiet --disable-deprecated LDFLAGS="-L/usr/X11R6/lib" CFLAGS="-Wall -I/usr/X11R6/include -D_FORTIFY_SOURCE" --with-ruby --with-static-xm --with-gtk --with-x11 --with-gl
make
echo ' '
echo ' '
./snd --version
./snd -noinit --features "'clm 'snd-gtk 'xg 'gl"

make allclean
rm -f snd
rm -f config.cache

echo ' -------------------------------------------------------------------------------- '
echo ' ----                 --with-ruby --with-no-gui --without-fftw                --- '
echo ' -------------------------------------------------------------------------------- '
./configure --quiet LDFLAGS="-L/usr/X11R6/lib" CFLAGS="-Wall -I/usr/X11R6/include" --with-ruby --with-no-gui --without-fftw
make
echo ' '
echo ' '
./snd --version
./snd -noinit --features ":clm, :snd_nogui, :snd_ruby"
make allclean

echo ' -------------------------------------------------------------------------------- '
echo ' -----                --with-ruby --with-no-gui --enable-snd-debug           ---- '
echo ' -------------------------------------------------------------------------------- '
./configure --quiet LDFLAGS="-L/usr/X11R6/lib" CFLAGS="-Wall -I/usr/X11R6/include -DXEN_DEBUGGING" --with-ruby --with-no-gui --enable-snd-debug
make
echo ' '
echo ' '
./snd --version
./snd -noinit --features ":clm, :snd_nogui, :snd_debug, :snd_ruby"
make allclean

echo ' -------------------------------------------------------------------------------- '
echo ' ----                g++ --with-ruby --with-no-gui --enable-snd-debug        ---- '
echo ' -------------------------------------------------------------------------------- '
./configure --quiet CC=g++ LDFLAGS="-L/usr/X11R6/lib" CFLAGS="-Wall -I/usr/X11R6/include -DXEN_DEBUGGING" --with-ruby --with-no-gui --enable-snd-debug
make
echo ' '
echo ' '
./snd --version
./snd -noinit --features ":clm, :snd_nogui, :snd_ruby, :snd_debug"
make allclean

rm -f snd
rm -f config.cache

echo ' -------------------------------------------------------------------------------- '
echo ' ----                g++                                                      --- '
echo ' -------------------------------------------------------------------------------- '
./configure --quiet CC=g++ LDFLAGS="-L/usr/X11R6/lib" CFLAGS="-Wall -I/usr/X11R6/include"
make
./snd --version
./snd -noinit --features "'clm 'snd-guile 'snd-motif 'snd-ladspa 'sndlib"
make sndinfo
make audinfo
make sndplay
make sndrecord
./audinfo
./sndinfo test.snd
make allclean

echo ' '
echo ' '
echo ' -------------------------------------------------------------------------------- '
echo ' ----                g++ --with-gtk                                          ---- '
echo ' -------------------------------------------------------------------------------- '
./configure --quiet CC=g++ --with-gtk
make
./snd --version
./snd -noinit --features "'clm 'snd-gtk"
make allclean

echo ' '
echo ' '
echo ' -------------------------------------------------------------------------------- '
echo ' ----                g++ --with-no-gui                                       ---- '
echo ' -------------------------------------------------------------------------------- '
./configure LDFLAGS="-L/usr/X11R6/lib" CFLAGS="-I/usr/X11R6/include" --quiet CC=g++ --with-no-gui
make
./snd --version
./snd -noinit --features "'clm 'snd-nogui 'snd-guile"
make allclean

echo ' -------------------------------------------------------------------------------- '
echo ' -----                g++ --without-guile --without-ruby                     ---- '
echo ' -------------------------------------------------------------------------------- '
./configure LDFLAGS="-L/usr/X11R6/lib" CFLAGS="-I/usr/X11R6/include" --quiet CC=g++ --without-guile --without-ruby
make
./snd --version
make allclean
echo ' '
echo ' '

echo ' -------------------------------------------------------------------------------- '
echo ' -----                g++ --with-static-xm --with-hobbit --without-gsl --with-alsa '
echo ' -------------------------------------------------------------------------------- '
./configure LDFLAGS="-L/usr/X11R6/lib" CFLAGS="-I/usr/X11R6/include" --quiet CC=g++ --with-static-xm --without-gsl --with-alsa
make
./snd --version
./snd -noinit --features "'clm 'alsa 'xm"
make allclean
echo ' '
echo ' '

make allclean
rm -f snd
rm -f config.cache
rm -f sndinfo
rm -f audinfo

echo ' -------------------------------------------------------------------------------- '
echo ' -----                sndlib                                                 ---- '
echo ' -------------------------------------------------------------------------------- '
./configure --quiet LDFLAGS="-L/usr/X11R6/lib" CFLAGS="-Wall -I/usr/X11R6/include"
make sndinfo
sndinfo oboe.snd
make audinfo
audinfo
sndinfo test.snd

echo ' '
echo ' '
make allclean
echo ' -------------------------------------------------------------------------------- '
echo ' ----                --with-shared-sndlib                                    ---- '
echo ' -------------------------------------------------------------------------------- '
./configure LDFLAGS="-L/usr/X11R6/lib" CFLAGS="-I/usr/X11R6/include" --quiet --with-shared-sndlib
make
./snd --version
./snd -noinit --features "'clm"

echo ' '
echo ' '
echo ' -------------------------------- no-gui test -------------------------------- '
make allclean
rm -f snd
echo ' -------------------------------------------------------------------------------- '
echo ' ----                 --with-no-gui                                          ---- '
echo ' -------------------------------------------------------------------------------- '
./configure --quiet LDFLAGS="-L/usr/X11R6/lib" CFLAGS="-Wall -I/usr/X11R6/include" --with-no-gui
make
echo ' '
echo ' '
./snd --version
./snd -noinit --features "'clm 'snd-nogui 'snd-guile"

make allclean
rm -f snd
rm -f config.cache
rm -f makefile
rm -f mus-config.h

echo ' -------------------------------------------------------------------------------- '
echo ' -----                --disable-nls                                          ---- '
echo ' -------------------------------------------------------------------------------- '
./configure --quiet LDFLAGS="-L/usr/X11R6/lib" CFLAGS="-Wall -I/usr/X11R6/include" --disable-nls
make
./snd --version
./snd -noinit --features "'clm 'snd-guile"
make allclean
echo ' '
echo ' '

echo ' -------------------------------------------------------------------------------- '
echo ' ----                g++ --with-gtk --disable-nls                            ---- '
echo ' -------------------------------------------------------------------------------- '
./configure LDFLAGS="-L/usr/X11R6/lib" CFLAGS="-I/usr/X11R6/include" --quiet CC=g++ --with-gtk --disable-nls
make
./snd --version
./snd -noinit --features "'clm 'snd-gtk"
make allclean
echo ' '
echo ' '

echo ' -------------------------------------------------------------------------------- '
echo ' ----                g++ --with-no-gui --disable-nls                         ---- '
echo ' -------------------------------------------------------------------------------- '
./configure LDFLAGS="-L/usr/X11R6/lib" CFLAGS="-I/usr/X11R6/include" --quiet CC=g++ --with-no-gui --disable-nls
make
./snd --version
./snd -noinit --features "'clm 'snd-nogui 'snd-guile"
make allclean
echo ' '
echo ' '

echo ' -------------------------------------------------------------------------------- '
echo ' -----                g++ --without-guile --without-ruby --disable-nls       ---- '
echo ' -------------------------------------------------------------------------------- '
./configure LDFLAGS="-L/usr/X11R6/lib" CFLAGS="-I/usr/X11R6/include" --quiet CC=g++ --without-guile --without-ruby --disable-nls
make
./snd --version
make allclean
echo ' '
echo ' '

echo ' -------------------------------------------------------------------------------- '
echo ' ----                g++ --with-static-xm --disable-nls                      ---- '
echo ' -------------------------------------------------------------------------------- '
./configure LDFLAGS="-L/usr/X11R6/lib" CFLAGS="-I/usr/X11R6/include" --quiet CC=g++ --with-static-xm --disable-nls
make
./snd --version
./snd -noinit --features "'clm 'xm"
./snd -e "(begin (display (+ 1 2 3)) (exit))"
make allclean
echo ' '
echo ' '

echo ' -------------------------------------------------------------------------------- '
echo ' -----                --with-ruby --disable-nls                              ---- '
echo ' -------------------------------------------------------------------------------- '
./configure --quiet LDFLAGS="-L/usr/X11R6/lib" CFLAGS="-Wall -I/usr/X11R6/include" --with-ruby --disable-nls
make
./snd --version
./snd -noinit --features ":clm, :snd_ruby"
make allclean
cp makefile.gettext makefile.in

echo ' '
echo ' '
echo ' -------------------------------------------------------------------------------- '
echo ' -----                --with-static-xm -DXM_DISABLE_DEPRECATED              ----- '
echo ' -------------------------------------------------------------------------------- '
./configure --quiet --with-static-xm LDFLAGS="-L/usr/X11R6/lib" CFLAGS="-DXM_DISABLE_DEPRECATED -Wall -I/usr/X11R6/include"
make
./snd --version
./snd -noinit --features "'clm 'xm"
make allclean
echo ' '
echo ' '

echo ' -------------------------------------------------------------------------------- '
echo ' -----                --with-static-xm --with-ruby -DXM_DISABLE_DEPRECATED   ---- '
echo ' -------------------------------------------------------------------------------- '
./configure --quiet --with-static-xm --with-ruby LDFLAGS="-L/usr/X11R6/lib" CFLAGS="-DXM_DISABLE_DEPRECATED -Wall -I/usr/X11R6/include"
make
./snd --version
./snd -noinit --features ":clm, :xm, :snd_ruby"
make allclean

echo ' '
echo ' '
echo ' -------------------------------------------------------------------------------- '
echo ' -----                --with-no-gui --without-guile --without-ruby          ----- '
echo ' -------------------------------------------------------------------------------- '
./configure LDFLAGS="-L/usr/X11R6/lib" CFLAGS="-I/usr/X11R6/include" --with-no-gui --without-guile --without-ruby --quiet
make
./snd --version
make allclean
echo ' '
echo ' '

echo ' -------------------------------------------------------------------------------- '
echo ' ----                 --without-guile --without-ruby --with-static-xm --with-gl - '
echo ' -------------------------------------------------------------------------------- '
./configure LDFLAGS="-L/usr/X11R6/lib" CFLAGS="-I/usr/X11R6/include" --without-guile --without-ruby --with-static-xm --with-gl --quiet
make
./snd --version
make allclean
echo ' '
echo ' '

echo ' -------------------------------------------------------------------------------- '
echo ' -----                --with-static-xm --with-just-gl --with-gl2ps         ------ '
echo ' -------------------------------------------------------------------------------- '
./configure LDFLAGS="-L/usr/X11R6/lib" CFLAGS="-I/usr/X11R6/include" --with-static-xm --with-just-gl --quiet --with-gl2ps
make
./snd --version
./snd -noinit --features "'clm 'xm 'gl2ps"
make allclean
echo ' '
echo ' '

echo ' -------------------------------------------------------------------------------- '
echo ' -----                --without-guile --without-ruby --with-gtk --with-static-xg --with-gl '
echo ' -------------------------------------------------------------------------------- '
./configure --without-guile --without-ruby --with-gtk --with-static-xg --with-gl --quiet
make
./snd --version
make allclean
echo ' '
echo ' '

echo ' -------------------------------------------------------------------------------- '
echo ' -----                --without-fam                                          ---- '
echo ' -------------------------------------------------------------------------------- '
./configure LDFLAGS="-L/usr/X11R6/lib" CFLAGS="-I/usr/X11R6/include" --without-fam --quiet
make
./snd --version
./snd -noinit --features "'clm 'snd-guile 'snd-motif 'sndlib"
make allclean
make allclean
echo ' '
echo ' '

echo ' -------------------------------------------------------------------------------- '
echo ' ----                 --without-fam --with-gtk                               ---- '
echo ' -------------------------------------------------------------------------------- '
./configure --without-fam --with-gtk --quiet
make
./snd --version
./snd -noinit --features "'clm 'snd-gtk"
make allclean

echo ' '
echo ' '
echo ' -------------------------------------------------------------------------------- '
echo ' -----                --enable-threads                                       ---- '
echo ' -------------------------------------------------------------------------------- '
./configure LDFLAGS="-L/usr/X11R6/lib" CFLAGS="-I/usr/X11R6/include" --enable-threads --quiet
make
./snd --version
./snd -noinit --features "'clm 'snd-guile 'snd-motif"
make allclean

echo ' '
echo ' '
echo ' -------------------------------------------------------------------------------- '
echo ' ----                 --enable-threads g++                                   ---- '
echo ' -------------------------------------------------------------------------------- '
./configure LDFLAGS="-L/usr/X11R6/lib" CFLAGS="-I/usr/X11R6/include" --enable-threads --quiet CC=g++
make
./snd --version
./snd -noinit --features "'clm 'snd-guile"
make allclean

echo ' '
echo ' '
echo ' -------------------------------------------------------------------------------- '
echo ' -----                --enable-threads --with-gtk --with-ruby                ---- '
echo ' -------------------------------------------------------------------------------- '
./configure --enable-threads --with-gtk --with-ruby --quiet
make
./snd --version
./snd -noinit --features ":clm, :snd-gtk, :snd_ruby"
make allclean

echo ' '
echo ' '
echo ' -------------------------------------------------------------------------------- '
echo ' ----                --with-ruby --with-ruby-prefix=/home/bil/test/tmp-ruby ----- '
echo ' -------------------------------------------------------------------------------- '
./configure LDFLAGS="-L/usr/X11R6/lib" CFLAGS="-I/usr/X11R6/include" --quiet --with-ruby --with-ruby-prefix=/home/bil/test/tmp-ruby
make
./snd --version
./snd -noinit --features ":clm, :snd_ruby"
make allclean

echo ' '
echo ' '
echo ' -------------------------------------------------------------------------------- '
echo ' ----                 --with-jack GUILE_CONFIG_path=/home/bil/test/bin       ---- '
echo ' -------------------------------------------------------------------------------- '
./configure --quiet --with-jack CFLAGS="-I/home/bil/test/include -I/usr/X11R6/include" LDFLAGS="-L/home/bil/test/lib -L/usr/X11R6/lib" GUILE_CONFIG_path=/home/bil/test/bin
make
./snd --version
./snd -noinit --features "'clm 'snd-guile"
make allclean

echo ' '
echo ' '
echo ' -------------------------------------------------------------------------------- '
echo ' ----                 -DSCM_DEBUG_TYPING_STRICTNESS=2 GUILE_CONFIG_path=/home/bil/test/bin '
echo ' -------------------------------------------------------------------------------- '
./configure --quiet CFLAGS="-I/home/bil/test/include -I/usr/X11R6/include -DSCM_DEBUG_TYPING_STRICTNESS=2" LDFLAGS="-L/home/bil/test/lib -L/usr/X11R6/lib" GUILE_CONFIG_path=/home/bil/test/bin
make
./snd --version
./snd -noinit --features "'clm 'snd-guile"
make allclean

echo ' '
echo ' '
echo ' -------------------------------------------------------------------------------- '
echo ' ----                --with-gtk --with-static-xg --with-jack GUILE_CONFIG_path=/home/bil/test/bin '
echo ' -------------------------------------------------------------------------------- '
./configure --quiet --with-gtk --with-static-xg --with-jack CFLAGS="-I/home/bil/test/include -I/usr/X11R6/include" LDFLAGS="-L/home/bil/test/lib -L/usr/X11R6/lib" GUILE_CONFIG_path=/home/bil/test/bin
make
./snd --version
./snd -noinit --features "'clm 'xg 'snd-gtk 'snd-guile"
make allclean

echo ' '
echo ' '
echo ' -------------------------------------------------------------------------------- '
echo ' ------                --with-snd-as-pd-external --with-no-gui GUILE_CONFIG_path=/home/bil/test/bin '
echo ' -------------------------------------------------------------------------------- '
./configure --quiet --with-snd-as-pd-external --with-no-gui CFLAGS="-I/home/bil/test/include -I/usr/X11R6/include" LDFLAGS="-L/home/bil/test/lib" GUILE_CONFIG_path=/home/bil/test/bin
make
./snd --version
./snd -noinit --features "'clm 'snd-nogui 'snd-pd-external 'snd-guile"
make allclean

setenv PKG_CONFIG_PATH /home/bil/test/old-gtk/lib/pkgconfig

echo ' '
echo ' '
echo ' -------------------------------------------------------------------------------- '
echo ' ------                OLD-GTK: --with-gtk -I/home/bil/test/old-gtk          ---- '
echo ' -------------------------------------------------------------------------------- '
./configure --quiet --with-gtk LDFLAGS="-L/usr/X11R6/lib" CFLAGS="-Wall -I/usr/X11R6/include -I/home/bil/test/old-gtk"
make
./snd --version
./snd -noinit --features "'clm 'snd-gtk"

setenv PKG_CONFIG_PATH /usr/local/lib/pkgconfig

echo ' '
echo ' '
echo ' -------------------------------------------------------------------------------- '
echo ' -----                GUILE_CONFIG_path=/home/bil/test/g13/bin               ---- '
echo ' -------------------------------------------------------------------------------- '
./configure --quiet CFLAGS="-I/home/bil/test/g13/include -I/usr/X11R6/include" LDFLAGS="-L/home/bil/test/g13/lib -L/usr/X11R6/lib" GUILE_CONFIG_path=/home/bil/test/g13/bin
make
./snd --version
./snd -noinit --features "'clm 'snd-guile"
make allclean

echo ' '
echo ' '
echo ' -------------------------------------------------------------------------------- '
echo ' -----                GUILE_CONFIG_path=/home/bil/test/g14/bin               ---- '
echo ' -------------------------------------------------------------------------------- '
./configure --quiet CFLAGS="-I/home/bil/test/g14/include -I/usr/X11R6/include" LDFLAGS="-L/home/bil/test/g14/lib -L/usr/X11R6/lib" GUILE_CONFIG_path=/home/bil/test/g14/bin
make
./snd --version
./snd -noinit --features "'clm 'snd-guile"
make allclean

echo ' '
echo ' '
echo ' -------------------------------------------------------------------------------- '
echo ' ----                GUILE_CONFIG_path=/home/bil/test/g13/bin --with-static-xm -- '
echo ' -------------------------------------------------------------------------------- '
./configure --quiet CFLAGS="-I/home/bil/test/g13/include -I/usr/X11R6/include" LDFLAGS="-L/home/bil/test/g13/lib -L/usr/X11R6/lib" GUILE_CONFIG_path=/home/bil/test/g13/bin --with-static-xm
make
./snd --version
./snd -noinit --features "'clm 'snd-guile"
make allclean

echo ' '
echo ' '
echo ' -------------------------------------------------------------------------------- '
echo ' ------                GUILE_CONFIG_path=/home/bil/test/g14/bin --with-static-xm  '
echo ' -------------------------------------------------------------------------------- '
./configure --quiet CFLAGS="-I/home/bil/test/g14/include -I/usr/X11R6/include" LDFLAGS="-L/home/bil/test/g14/lib -L/usr/X11R6/lib" GUILE_CONFIG_path=/home/bil/test/g14/bin --with-static-xm
make
./snd --version
./snd -noinit --features "'clm 'snd-guile"
make allclean

echo ' '
echo ' '
echo ' -------------------------------------------------------------------------------- '
echo ' ----                GUILE_CONFIG_path=/home/bil/test/g13/bin --with-static-xg --with-gtk '
echo ' -------------------------------------------------------------------------------- '
./configure --quiet CFLAGS="-I/home/bil/test/g13/include -I/usr/X11R6/include" LDFLAGS="-L/home/bil/test/g13/lib -L/usr/X11R6/lib" GUILE_CONFIG_path=/home/bil/test/g13/bin --with-static-xg --with-gtk
make
./snd --version
./snd -noinit --features "'clm 'snd-guile"
make allclean

echo ' '
echo ' '
echo ' -------------------------------------------------------------------------------- '
echo ' -----                GUILE_CONFIG_path=/home/bil/test/g14/bin --with-static-xg --with-gtk '
echo ' -------------------------------------------------------------------------------- '
./configure --quiet CFLAGS="-I/home/bil/test/g14/include -I/usr/X11R6/include" LDFLAGS="-L/home/bil/test/g14/lib -L/usr/X11R6/lib" GUILE_CONFIG_path=/home/bil/test/g14/bin --with-static-xg --with-gtk
make
./snd --version
./snd -noinit --features "'clm 'snd-guile"
make allclean


echo ' '
echo ' '
echo ' -------------------------------------------------------------------------------- '
echo ' -----                g++ GUILE_CONFIG_path=/home/bil/test/g13/bin           ---- '
echo ' -------------------------------------------------------------------------------- '
./configure --quiet CFLAGS="-I/home/bil/test/g13/include -Wall -I/usr/X11R6/include" LDFLAGS="-L/home/bil/test/g13/lib -L/usr/X11R6/lib" CC=g++ GUILE_CONFIG_path=/home/bil/test/g13/bin
make
./snd --version
./snd -noinit --features "'clm 'snd-guile"
make allclean

echo ' '
echo ' '
echo ' -------------------------------------------------------------------------------- '
echo ' -----                g++ GUILE_CONFIG_path=/home/bil/test/g14/bin           ---- '
echo ' -------------------------------------------------------------------------------- '
./configure --quiet CFLAGS="-I/home/bil/test/g14/include -Wall -I/usr/X11R6/include" LDFLAGS="-L/home/bil/test/g14/lib -L/usr/X11R6/lib" CC=g++ GUILE_CONFIG_path=/home/bil/test/g14/bin
make
./snd --version
./snd -noinit --features "'clm 'snd-guile"
make allclean

echo ' '
echo ' '
echo ' -------------------------------------------------------------------------------- '
echo ' ----                g++ GUILE_CONFIG_path=/home/bil/test/g13/bin --with-static-xm '
echo ' -------------------------------------------------------------------------------- '
./configure --quiet CFLAGS="-I/home/bil/test/g13/include -Wall -I/usr/X11R6/include" LDFLAGS="-L/home/bil/test/g13/lib -L/usr/X11R6/lib" CC=g++ GUILE_CONFIG_path=/home/bil/test/g13/bin --with-static-xm
make
./snd --version
./snd -noinit --features "'clm 'snd-guile"
make allclean

echo ' '
echo ' '
echo ' -------------------------------------------------------------------------------- '
echo ' -----                g++ GUILE_CONFIG_path=/home/bil/test/g14/bin --with-static-xm '
echo ' -------------------------------------------------------------------------------- '
./configure --quiet CFLAGS="-I/home/bil/test/g14/include -Wall -I/usr/X11R6/include" LDFLAGS="-L/home/bil/test/g14/lib -L/usr/X11R6/lib" CC=g++ GUILE_CONFIG_path=/home/bil/test/g14/bin --with-static-xm
make
./snd --version
./snd -noinit --features "'clm 'snd-guile"
make allclean

echo ' '
echo ' '
echo ' -------------------------------------------------------------------------------- '
echo ' -----                g++ GUILE_CONFIG_path=/home/bil/test/g13/bin --with-static-xg --with-gtk '
echo ' -------------------------------------------------------------------------------- '
./configure --quiet CFLAGS="-I/home/bil/test/g13/include -Wall -I/usr/X11R6/include" LDFLAGS="-L/home/bil/test/g13/lib -L/usr/X11R6/lib" CC=g++ GUILE_CONFIG_path=/home/bil/test/g13/bin --with-static-xg --with-gtk
make
./snd --version
./snd -noinit --features "'clm 'snd-guile"
make allclean

echo ' '
echo ' '
echo ' -------------------------------------------------------------------------------- '
echo ' -----                g++ GUILE_CONFIG_path=/home/bil/test/g14/bin --with-static-xg --with-gtk '
echo ' -------------------------------------------------------------------------------- '
./configure --quiet CFLAGS="-I/home/bil/test/g14/include -Wall -I/usr/X11R6/include" LDFLAGS="-L/home/bil/test/g14/lib -L/usr/X11R6/lib" CC=g++ GUILE_CONFIG_path=/home/bil/test/g14/bin --with-static-xg --with-gtk
make
./snd --version
./snd -noinit --features "'clm 'snd-guile"
make allclean

echo ' '
echo ' '
echo ' -------------------------------------------------------------------------------- '
echo ' ------                GUILE_CONFIG_path=/home/bil/test/guile-1.8.1/g181/bin --with-static-xm  '
echo ' -------------------------------------------------------------------------------- '
./configure --quiet CFLAGS="-I/home/bil/test/guile-1.8.1/g181/include -I/usr/X11R6/include" LDFLAGS="-L/home/bil/test/guile-1.8.1/g181/lib -L/usr/X11R6/lib" GUILE_CONFIG_path=/home/bil/test/guile-1.8.1/g181/bin --with-static-xm
make
./snd --version
./snd -noinit --features "'clm 'snd-guile"
make allclean

echo ' '
echo ' '
echo ' -------------------------------------------------------------------------------- '
echo ' ------                GUILE_CONFIG_path=/home/bil/test/guile-1.8.2/g182/bin --with-static-xm  '
echo ' -------------------------------------------------------------------------------- '
./configure --quiet CFLAGS="-I/home/bil/test/guile-1.8.2/g182/include -I/usr/X11R6/include" LDFLAGS="-L/home/bil/test/guile-1.8.2/g182/lib -L/usr/X11R6/lib" GUILE_CONFIG_path=/home/bil/test/guile-1.8.2/g182/bin --with-static-xm
make
./snd --version
./snd -noinit --features "'clm 'snd-guile"
make allclean

cp ~/sndlib/* .
echo ' -------------------------------------------------------------------------------- '
echo ' -----                sndlib tests                                           ---- '
echo ' -------------------------------------------------------------------------------- '
./configure LDFLAGS="-L/usr/X11R6/lib" CFLAGS="-I/usr/X11R6/include" --quiet
make
make clean
./configure LDFLAGS="-L/usr/X11R6/lib" CFLAGS="-I/usr/X11R6/include" --quiet --with-ruby
make
make clean
./configure LDFLAGS="-L/usr/X11R6/lib" CFLAGS="-I/usr/X11R6/include" --quiet --with-gauche
make
make clean
./configure LDFLAGS="-L/usr/X11R6/lib" CFLAGS="-I/usr/X11R6/include" --quiet --with-forth
make
make clean
./configure LDFLAGS="-L/usr/X11R6/lib" CFLAGS="-I/usr/X11R6/include" --quiet --without-guile --without-ruby --without-gauche --without-forth
make
make clean
./configure LDFLAGS="-L/usr/X11R6/lib" CFLAGS="-I/usr/X11R6/include" --quiet --disable-deprecated
make
make clean

cp ~/libxm/* .
echo ' -------------------------------------------------------------------------------- '
echo ' -----                libxm tests                                            ---- '
echo ' -------------------------------------------------------------------------------- '
./configure LDFLAGS="-L/usr/X11R6/lib" CFLAGS="-I/usr/X11R6/include" --quiet
make
make clean
./configure LDFLAGS="-L/usr/X11R6/lib" CFLAGS="-I/usr/X11R6/include" --quiet --with-ruby
make
make clean
./configure LDFLAGS="-L/usr/X11R6/lib" CFLAGS="-I/usr/X11R6/include" --quiet --with-gauche
make
make clean
./configure LDFLAGS="-L/usr/X11R6/lib" CFLAGS="-I/usr/X11R6/include" --quiet --with-forth
make
make clean
./configure LDFLAGS="-L/usr/X11R6/lib" CFLAGS="-I/usr/X11R6/include" --quiet --without-guile --without-ruby --without-gauche --without-forth
make
make clean
./configure LDFLAGS="-L/usr/X11R6/lib" CFLAGS="-I/usr/X11R6/include" --quiet --disable-deprecated
make
make clean
./configure --quiet --with-gtk
make
make clean
./configure --quiet --with-ruby --with-gtk
make
make clean
./configure --quiet --with-gauche --with-gtk
make
make clean
./configure --quiet --with-forth --with-gtk
make
make clean
./configure --quiet --without-guile --without-ruby --without-gauche --without-forth --with-gtk
make
make clean
./configure --quiet --disable-deprecated --with-gtk
make
make clean

cp ~/dist/snd/snd.tar .
tar xf snd.tar
