#!/bin/csh -f

# cp ~/dist/snd/snd.tar .
# tar xf snd.tar

# words I constantly missppelll
fgrep decrip *.html
fgrep accomoda *.html
fgrep pysical *.html
fgrep decrip *.c
fgrep maake *.c
fgrep maake *.html
fgrep accomoda *.c
fgrep decrip *.scm
fgrep accomoda *.scm
# fgrep -e " #(" *.scm
fgrep -e "the the " *.c
fgrep -e "the the " *.html
fgrep udpate *.c
fgrep udpate *.html
fgrep udpate *.scm
fgrep -e "Float* " *.[ch]
fgrep -e "float* " *.h
fgrep -e "double* " *.h
fgrep -e "int* " *.h
fgrep -e "off_t* " *.[ch]
fgrep -e " long* " *.[ch]
grep ' \-\-$' *.html
/home/bil/cl/snd tools/va.scm
# tools/check-gtk.scm

rm -f snd
rm -f config.cache

echo ' -------------------------------------------------------------------------------- '
echo ' ----                 basic configure test                                  ----- '
echo ' -------------------------------------------------------------------------------- '
./configure --quiet --disable-deprecated --with-motif CFLAGS="-I/usr/X11R6/include" LDFLAGS="-L/usr/X11R6/lib" 
make allclean
make
echo ' '
echo ' '

./snd --version
./snd -noinit --features "'clm 'snd-s7 'snd-motif 'sndlib"
./snd tools/check-help.scm


echo ' -------------------------------------------------------------------------------- '
echo ' ----                 ffitest                                               ----- '
echo ' -------------------------------------------------------------------------------- '

cp tools/ffitest.c .
gcc -o ffitest ffitest.c -g3 -Wall s7.o -lm -I. -ldl
ffitest

make clmclean
make sndinfo
make sndplay
make allclean

./configure --quiet --disable-deprecated --with-motif CFLAGS="-I/usr/X11R6/include -Wextra -Wdeclaration-after-statement -Wlogical-op" LDFLAGS="-L/usr/X11R6/lib"
make allclean
make
echo ' '
echo ' '

make clmclean
make sndinfo
make sndplay
make allclean

echo ' '
echo ' '
echo ' -------------------------------------------------------------------------------- '
echo ' ----                 g++                                ----  '
echo ' -------------------------------------------------------------------------------- '
./configure --quiet --disable-deprecated CC=g++ CFLAGS="-I/usr/X11R6/include" LDFLAGS="-L/usr/X11R6/lib" 
make
./snd --version
./snd -noinit --features "'clm"

make allclean
rm -f snd
rm -f config.cache

echo ' '
echo ' '
echo ' -------------------------------------------------------------------------------- '
echo ' ----                 clang                                ----  '
echo ' -------------------------------------------------------------------------------- '
./configure --quiet --disable-deprecated CC=/home/bil/test/llvm-3.1.src/build/Release+Asserts/bin/clang CFLAGS="-I/usr/X11R6/include" LDFLAGS="-L/usr/X11R6/lib" 
make
./snd --version
./snd -noinit --features "'clm"

make allclean
rm -f snd
rm -f config.cache

echo ' '
echo ' '
echo ' -------------------------------------------------------------------------------- '
echo ' -----                --without-gui                                         ----  '
echo ' -------------------------------------------------------------------------------- '
./configure --quiet --disable-deprecated LDFLAGS="-L/usr/X11R6/lib" CFLAGS="-I/usr/X11R6/include" --without-gui
make
echo ' '
echo ' '
./snd --version
./snd -noinit --features "'clm 'snd-nogui"


echo ' '
echo ' '
echo ' -------------------------------- no complex -------------------------------- '
make clean
sed mus-config.h -e 's/#define WITH_COMPLEX 1/#define WITH_COMPLEX 0/g' > tmp
mv tmp mus-config.h
sed mus-config.h -e 's/#define HAVE_COMPLEX_TRIG 1/#define HAVE_COMPLEX_TRIG 0/g' > tmp
mv tmp mus-config.h
make


make allclean
rm -f snd
rm -f config.cache

echo ' '
echo ' '
echo ' -------------------------------------------------------------------------------- '
echo ' -----                --without-gui --with-oss                              ----  '
echo ' -------------------------------------------------------------------------------- '
./configure --quiet --disable-deprecated LDFLAGS="-L/usr/X11R6/lib" CFLAGS="-I/usr/X11R6/include" --without-gui --with-oss
make
echo ' '
echo ' '
./snd --version
./snd -noinit --features "'clm 'snd-nogui 'oss"

make allclean
rm -f snd
rm -f config.cache

echo ' -------------------------------------------------------------------------------- '
echo ' -----                --without-gui --with-gmp                              ----  '
echo ' -------------------------------------------------------------------------------- '
./configure --quiet --disable-deprecated --without-gui --with-gmp
make
echo ' '
echo ' '
./snd --version
./snd -noinit --features "'clm 'snd-nogui 'gmp"

make allclean
rm -f snd
rm -f config.cache

echo ' '
echo ' '
echo ' -------------------------------------------------------------------------------- '
echo ' ----                 -without-gui --without-ladspa                         ----  '
echo ' -------------------------------------------------------------------------------- '
./configure --quiet --disable-deprecated LDFLAGS="-L/usr/X11R6/lib" CFLAGS="-I/usr/X11R6/include" --without-gui --without-ladspa
make
echo ' '
echo ' '
./snd --version
./snd -noinit --features "'clm 'snd-nogui 'snd-s7"

make allclean
rm -f snd
rm -f config.cache

echo ' '
echo ' '
echo ' -------------------------------------------------------------------------------- '
echo ' ----                --with-gtk                                             ----  '
echo ' -------------------------------------------------------------------------------- '
./configure --quiet --disable-deprecated LDFLAGS="-L/usr/X11R6/lib" CFLAGS="-I/usr/X11R6/include" --with-gtk
make
echo ' '
echo ' '
./snd --version
./snd -noinit --features "'clm 'snd-gtk 'snd-s7"

echo ' '
echo ' '
echo ' -------------------------------------------------------------------------------- '
echo ' ----                 g++ --with-gtk --disable-deprecated                   ----  '
echo ' -------------------------------------------------------------------------------- '
./configure --quiet --disable-deprecated CC=g++ CFLAGS="-I/usr/X11R6/include" --with-gtk --disable-deprecated
make allclean
make
./snd --version
./snd -noinit --features "'clm 'snd-gtk 'snd-s7"
make allclean

echo ' '
echo ' '
echo ' -------------------------------------------------------------------------------- '
echo ' -----                g++ --with-gtk                                         ---  '
echo ' -------------------------------------------------------------------------------- '
./configure --quiet --disable-deprecated CC=g++ --with-gtk CFLAGS="-I/usr/X11R6/include"
make
./snd --version
./snd -noinit --features "'clm 'snd-gtk"
make allclean

echo ' '
echo ' '
echo ' -------------------------------------------------------------------------------- '
echo ' -----                g++ --with-gtk --with-gsl                              ---  '
echo ' -------------------------------------------------------------------------------- '
./configure --quiet --disable-deprecated CC=g++ --with-gtk --with-gsl CFLAGS="-I/usr/X11R6/include"
make
./snd --version
./snd -noinit --features "'clm 'snd-gtk 'gsl"
make allclean

echo ' '
echo ' '
echo ' -------------------------------------------------------------------------------- '
echo ' -----                --with-forth                                           ---- '
echo ' -------------------------------------------------------------------------------- '
./configure LDFLAGS="-L/usr/X11R6/lib" CFLAGS="-I/usr/X11R6/include" --quiet --disable-deprecated --with-motif --with-forth
make
./snd --version
./snd -noinit --features "'clm 'snd-forth 'snd-motif"
make allclean

echo ' '
echo ' '
echo ' -------------------------------------------------------------------------------- '
echo ' -----                --with-forth  --with-motif --with-editres --with-gl ---- '
echo ' -------------------------------------------------------------------------------- '
./configure --quiet --disable-deprecated --with-forth  --with-motif --with-editres --with-gl LDFLAGS="-L/usr/X11R6/lib" CFLAGS="-I/usr/X11R6/include"
make
./snd --version
./snd -noinit --features "'clm 'snd-forth 'xm 'gl"
make allclean

echo ' '
echo ' '
echo ' -------------------------------------------------------------------------------- '
echo ' -----                --with-forth --with-gtk       --- '
echo ' -------------------------------------------------------------------------------- '
./configure --quiet --disable-deprecated --with-forth --with-gtk  LDFLAGS="-L/usr/X11R6/lib" CFLAGS="-I/usr/X11R6/include"
make
./snd --version
./snd -noinit --features "'clm 'snd-gtk 'xg 'gl"
make allclean

echo ' '
echo ' '
echo ' -------------------------------------------------------------------------------- '
echo ' -----                --with-forth --without-gui                              --- '
echo ' -------------------------------------------------------------------------------- '
./configure --quiet --disable-deprecated --with-forth --without-gui LDFLAGS="-L/usr/X11R6/lib" CFLAGS="-I/usr/X11R6/include"
make
./snd --version
./snd -noinit --features "'clm 'snd-forth 'snd-nogui"
make allclean

echo ' '
echo ' '
echo ' -------------------------------------------------------------------------------- '
echo ' ----                 --without-extension-language                          ----  '
echo ' -------------------------------------------------------------------------------- '
./configure LDFLAGS="-L/usr/X11R6/lib" CFLAGS="-I/usr/X11R6/include" --quiet --disable-deprecated --without-extension-language
make
echo ' '
echo ' '
./snd --version
make allclean

echo ' -------------------------------------------------------------------------------- '
echo ' -----                --without-extension-language --with-gtk               ----  '
echo ' -------------------------------------------------------------------------------- '
./configure --quiet --disable-deprecated --without-extension-language --with-gtk 
make
echo ' '
echo ' '
./snd --version
rm -f sndinfo
make sndinfo
./sndinfo test.snd
make allclean

echo ' -------------------------------------------------------------------------------- '
echo ' ----                 --without-extension-language --with-gl         ------  '
echo ' -------------------------------------------------------------------------------- '
./configure LDFLAGS="-L/usr/X11R6/lib" CFLAGS="-I/usr/X11R6/include" --quiet --disable-deprecated --without-extension-language --with-motif --with-gl
make
echo ' '
echo ' '
./snd --version
make allclean

echo ' -------------------------------------------------------------------------------- '
echo ' -----                --without-extension-language g++                      ----  '
echo ' -------------------------------------------------------------------------------- '
./configure --quiet --disable-deprecated --without-extension-language  CC=g++ LDFLAGS="-L/usr/X11R6/lib" CFLAGS="-I/usr/X11R6/include"
make
echo ' '
echo ' '
./snd --version
make allclean

rm -f snd
rm -f config.cache

echo ' -------------------------------------------------------------------------------- '
echo ' ----                  --with-gtk                                            ---- '
echo ' -------------------------------------------------------------------------------- '
./configure --quiet --disable-deprecated LDFLAGS="-L/usr/X11R6/lib" CFLAGS="-I/usr/X11R6/include"  --with-gtk
make
echo ' '
echo ' '
./snd --version
./snd -noinit --features "'clm 'snd-gtk"
make allclean
rm -f snd
rm -f config.cache

echo ' -------------------------------------------------------------------------------- '
echo ' -----                GTK_DISABLE_DEPRECATED G_DISABLE_DEPRECATED GDK_DISABLE_DEPRECATED --with-gtk  '
echo ' -------------------------------------------------------------------------------- '
./configure --quiet --disable-deprecated --disable-deprecated CFLAGS="-I/usr/X11R6/include -D_FORTIFY_SOURCE" --with-gtk 
make
echo ' '
echo ' '
./snd --version
./snd -noinit --features "'clm 'snd-gtk 'xg"

make allclean
rm -f snd
rm -f sndinfo
rm -f config.cache

echo ' -------------------------------------------------------------------------------- '
echo ' ----                --with-gsl                           ---- '
echo ' -------------------------------------------------------------------------------- '
./configure --quiet --disable-deprecated LDFLAGS="-L/usr/X11R6/lib" CFLAGS="-I/usr/X11R6/include -DXEN_DEBUGGING" --with-motif --with-gsl
make
echo ' '
echo ' '
./snd --version
./snd -noinit --features "'clm 'gsl 'snd-motif"
make allclean

echo ' -------------------------------------------------------------------------------- '
echo ' ----                --with-gmp                                              ---- '
echo ' -------------------------------------------------------------------------------- '
./configure --quiet --disable-deprecated LDFLAGS="-L/usr/X11R6/lib" CFLAGS="-I/usr/X11R6/include" --with-gmp
make
echo ' '
echo ' '
./snd --version
./snd -noinit --features "'clm 'snd-motif 'gmp"
make allclean

echo ' -------------------------------------------------------------------------------- '
echo ' ----                WITH_EXTRA_EXPONENT_MARKERS=0 WITH_AT_SIGN_AS_EXPONENT=0 --- '
echo ' -------------------------------------------------------------------------------- '
./configure --quiet --disable-deprecated LDFLAGS="-L/usr/X11R6/lib" CFLAGS="-I/usr/X11R6/include -DWITH_IMMUTABLE_UNQUOTE=1 -DWITH_SYSTEM_EXTRAS=1 -DWITH_EXTRA_EXPONENT_MARKERS=0 -DWITH_AT_SIGN_AS_EXPONENT=0"
make
echo ' '
echo ' '
./snd --version
./snd -noinit --features "'clm 'snd-motif"
make allclean

echo ' -------------------------------------------------------------------------------- '
echo ' -----                  editres                              ---- '
echo ' -------------------------------------------------------------------------------- '
./configure --quiet --disable-deprecated LDFLAGS="-L/usr/X11R6/lib" CFLAGS="-I/usr/X11R6/include"  --with-motif --with-editres --disable-deprecated
make
make allclean

echo ' '
echo ' '
echo ' -------------------------------------------------------------------------------- '
echo ' -----                g++                                    ---- '
echo ' -------------------------------------------------------------------------------- '
./configure --with-motif LDFLAGS="-L/usr/X11R6/lib" --quiet --disable-deprecated CC=g++  CFLAGS="-I/usr/X11R6/include"
make

make allclean
rm -f snd
rm -f config.cache

echo ' -------------------------------------------------------------------------------- '
echo ' ----                 --with-gtk --with-gmp                                  ---- '
echo ' -------------------------------------------------------------------------------- '
./configure --quiet --disable-deprecated --with-gtk --with-gmp
make
echo ' '
echo ' '
./snd --version
./snd -noinit --features "'clm 'snd-gtk 'gmp"

echo ' '
echo ' '
make allclean
rm -f snd
rm -f config.cache

echo ' -------------------------------------------------------------------------------- '
echo ' -----                --with-ruby                                            ---- '
echo ' -------------------------------------------------------------------------------- '
./configure --quiet --disable-deprecated LDFLAGS="-L/usr/X11R6/lib" CFLAGS="-I/usr/X11R6/include" --with-ruby --with-motif 
make
echo ' '
echo ' '
./snd --version
./snd -noinit --features ":clm, :snd_ruby, :snd_motif"
make allclean

echo ' -------------------------------------------------------------------------------- '
echo ' ----                 g++ --with-ruby                                        ---- '
echo ' -------------------------------------------------------------------------------- '
./configure --quiet --disable-deprecated CC=g++ LDFLAGS="-L/usr/X11R6/lib" CFLAGS="-I/usr/X11R6/include" --with-ruby
make
./snd --version
./snd -noinit --features ":clm, :snd_ruby"
make allclean

echo ' -------------------------------------------------------------------------------- '
echo ' -----                --with-ruby  --with-gl --with-alsa '
echo ' -------------------------------------------------------------------------------- '
./configure --quiet --disable-deprecated LDFLAGS="-L/usr/X11R6/lib" CFLAGS="-I/usr/X11R6/include -DXEN_DEBUGGING" --with-ruby  --with-motif --with-gl --with-alsa
make
echo ' '
echo ' '
./snd --version
./snd -noinit --features ":clm, :alsa, :snd_ruby, :gl"

make allclean
rm -f snd
rm -f config.cache

echo ' -------------------------------------------------------------------------------- '
echo ' ----                 --with-ruby --with-gtk                                 ---- '
echo ' -------------------------------------------------------------------------------- '
./configure --quiet --disable-deprecated LDFLAGS="-L/usr/X11R6/lib" CFLAGS="-I/usr/X11R6/include" --with-ruby --with-gtk
make
echo ' '
echo ' '
./snd --version
./snd -noinit --features ":clm, :snd_gtk, :snd_ruby"
make allclean

echo ' -------------------------------------------------------------------------------- '
echo ' -----                g++ --with-ruby --with-gtk --with-alsa                 ---- '
echo ' -------------------------------------------------------------------------------- '
./configure --quiet --disable-deprecated CC=g++ --with-ruby --with-gtk --with-alsa
make
echo ' '
echo ' '
./snd --version
./snd -noinit --features ":clm, :alsa, :snd_gtk, :snd_ruby"
make allclean

echo ' -------------------------------------------------------------------------------- '
echo ' ----                 --with-ruby  --with-gtk --without-gsl '
echo ' -------------------------------------------------------------------------------- '
./configure --quiet --disable-deprecated LDFLAGS="-L/usr/X11R6/lib" CFLAGS="-I/usr/X11R6/include -DXEN_DEBUGGING" --with-ruby  --with-gtk --without-gsl
make
echo ' '
echo ' '
./snd --version
./snd -noinit --features ":clm, :snd_ruby, :snd_gtk"
make allclean

echo ' -------------------------------------------------------------------------------- '
echo ' ----                GTK_DISABLE_DEPRECATED G_DISABLE_DEPRECATED GDK_DISABLE_DEPRECATED --with-ruby  --with-gtk '
echo ' -------------------------------------------------------------------------------- '
./configure --quiet --disable-deprecated --disable-deprecated LDFLAGS="-L/usr/X11R6/lib" CFLAGS="-I/usr/X11R6/include -D_FORTIFY_SOURCE" --with-ruby  --with-gtk
make
echo ' '
echo ' '
./snd --version
./snd -noinit --features ":clm, :snd-gtk, :xg"

make allclean
rm -f snd
rm -f config.cache

echo ' -------------------------------------------------------------------------------- '
echo ' ----                 --with-ruby --without-gui --without-fftw                --- '
echo ' -------------------------------------------------------------------------------- '
./configure --quiet --disable-deprecated LDFLAGS="-L/usr/X11R6/lib" CFLAGS="-I/usr/X11R6/include" --with-ruby --without-gui --without-fftw
make
echo ' '
echo ' '
./snd --version
./snd -noinit --features ":clm, :snd_nogui, :snd_ruby"
make allclean

echo ' -------------------------------------------------------------------------------- '
echo ' -----                --with-ruby --without-gui           ---- '
echo ' -------------------------------------------------------------------------------- '
./configure --quiet --disable-deprecated LDFLAGS="-L/usr/X11R6/lib" CFLAGS="-I/usr/X11R6/include -DXEN_DEBUGGING" --with-ruby --without-gui 
make
echo ' '
echo ' '
./snd --version
./snd -noinit --features ":clm, :snd_nogui, :snd_ruby"
make allclean

echo ' -------------------------------------------------------------------------------- '
echo ' ----                g++ --with-ruby --without-gui        ---- '
echo ' -------------------------------------------------------------------------------- '
./configure --quiet --disable-deprecated CC=g++ LDFLAGS="-L/usr/X11R6/lib" CFLAGS="-I/usr/X11R6/include -DXEN_DEBUGGING" --with-ruby --without-gui 
make
echo ' '
echo ' '
./snd --version
./snd -noinit --features ":clm, :snd_nogui, :snd_ruby"
make allclean

rm -f snd
rm -f config.cache

echo ' -------------------------------------------------------------------------------- '
echo ' ----                g++                                                      --- '
echo ' -------------------------------------------------------------------------------- '
./configure --quiet --disable-deprecated --with-motif CC=g++ LDFLAGS="-L/usr/X11R6/lib" CFLAGS="-I/usr/X11R6/include"
make
./snd --version
./snd -noinit --features "'clm 'snd-s7 'snd-motif 'snd-ladspa 'sndlib"
make sndinfo
make sndplay
./sndinfo test.snd
make allclean

echo ' '
echo ' '
echo ' -------------------------------------------------------------------------------- '
echo ' ----                g++ --with-gtk                                          ---- '
echo ' -------------------------------------------------------------------------------- '
./configure --quiet --disable-deprecated CC=g++ --with-gtk
make
./snd --version
./snd -noinit --features "'clm 'snd-gtk"
make allclean

echo ' '
echo ' '
echo ' -------------------------------------------------------------------------------- '
echo ' ----                g++ --without-gui                                       ---- '
echo ' -------------------------------------------------------------------------------- '
./configure LDFLAGS="-L/usr/X11R6/lib" CFLAGS="-I/usr/X11R6/include" --quiet --disable-deprecated CC=g++ --without-gui
make
./snd --version
./snd -noinit --features "'clm 'snd-nogui 'snd-s7"
make allclean

echo ' -------------------------------------------------------------------------------- '
echo ' -----                g++ --without-extension-language                     ---- '
echo ' -------------------------------------------------------------------------------- '
./configure LDFLAGS="-L/usr/X11R6/lib" CFLAGS="-I/usr/X11R6/include" --quiet --disable-deprecated CC=g++ --without-extension-language
make
./snd --version
make allclean
echo ' '
echo ' '

echo ' -------------------------------------------------------------------------------- '
echo ' -----                g++  --without-gsl --with-alsa '
echo ' -------------------------------------------------------------------------------- '
./configure LDFLAGS="-L/usr/X11R6/lib" CFLAGS="-I/usr/X11R6/include" --quiet --disable-deprecated CC=g++  --without-gsl --with-alsa
make
./snd --version
./snd -noinit --features "'clm 'alsa 'xm"
make allclean
echo ' '
echo ' '

make allclean
rm -f snd
rm -f config.cache
rm -f sndinfo

echo ' -------------------------------------------------------------------------------- '
echo ' -----                sndlib                                                 ---- '
echo ' -------------------------------------------------------------------------------- '
./configure --quiet --disable-deprecated LDFLAGS="-L/usr/X11R6/lib" CFLAGS="-I/usr/X11R6/include"
make sndinfo
sndinfo oboe.snd
sndinfo test.snd
make allclean
echo ' '
echo ' '

echo ' -------------------------------------------------------------------------------- '
echo ' ----                 --without-gui                                          ---- '
echo ' -------------------------------------------------------------------------------- '
./configure --quiet --disable-deprecated LDFLAGS="-L/usr/X11R6/lib" CFLAGS="-I/usr/X11R6/include" --without-gui
make
echo ' '
echo ' '
./snd --version
./snd -noinit --features "'clm 'snd-nogui 'snd-s7"

make allclean
rm -f snd
rm -f config.cache
rm -f makefile
rm -f mus-config.h

echo ' '
echo ' '
echo ' -------------------------------------------------------------------------------- '
echo ' -----                 -DXM_DISABLE_DEPRECATED              ----- '
echo ' -------------------------------------------------------------------------------- '
./configure --quiet --disable-deprecated  LDFLAGS="-L/usr/X11R6/lib" CFLAGS="-DXM_DISABLE_DEPRECATED -Wall -I/usr/X11R6/include"
make
./snd --version
./snd -noinit --features "'clm 'xm"
make allclean
echo ' '
echo ' '

echo ' -------------------------------------------------------------------------------- '
echo ' -----                 --with-ruby -DXM_DISABLE_DEPRECATED   ---- '
echo ' -------------------------------------------------------------------------------- '
./configure --quiet --disable-deprecated  --with-ruby LDFLAGS="-L/usr/X11R6/lib" CFLAGS="-DXM_DISABLE_DEPRECATED -Wall -I/usr/X11R6/include"
make
./snd --version
./snd -noinit --features ":clm, :snd_ruby"
make allclean

echo ' '
echo ' '
echo ' -------------------------------------------------------------------------------- '
echo ' -----                --without-gui --without-extension-language          ----- '
echo ' -------------------------------------------------------------------------------- '
./configure LDFLAGS="-L/usr/X11R6/lib" CFLAGS="-I/usr/X11R6/include" --without-gui --without-extension-language --quiet --disable-deprecated
make
./snd --version
make allclean
echo ' '
echo ' '

echo ' -------------------------------------------------------------------------------- '
echo ' ----                 --without-extension-language  --with-gl - '
echo ' -------------------------------------------------------------------------------- '
./configure LDFLAGS="-L/usr/X11R6/lib" CFLAGS="-I/usr/X11R6/include" --without-extension-language  --with-motif --with-gl --quiet --disable-deprecated
make
./snd --version
make allclean
echo ' '
echo ' '

echo ' -------------------------------------------------------------------------------- '
echo ' -----                 --with-gl --with-gl2ps         ------ '
echo ' -------------------------------------------------------------------------------- '
./configure LDFLAGS="-L/usr/X11R6/lib" CFLAGS="-I/usr/X11R6/include"  --with-motif --with-gl --quiet --disable-deprecated --with-gl2ps
make
./snd --version
./snd -noinit --features "'clm 'xm 'gl2ps"
make allclean
echo ' '
echo ' '

echo ' -------------------------------------------------------------------------------- '
echo ' -----                --without-extension-language --with-gtk                ---- '
echo ' -------------------------------------------------------------------------------- '
./configure --without-extension-language --with-gtk  --quiet --disable-deprecated
make
./snd --version
make allclean
echo ' '
echo ' '

echo ' -------------------------------------------------------------------------------- '
echo ' ----                 --with-portaudio                                       ---- '
echo ' -------------------------------------------------------------------------------- '
./configure --with-portaudio --quiet --disable-deprecated
make
./snd --version
./snd -noinit --features "'clm 'snd-gtk"
make allclean



echo ' -------------------------------------------------------------------------------- '
echo ' ----                 --with-jack                                       ---- '
echo ' -------------------------------------------------------------------------------- '
./configure --with-jack --with-alsa --quiet --disable-deprecated
make
./snd --version
./snd -noinit --features "'clm 'snd-gtk"
make allclean



echo ' -------------------------------------------------------------------------------- '
echo ' ----                 --with-pulseaudio                                      ---- '
echo ' -------------------------------------------------------------------------------- '
./configure --with-pulseaudio --quiet --disable-deprecated
make
./snd --version
./snd -noinit --features "'clm 'snd-gtk"
make allclean



cp ~/sndlib/* .
echo ' -------------------------------------------------------------------------------- '
echo ' -----                sndlib tests                                           ---- '
echo ' -------------------------------------------------------------------------------- '
./configure --quiet --disable-deprecated CFLAGS="-Wall"
make

cp tools/exs7.c .
echo ' -------------------------------------------------------------------------------- '
echo ' -------------------------------- ex 1 -------------------------------- '
echo ' -------------------------------------------------------------------------------- '
gcc -o exs7 exs7.c s7.o -lm -DEX1 -ldl
echo ' -------------------------------------------------------------------------------- '
echo ' -------------------------------- ex 2 -------------------------------- '
echo ' -------------------------------------------------------------------------------- '
gcc -o exs7 exs7.c s7.o -lm -DEX2 -ldl
echo ' -------------------------------------------------------------------------------- '
echo ' -------------------------------- ex 3 -------------------------------- '
echo ' -------------------------------------------------------------------------------- '
gcc -o exs7 exs7.c s7.o -lm -DEX3 -ldl
echo ' -------------------------------------------------------------------------------- '
echo ' -------------------------------- ex 4 -------------------------------- '
echo ' -------------------------------------------------------------------------------- '
gcc -o exs7 exs7.c s7.o -lm -DEX4 -ldl
echo ' -------------------------------------------------------------------------------- '
echo ' -------------------------------- ex 5 -------------------------------- '
echo ' -------------------------------------------------------------------------------- '
gcc -o exs7 exs7.c s7.o -lm -DEX5 -ldl
echo ' -------------------------------------------------------------------------------- '
echo ' -------------------------------- ex 6 -------------------------------- '
echo ' -------------------------------------------------------------------------------- '
gcc -o exs7 exs7.c s7.o -lm -DEX6 -ldl

make clean
echo ' -------------------------------------------------------------------------------- '
echo ' -------------------------------- sndlib ruby -------------------------------- '
echo ' -------------------------------------------------------------------------------- '
./configure --quiet --disable-deprecated --with-ruby
make
make clean
echo ' -------------------------------------------------------------------------------- '
echo ' -------------------------------- sndlib forth -------------------------------- '
echo ' -------------------------------------------------------------------------------- '
./configure --quiet --disable-deprecated --with-forth
make
make clean
echo ' -------------------------------------------------------------------------------- '
echo ' -------------------------------- sndlib s7 c++ -------------------------------- '
echo ' -------------------------------------------------------------------------------- '
./configure --quiet --disable-deprecated CC=g++
make
echo ' -------------------------------------------------------------------------------- '
echo ' -------------------------------- ex 1 -------------------------------- '
echo ' -------------------------------------------------------------------------------- '
g++ -o exs7 exs7.c s7.o -lm -DEX1 -ldl
echo ' -------------------------------------------------------------------------------- '
echo ' -------------------------------- ex 2 -------------------------------- '
echo ' -------------------------------------------------------------------------------- '
g++ -o exs7 exs7.c s7.o -lm -DEX2 -ldl
echo ' -------------------------------------------------------------------------------- '
echo ' -------------------------------- ex 3 -------------------------------- '
echo ' -------------------------------------------------------------------------------- '
g++ -o exs7 exs7.c s7.o -lm -DEX3 -ldl
echo ' -------------------------------------------------------------------------------- '
echo ' -------------------------------- ex 4 -------------------------------- '
echo ' -------------------------------------------------------------------------------- '
g++ -o exs7 exs7.c s7.o -lm -DEX4  -ldl /home/bil/test/sndlib/libsndlib.a -lgsl -lgslcblas -lasound
echo ' -------------------------------------------------------------------------------- '
echo ' -------------------------------- ex 5 -------------------------------- '
echo ' -------------------------------------------------------------------------------- '
g++ -o exs7 exs7.c s7.o -lm -DEX5 -ldl
echo ' -------------------------------------------------------------------------------- '
echo ' -------------------------------- ex 6 -------------------------------- '
echo ' -------------------------------------------------------------------------------- '
g++ -o exs7 exs7.c s7.o -lm -DEX6 -ldl
rm exs7
rm exs7.o
make clean

echo ' -------------------------------------------------------------------------------- '
echo ' -------------------------------- with int s7_Int -------------------------------- '
echo ' -------------------------------------------------------------------------------- '
sed s7.h -e 's/#define s7_Int long long int/#define s7_Int int/' > tmp
mv tmp s7.c
sed s7.h -e 's/#define s7_Int_d "%lld"/#define s7_Int_d "%d"/' > tmp
mv tmp s7.c
make
make clean
