#!/bin/csh -f

set gtkolddir = /home/bil/test/gtk+-3.9.4
set gtknewdir = /home/bil/test/gtk+-3.9.6
set pangoolddir = /home/bil/test/pango-1.34.1
set pangonewdir = /home/bil/test/pango-1.35.0
set curdir = $cwd

date > $curdir/hi
echo ' ' >> $curdir/hi

chdir $gtknewdir/gdk
foreach file (*.h)
  echo '---------------------------------  ' $file '        --------------------------------' >> $curdir/hi
  if (-e $gtkolddir/gdk/$file) then
    diff -bcw $gtkolddir/gdk/$file $gtknewdir/gdk/$file >> $curdir/hi
  else
    echo '(new)' >> $curdir/hi
  endif
end

chdir $gtknewdir/gtk
foreach file (*.h)
  echo '---------------------------------  ' $file '        --------------------------------' >> $curdir/hi
  if (-e $gtkolddir/gtk/$file) then
    diff -bcw $gtkolddir/gtk/$file $gtknewdir/gtk/$file >> $curdir/hi
  else
    echo '(new)' >> $curdir/hi
  endif
end

chdir $pangonewdir/pango
foreach file (*.h)
  echo '---------------------------------  ' $file '        --------------------------------' >> $curdir/hi
  if (-e $pangoolddir/pango/$file) then
    diff -bcw $pangoolddir/pango/$file $pangonewdir/pango/$file >> $curdir/hi
  else
    echo '(new)' >> $curdir/hi
  endif
end

