#!/bin/csh -f

set snddir = /usr/ccrma/lisp/src/snd
set sndtools = /usr/ccrma/lisp/src/snd/tools
set curdir = $cwd
set curtools = $cwd/tools

date > $curdir/hi
echo ' ' >> $curdir/hi

chdir snddir
foreach file (*.h *.c *.cl *.el *.clm *.fs *.js *.html makefile.* make.* *.gtkrc *.in *.scm *.lisp snd.spec old-snd.spec *.Snd Snd.ad snd.1 configure.ac *.rb *.m4 config.guess config.sub NEWS *.tex)
  if (-e $curdir/$file) then
    diff -bcw $curdir/$file $snddir/$file >> $curdir/hi
    find $curdir/$file -newer $snddir/$file -exec echo ' updating ' $file \;
    find $curdir/$file -newer $snddir/$file -exec cp $curdir/$file $snddir \;
  endif
end

chdir curtools
foreach file (*)
  if (-e $curdir/$file) then
    diff -bcw $curdir/$file $curtools/$file >> $curdir/hi
    find $curdir/$file -newer $curtools/$file -exec echo ' updating ' tools/$file \;
    find $curdir/$file -newer $curtools/$file -exec cp $curdir/$file $curtools \;
  endif
end

chdir sndtools
foreach file (*)
  if (-e $curtools/$file) then
    diff -bcw $curtools/$file $sndtools/$file >> $curdir/hi
    find $curtools/$file -newer $sndtools/$file -exec echo ' updating ' tools/$file \;
    find $curtools/$file -newer $sndtools/$file -exec cp $curtools/$file $sndtools \;
  endif
end

cp $curdir/configure $snddir

chdir curdir
wc hi
xgettext --keyword=_ --keyword=N_ --files-from=po/POTFILES.in -o po/snd.pot
cp po/snd.pot $snddir/po/snd.pot
