#!/bin/csh -f

echo ' -------------------------------- without-gui -------------------------------- '
rm -f snd
rm -f config.cache
./configure --quiet CFLAGS="-Wall -I/usr/local/include" --without-gui
make
echo ' '
echo ' '
./snd --version
./snd -l snd-test
echo ' '
echo ' '
echo ' -------------------------------- that was snd-test without-gui (also s7test) -------------------------------- '
echo ' '
echo ' '

./snd lint.scm -e '(begin (lint "s7test.scm" #f) (exit))'

valgrind ./snd -noinit -l snd-test
echo ' '
echo ' '
echo ' -------------------------------- that was valgrind without-gui (also s7test) -------------------------------- '
echo ' '
echo ' '

gcc s7.c -o repl -DWITH_MAIN -I. -O2 -g -lreadline -lncurses -ldl -lm 
./repl tools/t456.scm

echo ' '
echo ' '
echo ' -------------------------------- that was s7 t456 -------------------------------- '
echo ' '
echo ' '

echo ' -------------------------------- without-gui DEBUGGING=1 -------------------------------- '
rm -f snd
rm -f config.cache
./configure --quiet CFLAGS="-Wall -I/usr/local/include -DDEBUGGING" --without-gui --disable-deprecated
make
echo ' '
echo ' '
./snd --version
./snd -l snd-test
echo ' '
echo ' '
echo ' -------------------------------- that was snd-test without-gui debugging -------------------------------- '
echo ' '
echo ' '

echo ' -------------------------------- without-gui CC=g++ --disable-deprecated -------------------------------- '
make allclean
rm -f snd
rm -f config.cache
./configure --quiet CFLAGS="-Wall" --without-gui --disable-deprecated CC=g++
make
echo ' '
echo ' '
./snd --version
./snd -l snd-test
echo ' '
echo ' '
echo ' -------------------------------- that was snd-test g++/disable-deprecated -------------------------------- '
echo ' '
echo ' '

valgrind ./snd -l snd-test
echo ' '
echo ' '
echo ' -------------------------------- that was valgrind g++ -------------------------------- '
echo ' '
echo ' '

echo ' -------------------------------- without-gui --with-gmp -------------------------------- '
make allclean
rm -f snd
rm -f config.cache
./configure --quiet CFLAGS="-Wall" --without-gui --with-gmp --disable-deprecated
make
echo ' '
echo ' '
./snd --version
./snd -l snd-test
echo ' '
echo ' '
echo ' -------------------------------- that was snd-test --with-gmp -------------------------------- '
echo ' '
echo ' '

valgrind ./snd -l snd-test
echo ' '
echo ' '
echo ' -------------------------------- that was valgrind --with-gmp -------------------------------- '
echo ' '
echo ' '

# gcc s7.c -o repl -DWITH_MAIN -I. -O2 -g -lreadline -lncurses -ldl -lm -lgmp -lmpfr -lmpc
# ./repl tools/t456.scm

echo ' -------------------------------- motif -------------------------------- '
make allclean
rm -f snd
rm -f config.cache
./configure --quiet --with-motif CFLAGS="-Wall -I/usr/X11R6/include" LDFLAGS="-L/usr/X11R6/lib"
make
echo ' '
echo ' '
./snd --version
./snd -l snd-test 23
./snd -noinit -l snd-test
./snd -l snd-test
make clmclean
make sndinfo
./sndinfo oboe.snd
make sndplay
./sndplay oboe.snd
echo ' '
echo ' '
echo ' -------------------------------- that was motif? and test 23 -------------------------------- '
echo ' '
echo ' '

valgrind ./snd -l snd-test
echo ' '
echo ' '
echo ' -------------------------------- that was valgrind --with-motif? -------------------------------- '
echo ' '
echo ' '

echo ' -------------------------------- motif + gl -------------------------------- '
make allclean
rm -f snd
rm -f config.cache
./configure --quiet --with-gl --with-motif CFLAGS="-Wall -I/usr/X11R6/include" LDFLAGS="-L/usr/X11R6/lib"
make
echo ' '
echo ' '
./snd --version
./snd -l snd-test 24
./snd -l snd-test
echo ' '
echo ' '
echo ' -------------------------------- that was motif? and gl -------------------------------- '
echo ' '
echo ' '

valgrind ./snd -l snd-test
echo ' '
echo ' '
echo ' -------------------------------- that was valgrind --with-motif and gl -------------------------------- '
echo ' '
echo ' '

make allclean
rm -f snd
rm -f config.cache
./configure --quiet CC=/home/bil/test/llvm-3.1.src/build/Release+Asserts/bin/clang CFLAGS="-Wall" LDFLAGS="-Wl,-export-dynamic"
make
./snd --version
./snd -l snd-test
echo ' '
echo ' '
echo ' -------------------------------- that was clang? -------------------------------- '
echo ' '
echo ' '


echo ' -------------------------------- with-gtk -------------------------------- '
make allclean
rm -f snd
rm -f config.cache
./configure --quiet CFLAGS="-Wall" --with-gtk --disable-deprecated
make
echo ' '
echo ' '
./snd --version
./snd tools/va.scm
./snd -noinit -l snd-test
./snd -l snd-test
echo ' '
echo ' '
echo ' -------------------------------- that was snd-test --with-gtk -------------------------------- '
echo ' '
echo ' '

# echo ' -------------------------------- valgrind --with-gtk takes forever! -------------------------------- '
# valgrind ./snd -l snd-test
# echo ' '
# echo ' '
# echo ' -------------------------------- that was valgrind --with-gtk -------------------------------- '
# echo ' '
# echo ' '


cp snd-test.scm orig-snd-test.scm
./snd tools/sed.scm -e '(sed "snd-test.scm" "tmp" "(define tests 1)" "(define tests 7)")'
# sed snd-test.scm -e 's/(define tests 1)/(define tests 7)/g' > tmp
# sed differs so much between systems that it is useless
mv tmp snd-test.scm

echo ' -------------------------------- without-gui -------------------------------- '
make allclean
rm -f snd
rm -f config.cache
./configure --quiet CFLAGS="-Wall" --without-gui
make
echo ' '
echo ' '
./snd --version
./snd -l snd-test
echo ' '
echo ' '
echo ' -------------------------------- that was snd-test mult without-gui -------------------------------- '
echo ' '
echo ' '

valgrind ./snd -l snd-test
echo ' '
echo ' '
echo ' -------------------------------- that was valgrind mult -------------------------------- '
echo ' '
echo ' '


cp orig-snd-test.scm snd-test.scm
./snd tools/sed.scm -e '(sed "snd-test.scm" "tmp" "(define test-at-random 0)" "(define test-at-random 300)")'
# sed snd-test.scm -e 's/(define test-at-random 0)/(define test-at-random 300)/g' > tmp
mv tmp snd-test.scm

echo ' '
echo ' '
./snd --version
./snd -l snd-test
echo ' '
echo ' '
echo ' -------------------------------- that was snd-test at-random without-gui -------------------------------- '
echo ' '
echo ' '

valgrind ./snd -l snd-test
echo ' '
echo ' '
echo ' -------------------------------- that was valgrind at-random -------------------------------- '
echo ' '
echo ' '


cp orig-snd-test.scm snd-test.scm
./snd tools/sed.scm -e '(sed "snd-test.scm" "tmp" "(define all-args #f)" "(define all-args #t)")'
# sed snd-test.scm -e 's/(define all-args #f)/(define all-args #t)/g' > tmp
mv tmp snd-test.scm

echo ' '
echo ' '
./snd --version
./snd -l snd-test
echo ' '
echo ' '
echo ' -------------------------------- that was snd-test full without-gui -------------------------------- '
echo ' '
echo ' '

valgrind ./snd -l snd-test
echo ' '
echo ' '
echo ' -------------------------------- that was valgrind full -------------------------------- '
echo ' '
echo ' '

make allclean
rm -f snd
rm -f config.cache
./configure --quiet CFLAGS="-Wall" CC=g++
make
echo ' '
echo ' '
./snd --version
./snd -l snd-test
echo ' '
echo ' '
echo ' -------------------------------- that was snd-test full g++ -------------------------------- '
echo ' '
echo ' '

make allclean
rm -f snd
rm -f config.cache
./configure --quiet CFLAGS="-Wall" --with-gtk --with-ladspa --without-audio
make
echo ' '
echo ' '
./snd --version
./snd -l snd-test
echo ' '
echo ' '
echo ' -------------------------------- that was snd-test full gtk ladspa-------------------------------- '
echo ' '
echo ' '

make allclean
rm -f snd
rm -f config.cache
./configure --quiet CFLAGS="-Wall" --with-gmp --without-gui
make
echo ' '
echo ' '
./snd --version
./snd -l snd-test
echo ' '
echo ' '
echo ' -------------------------------- that was snd-test full gmp -------------------------------- '
echo ' '
echo ' '

./snd tools/sed.scm -e '(sed "snd-test.scm" "tmp" "(define tests 1)" "(define tests 7)")'
# sed snd-test.scm -e 's/(define tests 1)/(define tests 7)/g' > tmp
mv tmp snd-test.scm

make allclean
rm -f snd
rm -f config.cache
./configure --quiet CFLAGS="-Wall" --without-gui
make
echo ' '
echo ' '
./snd -l snd-test
echo ' '
echo ' '
echo ' -------------------------------- that was snd-test full mult no-gui -------------------------------- '
echo ' '
echo ' '

cp orig-snd-test.scm snd-test.scm
