#!/bin/csh -f

echo ' -------------------------------- basic configure test -------------------------------- '
rm -f snd
rm -f config.cache
echo ' CFLAGS="-Wall"  '
./configure --quiet CFLAGS="-Wall -I/usr/X11R6/include" LDFLAGS="-L/usr/X11R6/lib"
make allclean
make
echo ' '
echo ' '
./snd --version
./snd -l snd-test 0
make clmclean
make sndinfo
./sndinfo oboe.snd
make sndplay
./sndplay oboe.snd


echo ' -------------------------------- basic configure -------------------------------- '
make allclean
echo ' CFLAGS="-Wall -I/usr/X11R6/include" '
./configure --quiet CFLAGS="-Wall -I/usr/X11R6/include" LDFLAGS="-L/usr/X11R6/lib"
make
./snd --version
./snd -l snd-test 0
make allclean

echo ' -------------------------------- without-gui -------------------------------- '
make allclean
rm -f snd
rm -f config.cache
echo ' CFLAGS="-Wall -I/usr/X11R6/include" --without-gui '
./configure --quiet CFLAGS="-Wall" --without-gui
make
echo ' '
echo ' '
./snd --version
./snd -l snd-test 2
./snd -l snd-test 28

echo ' -------------------------------- without-gui/ladspa -------------------------------- '
make allclean
rm -f snd
rm -f config.cache
echo ' CFLAGS="-Wall" --without-gui --without-ladspa '
./configure --quiet CFLAGS="-Wall" --without-gui --without-ladspa
make
echo ' '
echo ' '
./snd --version
./snd -l snd-test 3

echo ' -------------------------------- gtk -------------------------------- '
make allclean
rm -f snd
rm -f config.cache
echo ' CFLAGS="-Wall" --with-gtk '
./configure --quiet CFLAGS="-Wall" --with-gtk
make
echo ' '
echo ' '
./snd --version 2
./snd --version 8
./snd -l snd-test 10
rm xg.o
echo ' CC=g++ CFLAGS="-Wall" --with-gtk '
./configure --quiet CC=g++ CFLAGS="-Wall" --with-gtk --disable-deprecated
make allclean
echo ' CC=g++ --with-gtk CFLAGS="-Wall" '
./configure --quiet CC=g++ --with-gtk CFLAGS="-Wall"
make
./snd --version
./snd -l snd-test 9

echo ' '
echo ' -------------------------------- configure --with-gtk test -------------------------------- '
make allclean
rm -f snd
rm -f config.cache
echo ' CFLAGS="-Wall"  --with-gtk '
./configure --quiet CFLAGS="-Wall"  --with-gtk
make
echo ' '
echo ' '
./snd --version
./snd -l snd-test 7
make allclean
rm -f snd
rm -f config.cache
echo ' CFLAGS="-Wall"  --with-gtk '
./configure --quiet CFLAGS="-Wall"  --with-gtk
make
echo ' '
echo ' '
./snd --version
./snd -l snd-test
echo ' -------------------------------- that was full snd-test with-gtk -------------------------------- '
make allclean
echo ' CFLAGS="-Wall -DGTK_DISABLE_DEPRECATED -DG_DISABLE_DEPRECATED -DGDK_DISABLE_DEPRECATED" --with-gtk '
./configure --quiet --disable-deprecated CFLAGS="-Wall" --with-gtk
make
./snd --version
./snd -l snd-test 11
echo ' '
echo ' '
date
echo ' -------------------------------- motif test -------------------------------- '
make allclean
rm -f snd
rm -f sndinfo
rm -f config.cache
echo ' CFLAGS="-Wall -I/usr/X11R6/include" --with-gsl '
./configure --quiet CFLAGS="-Wall -I/usr/X11R6/include" --with-gsl LDFLAGS="-L/usr/X11R6/lib"
make
echo ' '
echo ' '
./snd --version
./snd -l snd-test
echo ' -------------------------------- that was full snd-test with-motif -------------------------------- '
rm xm.o
echo ' CC=g++ '
./configure --quiet CC=g++ CFLAGS="-I/usr/X11R6/include" LDFLAGS="-L/usr/X11R6/lib"
./snd --version
./snd -l snd-test 12

make allclean
echo ' CFLAGS="-Wall -I/usr/X11R6/include" '
./configure --quiet CFLAGS="-Wall -I/usr/X11R6/include" LDFLAGS="-L/usr/X11R6/lib"
make
./snd --version
./snd -l snd-test 8

echo ' '
echo ' '
date
echo ' -------------------------------- gtk test -------------------------------- '
make allclean
rm -f snd
rm -f config.cache
echo ' CFLAGS="-Wall" --with-gtk --with-gsl '
./configure --quiet CFLAGS="-Wall" --with-gtk --with-gsl
make
echo ' '
echo ' '
./snd --version
./snd -l snd-test 14

echo ' '
echo ' '
date
echo ' -------------------------------- ruby test (Motif) -------------------------------- '
make allclean
rm -f snd
rm -f config.cache
echo ' CFLAGS="-Wall -I/usr/X11R6/include" --with-ruby '
./configure --quiet CFLAGS="-Wall -I/usr/X11R6/include" --with-ruby LDFLAGS="-L/usr/X11R6/lib"
make
echo ' '
echo ' '
echo ' '
echo ' '
./snd --version
# ./snd -l snd-test.rb -- libxm problem here stops entire sequence
make allclean
echo ' CC=g++ CFLAGS="-Wall -I/usr/X11R6/include" --with-ruby '
./configure --quiet CC=g++ CFLAGS="-Wall -I/usr/X11R6/include" --with-ruby LDFLAGS="-L/usr/X11R6/lib"
make
echo ' '
echo ' '
echo ' -------------------------------- ruby test (Gtk) -------------------------------- '
make allclean
rm -f snd
rm -f config.cache
echo ' CFLAGS="-Wall" --with-ruby --with-gtk '
./configure --quiet CFLAGS="-Wall" --with-ruby --with-gtk
make
echo ' '
echo ' '
./snd --version
make allclean
echo ' CC=g++ --with-ruby --with-gtk '
./configure --quiet CC=g++ --with-ruby --with-gtk
make
echo ' '
echo ' '
make allclean
echo ' CFLAGS="-Wall" --with-ruby --with-gtk --without-gsl '
./configure --quiet CFLAGS="-Wall" --with-ruby --with-gtk --without-gsl
make
echo ' '
echo ' '
./snd --version
make allclean
echo ' CFLAGS="-Wall -DGTK_DISABLE_DEPRECATED -DG_DISABLE_DEPRECATED -DGDK_DISABLE_DEPRECATED" --with-ruby --with-gtk '
./configure --quiet --disable-deprecated CFLAGS="-Wall" --with-ruby --with-gtk
make
echo ' '
echo ' -------------------------------- ruby test (no gui) -------------------------------- '
make allclean
rm -f snd
rm -f config.cache
echo ' CFLAGS="-Wall" --with-ruby --without-gui --without-fftw '
./configure --quiet CFLAGS="-Wall" --with-ruby --without-gui --without-fftw
make
echo ' '
echo ' '
./snd --version
make allclean
echo ' CFLAGS="-Wall" --with-ruby --without-gui '
./configure --quiet CFLAGS="-Wall" --with-ruby --without-gui 
make
echo ' '
echo ' '
./snd --version
make allclean
echo ' CC=g++ CFLAGS="-Wall" --with-ruby --without-gui '
./configure --quiet CC=g++ CFLAGS="-Wall" --with-ruby --without-gui 
make

echo ' '
echo ' '
date
echo ' -------------------------------- g++ test -------------------------------- '
make allclean
rm -f snd
rm -f config.cache
echo ' CC=g++ CFLAGS="-Wall -I/usr/X11R6/include" '
./configure --quiet CC=g++ CFLAGS="-Wall -I/usr/X11R6/include" LDFLAGS="-L/usr/X11R6/lib"
make
make sndinfo
make sndplay
./sndinfo test.snd
./snd --version
./snd -l snd-test 16
make allclean
echo ' '
echo ' '
echo ' CC=g++ --with-gtk '
./configure --quiet CC=g++ --with-gtk
make
./snd --version
./snd -l snd-test 17
./snd -l snd-test 20
make allclean
echo ' '
echo ' '
echo ' CC=g++ --without-gui '
./configure --quiet CC=g++ --without-gui
make
./snd --version
./snd -l snd-test 6
make allclean
echo ' '
echo ' '
date
echo ' -------------------------------- sndlib test -------------------------------- '
make allclean
rm -f snd
rm -f config.cache
rm -f sndinfo
echo ' CFLAGS="-Wall" '
./configure --quiet CFLAGS="-Wall -I/usr/X11R6/include" LDFLAGS="-L/usr/X11R6/lib"
make sndinfo
./sndinfo oboe.snd

echo ' '
echo ' '
date
echo ' -------------------------------- no-gui test -------------------------------- '
make allclean
rm -f snd
echo ' CFLAGS="-Wall" --without-gui '
./configure --quiet CFLAGS="-Wall" --without-gui
make
./snd --version
./snd -l snd-test 20
./snd -l snd-test 8
echo ' '
echo ' '
date
make allclean


echo ' -------------------------------- s7 gc tests -------------------------------- '
make allclean
rm -f snd
echo ' CFLAGS="-Wall -DINITIAL_HEAP_SIZE=1024" --without-gui '
./configure --quiet CFLAGS="-Wall -DINITIAL_HEAP_SIZE=1024" --without-gui
make
./snd -l snd-test 29
echo ' '
echo ' '
date
rm s7.o

echo ' CFLAGS="-Wall -DINITIAL_HEAP_SIZE=1824" --without-gui '
./configure --quiet CFLAGS="-Wall -DINITIAL_HEAP_SIZE=1824" --without-gui
make
./snd -l snd-test 29
echo ' '
echo ' '
date
rm s7.o

echo ' CFLAGS="-Wall -DINITIAL_HEAP_SIZE=736" --without-gui '
./configure --quiet CFLAGS="-Wall -DINITIAL_HEAP_SIZE=736" --without-gui
make
./snd -l snd-test 29
echo ' '
echo ' '
date
make allclean



